#!/bin/sh
# generate-auth.sh — builds the Angie include that turns on HTTP Basic
# Authentication (plus its per-IP rate limit) at container start.
#
# Invoked by deploy/docker-entrypoint.sh before angie starts. Any failure
# aborts container start (fail closed): the proxy either comes up fully
# authenticated or not at all — never anonymously by accident.
#
# Inputs (environment):
#   MANGA_READER_BASIC_AUTH_ENABLED  true|1|yes enables; false|0|no|"" disables;
#                                    any other value is an error
#   MANGA_READER_BASIC_AUTH_FILE     path to an existing htpasswd file
#                                    (preferred: docker secret; must be
#                                    world-readable for the angie worker,
#                                    i.e. chmod 644)
#   MANGA_READER_BASIC_AUTH_USERNAME + MANGA_READER_BASIC_AUTH_PASSWORD
#                                    single user; the password is piped into
#                                    htpasswd (never on argv) and stored as an
#                                    apr1 ($1$) hash in ANGIE_HTPASSWD
#   MANGA_READER_BASIC_AUTH_PASSWORD_FILE
#                                    like PASSWORD, but read from a file
#                                    (first line; docker-secret friendly)
#   ANGIE_AUTH_CONF                  include path (default /etc/angie/basic-auth.conf)
#   ANGIE_HTPASSWD                   generated htpasswd path (default /etc/angie/htpasswd)
#
# Apr1 instead of bcrypt on purpose: Angie runs on Alpine/musl, whose crypt()
# has no bcrypt support — a $2y$ hash would reject even correct passwords.
# nginx itself implements $1$, so apr1 always verifies.
#
# Never prints credentials; messages carry paths and modes only.

set -eu

CONF_PATH="${ANGIE_AUTH_CONF:-/etc/angie/basic-auth.conf}"
HTPASSWD_PATH="${ANGIE_HTPASSWD:-/etc/angie/htpasswd}"
REALM="Manga Reader"

die() {
    echo "generate-auth: $*" >&2
    exit 1
}

write_disabled() {
    mkdir -p "$(dirname "$CONF_PATH")"
    cat >"$CONF_PATH" <<'EOF'
# HTTP Basic Authentication disabled (MANGA_READER_BASIC_AUTH_ENABLED is off).
EOF
}

enabled="$(printf '%s' "${MANGA_READER_BASIC_AUTH_ENABLED:-false}" | tr '[:upper:]' '[:lower:]')"

case "$enabled" in
    true | 1 | yes) ;;
    false | 0 | no | "")
        write_disabled
        exit 0
        ;;
    *)
        # Deliberately does not echo the raw value: mis-pasted secrets stay out of logs.
        die "invalid MANGA_READER_BASIC_AUTH_ENABLED value (want true/false)"
        ;;
esac

# --- resolve the credential source -----------------------------------------

auth_file=""

if [ -n "${MANGA_READER_BASIC_AUTH_FILE:-}" ]; then
    auth_file="$MANGA_READER_BASIC_AUTH_FILE"
    [ -f "$auth_file" ] || die "MANGA_READER_BASIC_AUTH_FILE not found: $auth_file"
    [ -s "$auth_file" ] || die "MANGA_READER_BASIC_AUTH_FILE is empty: $auth_file"
    mode=$(stat -c '%a' "$auth_file" 2>/dev/null || stat -f '%Lp' "$auth_file" 2>/dev/null || echo "")
    last_digit=$(printf '%s' "$mode" | tail -c 1)
    case "$last_digit" in
        4 | 5 | 6 | 7) ;;
        *) die "MANGA_READER_BASIC_AUTH_FILE must be world-readable for the angie worker (chmod 644): $auth_file" ;;
    esac
    echo "generate-auth: basic auth enabled (htpasswd file: $auth_file)" >&2
else
    user="${MANGA_READER_BASIC_AUTH_USERNAME:-}"
    pass=""
    if [ -n "${MANGA_READER_BASIC_AUTH_PASSWORD:-}" ]; then
        pass="$MANGA_READER_BASIC_AUTH_PASSWORD"
    elif [ -n "${MANGA_READER_BASIC_AUTH_PASSWORD_FILE:-}" ]; then
        pw_file="$MANGA_READER_BASIC_AUTH_PASSWORD_FILE"
        [ -f "$pw_file" ] && [ -r "$pw_file" ] || die "MANGA_READER_BASIC_AUTH_PASSWORD_FILE not found or unreadable: $pw_file"
        pass=$(head -n 1 "$pw_file" | tr -d '\r')
    fi

    [ -n "$user" ] || die "basic auth enabled but MANGA_READER_BASIC_AUTH_USERNAME is not set"
    case "$user" in
        *:*) die "MANGA_READER_BASIC_AUTH_USERNAME must not contain ':'" ;;
    esac
    [ -n "$pass" ] || die "basic auth enabled but no password (set MANGA_READER_BASIC_AUTH_PASSWORD or MANGA_READER_BASIC_AUTH_PASSWORD_FILE)"
    command -v htpasswd >/dev/null 2>&1 || die "htpasswd is not available in the image (apache2-utils)"

    # Password travels stdin -> htpasswd only; it never appears in argv,
    # in the generated files, or in any message.
    rm -f "$HTPASSWD_PATH"
    umask 022
    if ! printf '%s\n' "$pass" | htpasswd -i -c -m "$HTPASSWD_PATH" "$user" >/dev/null; then
        rm -f "$HTPASSWD_PATH"
        die "failed to generate the password file"
    fi
    chmod 644 "$HTPASSWD_PATH"
    unset pass
    auth_file="$HTPASSWD_PATH"
    echo "generate-auth: basic auth enabled (credentials via environment)" >&2
fi

mkdir -p "$(dirname "$CONF_PATH")"
cat >"$CONF_PATH" <<EOF
# Generated by deploy/generate-auth.sh — do not edit.
auth_basic "$REALM";
auth_basic_user_file "$auth_file";
limit_req zone=auth_limit burst=200 nodelay;
EOF
