// Code generated by ent, DO NOT EDIT.

package syncchange

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the syncchange type in the database.
	Label = "sync_change"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEntity holds the string denoting the entity field in the database.
	FieldEntity = "entity"
	// FieldGalleryID holds the string denoting the gallery_id field in the database.
	FieldGalleryID = "gallery_id"
	// FieldToken holds the string denoting the token field in the database.
	FieldToken = "token"
	// FieldOp holds the string denoting the op field in the database.
	FieldOp = "op"
	// FieldChangedAt holds the string denoting the changed_at field in the database.
	FieldChangedAt = "changed_at"
	// Table holds the table name of the syncchange in the database.
	Table = "sync_change"
)

// Columns holds all SQL columns for syncchange fields.
var Columns = []string{
	FieldID,
	FieldEntity,
	FieldGalleryID,
	FieldToken,
	FieldOp,
	FieldChangedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultOp holds the default value on creation for the "op" field.
	DefaultOp string
	// DefaultChangedAt holds the default value on creation for the "changed_at" field.
	DefaultChangedAt func() time.Time
)

// OrderOption defines the ordering options for the SyncChange queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEntity orders the results by the entity field.
func ByEntity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntity, opts...).ToFunc()
}

// ByGalleryID orders the results by the gallery_id field.
func ByGalleryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGalleryID, opts...).ToFunc()
}

// ByToken orders the results by the token field.
func ByToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToken, opts...).ToFunc()
}

// ByOp orders the results by the op field.
func ByOp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOp, opts...).ToFunc()
}

// ByChangedAt orders the results by the changed_at field.
func ByChangedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChangedAt, opts...).ToFunc()
}
