// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BookshelfColumns holds the columns for the "bookshelf" table.
	BookshelfColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "gallery_id", Type: field.TypeInt64},
		{Name: "token", Type: field.TypeString},
		{Name: "title", Type: field.TypeString, Default: ""},
		{Name: "title_jpn", Type: field.TypeString, Default: ""},
		{Name: "category", Type: field.TypeString, Default: ""},
		{Name: "thumbnail", Type: field.TypeString, Default: ""},
		{Name: "page_count", Type: field.TypeInt, Default: 0},
		{Name: "added_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// BookshelfTable holds the schema information for the "bookshelf" table.
	BookshelfTable = &schema.Table{
		Name:       "bookshelf",
		Columns:    BookshelfColumns,
		PrimaryKey: []*schema.Column{BookshelfColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "bookshelf_gallery_id_token",
				Unique:  true,
				Columns: []*schema.Column{BookshelfColumns[1], BookshelfColumns[2]},
			},
		},
	}
	// PrefillJobColumns holds the columns for the "prefill_job" table.
	PrefillJobColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "gallery_id", Type: field.TypeInt64, Nullable: true},
		{Name: "gallery_token", Type: field.TypeString, Default: ""},
		{Name: "title", Type: field.TypeString, Default: ""},
		{Name: "urls", Type: field.TypeJSON},
		{Name: "status", Type: field.TypeString, Default: "queued"},
		{Name: "total", Type: field.TypeInt, Default: 0},
		{Name: "failed_count", Type: field.TypeInt, Default: 0},
		{Name: "errors", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "finished_at", Type: field.TypeTime, Nullable: true},
	}
	// PrefillJobTable holds the schema information for the "prefill_job" table.
	PrefillJobTable = &schema.Table{
		Name:       "prefill_job",
		Columns:    PrefillJobColumns,
		PrimaryKey: []*schema.Column{PrefillJobColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "prefilljob_status_created_at",
				Unique:  false,
				Columns: []*schema.Column{PrefillJobColumns[5], PrefillJobColumns[9]},
			},
		},
	}
	// ReadingProgressColumns holds the columns for the "reading_progress" table.
	ReadingProgressColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "gallery_id", Type: field.TypeInt64},
		{Name: "token", Type: field.TypeString},
		{Name: "current_page", Type: field.TypeInt, Default: 0},
		{Name: "progress", Type: field.TypeFloat64, Default: 0},
		{Name: "completed", Type: field.TypeBool, Default: false},
		{Name: "title", Type: field.TypeString, Default: ""},
		{Name: "title_jpn", Type: field.TypeString, Default: ""},
		{Name: "category", Type: field.TypeString, Default: ""},
		{Name: "thumbnail", Type: field.TypeString, Default: ""},
		{Name: "page_count", Type: field.TypeInt, Default: 0},
		{Name: "started_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
	}
	// ReadingProgressTable holds the schema information for the "reading_progress" table.
	ReadingProgressTable = &schema.Table{
		Name:       "reading_progress",
		Columns:    ReadingProgressColumns,
		PrimaryKey: []*schema.Column{ReadingProgressColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "readingprogress_gallery_id_token",
				Unique:  true,
				Columns: []*schema.Column{ReadingProgressColumns[1], ReadingProgressColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BookshelfTable,
		PrefillJobTable,
		ReadingProgressTable,
	}
)

func init() {
	BookshelfTable.Annotation = &entsql.Annotation{
		Table: "bookshelf",
	}
	PrefillJobTable.Annotation = &entsql.Annotation{
		Table: "prefill_job",
	}
	ReadingProgressTable.Annotation = &entsql.Annotation{
		Table: "reading_progress",
	}
}
