// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"manga-reader/internal/ent/bookshelf"
	"manga-reader/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BookshelfUpdate is the builder for updating Bookshelf entities.
type BookshelfUpdate struct {
	config
	hooks    []Hook
	mutation *BookshelfMutation
}

// Where appends a list predicates to the BookshelfUpdate builder.
func (_u *BookshelfUpdate) Where(ps ...predicate.Bookshelf) *BookshelfUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGalleryID sets the "gallery_id" field.
func (_u *BookshelfUpdate) SetGalleryID(v int64) *BookshelfUpdate {
	_u.mutation.ResetGalleryID()
	_u.mutation.SetGalleryID(v)
	return _u
}

// SetNillableGalleryID sets the "gallery_id" field if the given value is not nil.
func (_u *BookshelfUpdate) SetNillableGalleryID(v *int64) *BookshelfUpdate {
	if v != nil {
		_u.SetGalleryID(*v)
	}
	return _u
}

// AddGalleryID adds value to the "gallery_id" field.
func (_u *BookshelfUpdate) AddGalleryID(v int64) *BookshelfUpdate {
	_u.mutation.AddGalleryID(v)
	return _u
}

// SetToken sets the "token" field.
func (_u *BookshelfUpdate) SetToken(v string) *BookshelfUpdate {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *BookshelfUpdate) SetNillableToken(v *string) *BookshelfUpdate {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BookshelfUpdate) SetUpdatedAt(v time.Time) *BookshelfUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the BookshelfMutation object of the builder.
func (_u *BookshelfUpdate) Mutation() *BookshelfMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BookshelfUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BookshelfUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BookshelfUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BookshelfUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BookshelfUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := bookshelf.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *BookshelfUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(bookshelf.Table, bookshelf.Columns, sqlgraph.NewFieldSpec(bookshelf.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GalleryID(); ok {
		_spec.SetField(bookshelf.FieldGalleryID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGalleryID(); ok {
		_spec.AddField(bookshelf.FieldGalleryID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(bookshelf.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(bookshelf.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bookshelf.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BookshelfUpdateOne is the builder for updating a single Bookshelf entity.
type BookshelfUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BookshelfMutation
}

// SetGalleryID sets the "gallery_id" field.
func (_u *BookshelfUpdateOne) SetGalleryID(v int64) *BookshelfUpdateOne {
	_u.mutation.ResetGalleryID()
	_u.mutation.SetGalleryID(v)
	return _u
}

// SetNillableGalleryID sets the "gallery_id" field if the given value is not nil.
func (_u *BookshelfUpdateOne) SetNillableGalleryID(v *int64) *BookshelfUpdateOne {
	if v != nil {
		_u.SetGalleryID(*v)
	}
	return _u
}

// AddGalleryID adds value to the "gallery_id" field.
func (_u *BookshelfUpdateOne) AddGalleryID(v int64) *BookshelfUpdateOne {
	_u.mutation.AddGalleryID(v)
	return _u
}

// SetToken sets the "token" field.
func (_u *BookshelfUpdateOne) SetToken(v string) *BookshelfUpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *BookshelfUpdateOne) SetNillableToken(v *string) *BookshelfUpdateOne {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BookshelfUpdateOne) SetUpdatedAt(v time.Time) *BookshelfUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the BookshelfMutation object of the builder.
func (_u *BookshelfUpdateOne) Mutation() *BookshelfMutation {
	return _u.mutation
}

// Where appends a list predicates to the BookshelfUpdate builder.
func (_u *BookshelfUpdateOne) Where(ps ...predicate.Bookshelf) *BookshelfUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BookshelfUpdateOne) Select(field string, fields ...string) *BookshelfUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Bookshelf entity.
func (_u *BookshelfUpdateOne) Save(ctx context.Context) (*Bookshelf, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BookshelfUpdateOne) SaveX(ctx context.Context) *Bookshelf {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BookshelfUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BookshelfUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BookshelfUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := bookshelf.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *BookshelfUpdateOne) sqlSave(ctx context.Context) (_node *Bookshelf, err error) {
	_spec := sqlgraph.NewUpdateSpec(bookshelf.Table, bookshelf.Columns, sqlgraph.NewFieldSpec(bookshelf.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Bookshelf.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bookshelf.FieldID)
		for _, f := range fields {
			if !bookshelf.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != bookshelf.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GalleryID(); ok {
		_spec.SetField(bookshelf.FieldGalleryID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGalleryID(); ok {
		_spec.AddField(bookshelf.FieldGalleryID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(bookshelf.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(bookshelf.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Bookshelf{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bookshelf.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
