// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"manga-reader/internal/ent/migrate"

	"manga-reader/internal/ent/prefilljob"
	"manga-reader/internal/ent/setting"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Bookshelf is the client for interacting with the Bookshelf builders.
	Bookshelf *BookshelfClient
	// GalleryCache is the client for interacting with the GalleryCache builders.
	GalleryCache *GalleryCacheClient
	// PrefillJob is the client for interacting with the PrefillJob builders.
	PrefillJob *PrefillJobClient
	// ReadingProgress is the client for interacting with the ReadingProgress builders.
	ReadingProgress *ReadingProgressClient
	// Setting is the client for interacting with the Setting builders.
	Setting *SettingClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Bookshelf = NewBookshelfClient(c.config)
	c.GalleryCache = NewGalleryCacheClient(c.config)
	c.PrefillJob = NewPrefillJobClient(c.config)
	c.ReadingProgress = NewReadingProgressClient(c.config)
	c.Setting = NewSettingClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		Bookshelf:       NewBookshelfClient(cfg),
		GalleryCache:    NewGalleryCacheClient(cfg),
		PrefillJob:      NewPrefillJobClient(cfg),
		ReadingProgress: NewReadingProgressClient(cfg),
		Setting:         NewSettingClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		Bookshelf:       NewBookshelfClient(cfg),
		GalleryCache:    NewGalleryCacheClient(cfg),
		PrefillJob:      NewPrefillJobClient(cfg),
		ReadingProgress: NewReadingProgressClient(cfg),
		Setting:         NewSettingClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Bookshelf.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Bookshelf.Use(hooks...)
	c.GalleryCache.Use(hooks...)
	c.PrefillJob.Use(hooks...)
	c.ReadingProgress.Use(hooks...)
	c.Setting.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Bookshelf.Intercept(interceptors...)
	c.GalleryCache.Intercept(interceptors...)
	c.PrefillJob.Intercept(interceptors...)
	c.ReadingProgress.Intercept(interceptors...)
	c.Setting.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *BookshelfMutation:
		return c.Bookshelf.mutate(ctx, m)
	case *GalleryCacheMutation:
		return c.GalleryCache.mutate(ctx, m)
	case *PrefillJobMutation:
		return c.PrefillJob.mutate(ctx, m)
	case *ReadingProgressMutation:
		return c.ReadingProgress.mutate(ctx, m)
	case *SettingMutation:
		return c.Setting.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// BookshelfClient is a client for the Bookshelf schema.
type BookshelfClient struct {
	config
}

// NewBookshelfClient returns a client for the Bookshelf from the given config.
func NewBookshelfClient(c config) *BookshelfClient {
	return &BookshelfClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `bookshelf.Hooks(f(g(h())))`.
func (c *BookshelfClient) Use(hooks ...Hook) {
	c.hooks.Bookshelf = append(c.hooks.Bookshelf, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `bookshelf.Intercept(f(g(h())))`.
func (c *BookshelfClient) Intercept(interceptors ...Interceptor) {
	c.inters.Bookshelf = append(c.inters.Bookshelf, interceptors...)
}

// Create returns a builder for creating a Bookshelf entity.
func (c *BookshelfClient) Create() *BookshelfCreate {
	mutation := newBookshelfMutation(c.config, OpCreate)
	return &BookshelfCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Bookshelf entities.
func (c *BookshelfClient) CreateBulk(builders ...*BookshelfCreate) *BookshelfCreateBulk {
	return &BookshelfCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BookshelfClient) MapCreateBulk(slice any, setFunc func(*BookshelfCreate, int)) *BookshelfCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BookshelfCreateBulk{err: fmt.Errorf("calling to BookshelfClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BookshelfCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BookshelfCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Bookshelf.
func (c *BookshelfClient) Update() *BookshelfUpdate {
	mutation := newBookshelfMutation(c.config, OpUpdate)
	return &BookshelfUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BookshelfClient) UpdateOne(_m *Bookshelf) *BookshelfUpdateOne {
	mutation := newBookshelfMutation(c.config, OpUpdateOne)
	mutation.gallery_id = &_m.GalleryID
	mutation.token = &_m.Token
	return &BookshelfUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Bookshelf.
func (c *BookshelfClient) Delete() *BookshelfDelete {
	mutation := newBookshelfMutation(c.config, OpDelete)
	return &BookshelfDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Query returns a query builder for Bookshelf.
func (c *BookshelfClient) Query() *BookshelfQuery {
	return &BookshelfQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBookshelf},
		inters: c.Interceptors(),
	}
}

// Hooks returns the client hooks.
func (c *BookshelfClient) Hooks() []Hook {
	return c.hooks.Bookshelf
}

// Interceptors returns the client interceptors.
func (c *BookshelfClient) Interceptors() []Interceptor {
	return c.inters.Bookshelf
}

func (c *BookshelfClient) mutate(ctx context.Context, m *BookshelfMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BookshelfCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BookshelfUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BookshelfUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BookshelfDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Bookshelf mutation op: %q", m.Op())
	}
}

// GalleryCacheClient is a client for the GalleryCache schema.
type GalleryCacheClient struct {
	config
}

// NewGalleryCacheClient returns a client for the GalleryCache from the given config.
func NewGalleryCacheClient(c config) *GalleryCacheClient {
	return &GalleryCacheClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `gallerycache.Hooks(f(g(h())))`.
func (c *GalleryCacheClient) Use(hooks ...Hook) {
	c.hooks.GalleryCache = append(c.hooks.GalleryCache, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `gallerycache.Intercept(f(g(h())))`.
func (c *GalleryCacheClient) Intercept(interceptors ...Interceptor) {
	c.inters.GalleryCache = append(c.inters.GalleryCache, interceptors...)
}

// Create returns a builder for creating a GalleryCache entity.
func (c *GalleryCacheClient) Create() *GalleryCacheCreate {
	mutation := newGalleryCacheMutation(c.config, OpCreate)
	return &GalleryCacheCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of GalleryCache entities.
func (c *GalleryCacheClient) CreateBulk(builders ...*GalleryCacheCreate) *GalleryCacheCreateBulk {
	return &GalleryCacheCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *GalleryCacheClient) MapCreateBulk(slice any, setFunc func(*GalleryCacheCreate, int)) *GalleryCacheCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &GalleryCacheCreateBulk{err: fmt.Errorf("calling to GalleryCacheClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*GalleryCacheCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &GalleryCacheCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for GalleryCache.
func (c *GalleryCacheClient) Update() *GalleryCacheUpdate {
	mutation := newGalleryCacheMutation(c.config, OpUpdate)
	return &GalleryCacheUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *GalleryCacheClient) UpdateOne(_m *GalleryCache) *GalleryCacheUpdateOne {
	mutation := newGalleryCacheMutation(c.config, OpUpdateOne)
	mutation.gallery_id = &_m.GalleryID
	mutation.token = &_m.Token
	return &GalleryCacheUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for GalleryCache.
func (c *GalleryCacheClient) Delete() *GalleryCacheDelete {
	mutation := newGalleryCacheMutation(c.config, OpDelete)
	return &GalleryCacheDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Query returns a query builder for GalleryCache.
func (c *GalleryCacheClient) Query() *GalleryCacheQuery {
	return &GalleryCacheQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeGalleryCache},
		inters: c.Interceptors(),
	}
}

// Hooks returns the client hooks.
func (c *GalleryCacheClient) Hooks() []Hook {
	return c.hooks.GalleryCache
}

// Interceptors returns the client interceptors.
func (c *GalleryCacheClient) Interceptors() []Interceptor {
	return c.inters.GalleryCache
}

func (c *GalleryCacheClient) mutate(ctx context.Context, m *GalleryCacheMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&GalleryCacheCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&GalleryCacheUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&GalleryCacheUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&GalleryCacheDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown GalleryCache mutation op: %q", m.Op())
	}
}

// PrefillJobClient is a client for the PrefillJob schema.
type PrefillJobClient struct {
	config
}

// NewPrefillJobClient returns a client for the PrefillJob from the given config.
func NewPrefillJobClient(c config) *PrefillJobClient {
	return &PrefillJobClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `prefilljob.Hooks(f(g(h())))`.
func (c *PrefillJobClient) Use(hooks ...Hook) {
	c.hooks.PrefillJob = append(c.hooks.PrefillJob, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `prefilljob.Intercept(f(g(h())))`.
func (c *PrefillJobClient) Intercept(interceptors ...Interceptor) {
	c.inters.PrefillJob = append(c.inters.PrefillJob, interceptors...)
}

// Create returns a builder for creating a PrefillJob entity.
func (c *PrefillJobClient) Create() *PrefillJobCreate {
	mutation := newPrefillJobMutation(c.config, OpCreate)
	return &PrefillJobCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PrefillJob entities.
func (c *PrefillJobClient) CreateBulk(builders ...*PrefillJobCreate) *PrefillJobCreateBulk {
	return &PrefillJobCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PrefillJobClient) MapCreateBulk(slice any, setFunc func(*PrefillJobCreate, int)) *PrefillJobCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PrefillJobCreateBulk{err: fmt.Errorf("calling to PrefillJobClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PrefillJobCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PrefillJobCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PrefillJob.
func (c *PrefillJobClient) Update() *PrefillJobUpdate {
	mutation := newPrefillJobMutation(c.config, OpUpdate)
	return &PrefillJobUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PrefillJobClient) UpdateOne(_m *PrefillJob) *PrefillJobUpdateOne {
	mutation := newPrefillJobMutation(c.config, OpUpdateOne, withPrefillJob(_m))
	return &PrefillJobUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PrefillJobClient) UpdateOneID(id uuid.UUID) *PrefillJobUpdateOne {
	mutation := newPrefillJobMutation(c.config, OpUpdateOne, withPrefillJobID(id))
	return &PrefillJobUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PrefillJob.
func (c *PrefillJobClient) Delete() *PrefillJobDelete {
	mutation := newPrefillJobMutation(c.config, OpDelete)
	return &PrefillJobDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PrefillJobClient) DeleteOne(_m *PrefillJob) *PrefillJobDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PrefillJobClient) DeleteOneID(id uuid.UUID) *PrefillJobDeleteOne {
	builder := c.Delete().Where(prefilljob.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PrefillJobDeleteOne{builder}
}

// Query returns a query builder for PrefillJob.
func (c *PrefillJobClient) Query() *PrefillJobQuery {
	return &PrefillJobQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePrefillJob},
		inters: c.Interceptors(),
	}
}

// Get returns a PrefillJob entity by its id.
func (c *PrefillJobClient) Get(ctx context.Context, id uuid.UUID) (*PrefillJob, error) {
	return c.Query().Where(prefilljob.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PrefillJobClient) GetX(ctx context.Context, id uuid.UUID) *PrefillJob {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *PrefillJobClient) Hooks() []Hook {
	return c.hooks.PrefillJob
}

// Interceptors returns the client interceptors.
func (c *PrefillJobClient) Interceptors() []Interceptor {
	return c.inters.PrefillJob
}

func (c *PrefillJobClient) mutate(ctx context.Context, m *PrefillJobMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PrefillJobCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PrefillJobUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PrefillJobUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PrefillJobDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PrefillJob mutation op: %q", m.Op())
	}
}

// ReadingProgressClient is a client for the ReadingProgress schema.
type ReadingProgressClient struct {
	config
}

// NewReadingProgressClient returns a client for the ReadingProgress from the given config.
func NewReadingProgressClient(c config) *ReadingProgressClient {
	return &ReadingProgressClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `readingprogress.Hooks(f(g(h())))`.
func (c *ReadingProgressClient) Use(hooks ...Hook) {
	c.hooks.ReadingProgress = append(c.hooks.ReadingProgress, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `readingprogress.Intercept(f(g(h())))`.
func (c *ReadingProgressClient) Intercept(interceptors ...Interceptor) {
	c.inters.ReadingProgress = append(c.inters.ReadingProgress, interceptors...)
}

// Create returns a builder for creating a ReadingProgress entity.
func (c *ReadingProgressClient) Create() *ReadingProgressCreate {
	mutation := newReadingProgressMutation(c.config, OpCreate)
	return &ReadingProgressCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ReadingProgress entities.
func (c *ReadingProgressClient) CreateBulk(builders ...*ReadingProgressCreate) *ReadingProgressCreateBulk {
	return &ReadingProgressCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ReadingProgressClient) MapCreateBulk(slice any, setFunc func(*ReadingProgressCreate, int)) *ReadingProgressCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ReadingProgressCreateBulk{err: fmt.Errorf("calling to ReadingProgressClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ReadingProgressCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ReadingProgressCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ReadingProgress.
func (c *ReadingProgressClient) Update() *ReadingProgressUpdate {
	mutation := newReadingProgressMutation(c.config, OpUpdate)
	return &ReadingProgressUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ReadingProgressClient) UpdateOne(_m *ReadingProgress) *ReadingProgressUpdateOne {
	mutation := newReadingProgressMutation(c.config, OpUpdateOne)
	mutation.gallery_id = &_m.GalleryID
	mutation.token = &_m.Token
	return &ReadingProgressUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ReadingProgress.
func (c *ReadingProgressClient) Delete() *ReadingProgressDelete {
	mutation := newReadingProgressMutation(c.config, OpDelete)
	return &ReadingProgressDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Query returns a query builder for ReadingProgress.
func (c *ReadingProgressClient) Query() *ReadingProgressQuery {
	return &ReadingProgressQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeReadingProgress},
		inters: c.Interceptors(),
	}
}

// Hooks returns the client hooks.
func (c *ReadingProgressClient) Hooks() []Hook {
	return c.hooks.ReadingProgress
}

// Interceptors returns the client interceptors.
func (c *ReadingProgressClient) Interceptors() []Interceptor {
	return c.inters.ReadingProgress
}

func (c *ReadingProgressClient) mutate(ctx context.Context, m *ReadingProgressMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ReadingProgressCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ReadingProgressUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ReadingProgressUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ReadingProgressDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ReadingProgress mutation op: %q", m.Op())
	}
}

// SettingClient is a client for the Setting schema.
type SettingClient struct {
	config
}

// NewSettingClient returns a client for the Setting from the given config.
func NewSettingClient(c config) *SettingClient {
	return &SettingClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `setting.Hooks(f(g(h())))`.
func (c *SettingClient) Use(hooks ...Hook) {
	c.hooks.Setting = append(c.hooks.Setting, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `setting.Intercept(f(g(h())))`.
func (c *SettingClient) Intercept(interceptors ...Interceptor) {
	c.inters.Setting = append(c.inters.Setting, interceptors...)
}

// Create returns a builder for creating a Setting entity.
func (c *SettingClient) Create() *SettingCreate {
	mutation := newSettingMutation(c.config, OpCreate)
	return &SettingCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Setting entities.
func (c *SettingClient) CreateBulk(builders ...*SettingCreate) *SettingCreateBulk {
	return &SettingCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SettingClient) MapCreateBulk(slice any, setFunc func(*SettingCreate, int)) *SettingCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SettingCreateBulk{err: fmt.Errorf("calling to SettingClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SettingCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SettingCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Setting.
func (c *SettingClient) Update() *SettingUpdate {
	mutation := newSettingMutation(c.config, OpUpdate)
	return &SettingUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SettingClient) UpdateOne(_m *Setting) *SettingUpdateOne {
	mutation := newSettingMutation(c.config, OpUpdateOne, withSetting(_m))
	return &SettingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SettingClient) UpdateOneID(id int) *SettingUpdateOne {
	mutation := newSettingMutation(c.config, OpUpdateOne, withSettingID(id))
	return &SettingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Setting.
func (c *SettingClient) Delete() *SettingDelete {
	mutation := newSettingMutation(c.config, OpDelete)
	return &SettingDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SettingClient) DeleteOne(_m *Setting) *SettingDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SettingClient) DeleteOneID(id int) *SettingDeleteOne {
	builder := c.Delete().Where(setting.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SettingDeleteOne{builder}
}

// Query returns a query builder for Setting.
func (c *SettingClient) Query() *SettingQuery {
	return &SettingQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSetting},
		inters: c.Interceptors(),
	}
}

// Get returns a Setting entity by its id.
func (c *SettingClient) Get(ctx context.Context, id int) (*Setting, error) {
	return c.Query().Where(setting.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SettingClient) GetX(ctx context.Context, id int) *Setting {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SettingClient) Hooks() []Hook {
	return c.hooks.Setting
}

// Interceptors returns the client interceptors.
func (c *SettingClient) Interceptors() []Interceptor {
	return c.inters.Setting
}

func (c *SettingClient) mutate(ctx context.Context, m *SettingMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SettingCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SettingUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SettingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SettingDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Setting mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Bookshelf, GalleryCache, PrefillJob, ReadingProgress, Setting []ent.Hook
	}
	inters struct {
		Bookshelf, GalleryCache, PrefillJob, ReadingProgress, Setting []ent.Interceptor
	}
)
