// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"manga-reader/internal/ent/gallerycache"
	"manga-reader/internal/ent/predicate"
	"manga-reader/internal/model"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// GalleryCacheUpdate is the builder for updating GalleryCache entities.
type GalleryCacheUpdate struct {
	config
	hooks    []Hook
	mutation *GalleryCacheMutation
}

// Where appends a list predicates to the GalleryCacheUpdate builder.
func (_u *GalleryCacheUpdate) Where(ps ...predicate.GalleryCache) *GalleryCacheUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGalleryID sets the "gallery_id" field.
func (_u *GalleryCacheUpdate) SetGalleryID(v int64) *GalleryCacheUpdate {
	_u.mutation.ResetGalleryID()
	_u.mutation.SetGalleryID(v)
	return _u
}

// SetNillableGalleryID sets the "gallery_id" field if the given value is not nil.
func (_u *GalleryCacheUpdate) SetNillableGalleryID(v *int64) *GalleryCacheUpdate {
	if v != nil {
		_u.SetGalleryID(*v)
	}
	return _u
}

// AddGalleryID adds value to the "gallery_id" field.
func (_u *GalleryCacheUpdate) AddGalleryID(v int64) *GalleryCacheUpdate {
	_u.mutation.AddGalleryID(v)
	return _u
}

// SetToken sets the "token" field.
func (_u *GalleryCacheUpdate) SetToken(v string) *GalleryCacheUpdate {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *GalleryCacheUpdate) SetNillableToken(v *string) *GalleryCacheUpdate {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *GalleryCacheUpdate) SetTitle(v string) *GalleryCacheUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *GalleryCacheUpdate) SetNillableTitle(v *string) *GalleryCacheUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetTitleJpn sets the "title_jpn" field.
func (_u *GalleryCacheUpdate) SetTitleJpn(v string) *GalleryCacheUpdate {
	_u.mutation.SetTitleJpn(v)
	return _u
}

// SetNillableTitleJpn sets the "title_jpn" field if the given value is not nil.
func (_u *GalleryCacheUpdate) SetNillableTitleJpn(v *string) *GalleryCacheUpdate {
	if v != nil {
		_u.SetTitleJpn(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *GalleryCacheUpdate) SetCategory(v string) *GalleryCacheUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *GalleryCacheUpdate) SetNillableCategory(v *string) *GalleryCacheUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetThumbnail sets the "thumbnail" field.
func (_u *GalleryCacheUpdate) SetThumbnail(v string) *GalleryCacheUpdate {
	_u.mutation.SetThumbnail(v)
	return _u
}

// SetNillableThumbnail sets the "thumbnail" field if the given value is not nil.
func (_u *GalleryCacheUpdate) SetNillableThumbnail(v *string) *GalleryCacheUpdate {
	if v != nil {
		_u.SetThumbnail(*v)
	}
	return _u
}

// SetPageCount sets the "page_count" field.
func (_u *GalleryCacheUpdate) SetPageCount(v int) *GalleryCacheUpdate {
	_u.mutation.ResetPageCount()
	_u.mutation.SetPageCount(v)
	return _u
}

// SetNillablePageCount sets the "page_count" field if the given value is not nil.
func (_u *GalleryCacheUpdate) SetNillablePageCount(v *int) *GalleryCacheUpdate {
	if v != nil {
		_u.SetPageCount(*v)
	}
	return _u
}

// AddPageCount adds value to the "page_count" field.
func (_u *GalleryCacheUpdate) AddPageCount(v int) *GalleryCacheUpdate {
	_u.mutation.AddPageCount(v)
	return _u
}

// SetRating sets the "rating" field.
func (_u *GalleryCacheUpdate) SetRating(v float64) *GalleryCacheUpdate {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *GalleryCacheUpdate) SetNillableRating(v *float64) *GalleryCacheUpdate {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *GalleryCacheUpdate) AddRating(v float64) *GalleryCacheUpdate {
	_u.mutation.AddRating(v)
	return _u
}

// SetRatingCount sets the "rating_count" field.
func (_u *GalleryCacheUpdate) SetRatingCount(v int) *GalleryCacheUpdate {
	_u.mutation.ResetRatingCount()
	_u.mutation.SetRatingCount(v)
	return _u
}

// SetNillableRatingCount sets the "rating_count" field if the given value is not nil.
func (_u *GalleryCacheUpdate) SetNillableRatingCount(v *int) *GalleryCacheUpdate {
	if v != nil {
		_u.SetRatingCount(*v)
	}
	return _u
}

// AddRatingCount adds value to the "rating_count" field.
func (_u *GalleryCacheUpdate) AddRatingCount(v int) *GalleryCacheUpdate {
	_u.mutation.AddRatingCount(v)
	return _u
}

// SetUploader sets the "uploader" field.
func (_u *GalleryCacheUpdate) SetUploader(v string) *GalleryCacheUpdate {
	_u.mutation.SetUploader(v)
	return _u
}

// SetNillableUploader sets the "uploader" field if the given value is not nil.
func (_u *GalleryCacheUpdate) SetNillableUploader(v *string) *GalleryCacheUpdate {
	if v != nil {
		_u.SetUploader(*v)
	}
	return _u
}

// SetPosted sets the "posted" field.
func (_u *GalleryCacheUpdate) SetPosted(v string) *GalleryCacheUpdate {
	_u.mutation.SetPosted(v)
	return _u
}

// SetNillablePosted sets the "posted" field if the given value is not nil.
func (_u *GalleryCacheUpdate) SetNillablePosted(v *string) *GalleryCacheUpdate {
	if v != nil {
		_u.SetPosted(*v)
	}
	return _u
}

// SetPostedAt sets the "posted_at" field.
func (_u *GalleryCacheUpdate) SetPostedAt(v time.Time) *GalleryCacheUpdate {
	_u.mutation.SetPostedAt(v)
	return _u
}

// SetNillablePostedAt sets the "posted_at" field if the given value is not nil.
func (_u *GalleryCacheUpdate) SetNillablePostedAt(v *time.Time) *GalleryCacheUpdate {
	if v != nil {
		_u.SetPostedAt(*v)
	}
	return _u
}

// ClearPostedAt clears the value of the "posted_at" field.
func (_u *GalleryCacheUpdate) ClearPostedAt() *GalleryCacheUpdate {
	_u.mutation.ClearPostedAt()
	return _u
}

// SetLanguage sets the "language" field.
func (_u *GalleryCacheUpdate) SetLanguage(v string) *GalleryCacheUpdate {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *GalleryCacheUpdate) SetNillableLanguage(v *string) *GalleryCacheUpdate {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetTranslated sets the "translated" field.
func (_u *GalleryCacheUpdate) SetTranslated(v bool) *GalleryCacheUpdate {
	_u.mutation.SetTranslated(v)
	return _u
}

// SetNillableTranslated sets the "translated" field if the given value is not nil.
func (_u *GalleryCacheUpdate) SetNillableTranslated(v *bool) *GalleryCacheUpdate {
	if v != nil {
		_u.SetTranslated(*v)
	}
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *GalleryCacheUpdate) SetFileSize(v string) *GalleryCacheUpdate {
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *GalleryCacheUpdate) SetNillableFileSize(v *string) *GalleryCacheUpdate {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// SetFavorited sets the "favorited" field.
func (_u *GalleryCacheUpdate) SetFavorited(v int) *GalleryCacheUpdate {
	_u.mutation.ResetFavorited()
	_u.mutation.SetFavorited(v)
	return _u
}

// SetNillableFavorited sets the "favorited" field if the given value is not nil.
func (_u *GalleryCacheUpdate) SetNillableFavorited(v *int) *GalleryCacheUpdate {
	if v != nil {
		_u.SetFavorited(*v)
	}
	return _u
}

// AddFavorited adds value to the "favorited" field.
func (_u *GalleryCacheUpdate) AddFavorited(v int) *GalleryCacheUpdate {
	_u.mutation.AddFavorited(v)
	return _u
}

// SetExpunged sets the "expunged" field.
func (_u *GalleryCacheUpdate) SetExpunged(v bool) *GalleryCacheUpdate {
	_u.mutation.SetExpunged(v)
	return _u
}

// SetNillableExpunged sets the "expunged" field if the given value is not nil.
func (_u *GalleryCacheUpdate) SetNillableExpunged(v *bool) *GalleryCacheUpdate {
	if v != nil {
		_u.SetExpunged(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *GalleryCacheUpdate) SetTags(v []model.Tag) *GalleryCacheUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *GalleryCacheUpdate) AppendTags(v []model.Tag) *GalleryCacheUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *GalleryCacheUpdate) ClearTags() *GalleryCacheUpdate {
	_u.mutation.ClearTags()
	return _u
}

// SetPageUrls sets the "page_urls" field.
func (_u *GalleryCacheUpdate) SetPageUrls(v []string) *GalleryCacheUpdate {
	_u.mutation.SetPageUrls(v)
	return _u
}

// AppendPageUrls appends value to the "page_urls" field.
func (_u *GalleryCacheUpdate) AppendPageUrls(v []string) *GalleryCacheUpdate {
	_u.mutation.AppendPageUrls(v)
	return _u
}

// ClearPageUrls clears the value of the "page_urls" field.
func (_u *GalleryCacheUpdate) ClearPageUrls() *GalleryCacheUpdate {
	_u.mutation.ClearPageUrls()
	return _u
}

// SetThumbnails sets the "thumbnails" field.
func (_u *GalleryCacheUpdate) SetThumbnails(v []model.GalleryPageThumb) *GalleryCacheUpdate {
	_u.mutation.SetThumbnails(v)
	return _u
}

// AppendThumbnails appends value to the "thumbnails" field.
func (_u *GalleryCacheUpdate) AppendThumbnails(v []model.GalleryPageThumb) *GalleryCacheUpdate {
	_u.mutation.AppendThumbnails(v)
	return _u
}

// ClearThumbnails clears the value of the "thumbnails" field.
func (_u *GalleryCacheUpdate) ClearThumbnails() *GalleryCacheUpdate {
	_u.mutation.ClearThumbnails()
	return _u
}

// SetMetaFetchedAt sets the "meta_fetched_at" field.
func (_u *GalleryCacheUpdate) SetMetaFetchedAt(v time.Time) *GalleryCacheUpdate {
	_u.mutation.SetMetaFetchedAt(v)
	return _u
}

// SetNillableMetaFetchedAt sets the "meta_fetched_at" field if the given value is not nil.
func (_u *GalleryCacheUpdate) SetNillableMetaFetchedAt(v *time.Time) *GalleryCacheUpdate {
	if v != nil {
		_u.SetMetaFetchedAt(*v)
	}
	return _u
}

// ClearMetaFetchedAt clears the value of the "meta_fetched_at" field.
func (_u *GalleryCacheUpdate) ClearMetaFetchedAt() *GalleryCacheUpdate {
	_u.mutation.ClearMetaFetchedAt()
	return _u
}

// SetDetailsFetchedAt sets the "details_fetched_at" field.
func (_u *GalleryCacheUpdate) SetDetailsFetchedAt(v time.Time) *GalleryCacheUpdate {
	_u.mutation.SetDetailsFetchedAt(v)
	return _u
}

// SetNillableDetailsFetchedAt sets the "details_fetched_at" field if the given value is not nil.
func (_u *GalleryCacheUpdate) SetNillableDetailsFetchedAt(v *time.Time) *GalleryCacheUpdate {
	if v != nil {
		_u.SetDetailsFetchedAt(*v)
	}
	return _u
}

// ClearDetailsFetchedAt clears the value of the "details_fetched_at" field.
func (_u *GalleryCacheUpdate) ClearDetailsFetchedAt() *GalleryCacheUpdate {
	_u.mutation.ClearDetailsFetchedAt()
	return _u
}

// SetPagesFetchedAt sets the "pages_fetched_at" field.
func (_u *GalleryCacheUpdate) SetPagesFetchedAt(v time.Time) *GalleryCacheUpdate {
	_u.mutation.SetPagesFetchedAt(v)
	return _u
}

// SetNillablePagesFetchedAt sets the "pages_fetched_at" field if the given value is not nil.
func (_u *GalleryCacheUpdate) SetNillablePagesFetchedAt(v *time.Time) *GalleryCacheUpdate {
	if v != nil {
		_u.SetPagesFetchedAt(*v)
	}
	return _u
}

// ClearPagesFetchedAt clears the value of the "pages_fetched_at" field.
func (_u *GalleryCacheUpdate) ClearPagesFetchedAt() *GalleryCacheUpdate {
	_u.mutation.ClearPagesFetchedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GalleryCacheUpdate) SetUpdatedAt(v time.Time) *GalleryCacheUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the GalleryCacheMutation object of the builder.
func (_u *GalleryCacheUpdate) Mutation() *GalleryCacheMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GalleryCacheUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GalleryCacheUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GalleryCacheUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GalleryCacheUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GalleryCacheUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := gallerycache.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *GalleryCacheUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(gallerycache.Table, gallerycache.Columns, sqlgraph.NewFieldSpec(gallerycache.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GalleryID(); ok {
		_spec.SetField(gallerycache.FieldGalleryID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGalleryID(); ok {
		_spec.AddField(gallerycache.FieldGalleryID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(gallerycache.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(gallerycache.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.TitleJpn(); ok {
		_spec.SetField(gallerycache.FieldTitleJpn, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(gallerycache.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Thumbnail(); ok {
		_spec.SetField(gallerycache.FieldThumbnail, field.TypeString, value)
	}
	if value, ok := _u.mutation.PageCount(); ok {
		_spec.SetField(gallerycache.FieldPageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPageCount(); ok {
		_spec.AddField(gallerycache.FieldPageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(gallerycache.FieldRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(gallerycache.FieldRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RatingCount(); ok {
		_spec.SetField(gallerycache.FieldRatingCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRatingCount(); ok {
		_spec.AddField(gallerycache.FieldRatingCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Uploader(); ok {
		_spec.SetField(gallerycache.FieldUploader, field.TypeString, value)
	}
	if value, ok := _u.mutation.Posted(); ok {
		_spec.SetField(gallerycache.FieldPosted, field.TypeString, value)
	}
	if value, ok := _u.mutation.PostedAt(); ok {
		_spec.SetField(gallerycache.FieldPostedAt, field.TypeTime, value)
	}
	if _u.mutation.PostedAtCleared() {
		_spec.ClearField(gallerycache.FieldPostedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(gallerycache.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Translated(); ok {
		_spec.SetField(gallerycache.FieldTranslated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(gallerycache.FieldFileSize, field.TypeString, value)
	}
	if value, ok := _u.mutation.Favorited(); ok {
		_spec.SetField(gallerycache.FieldFavorited, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFavorited(); ok {
		_spec.AddField(gallerycache.FieldFavorited, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Expunged(); ok {
		_spec.SetField(gallerycache.FieldExpunged, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(gallerycache.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, gallerycache.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(gallerycache.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.PageUrls(); ok {
		_spec.SetField(gallerycache.FieldPageUrls, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPageUrls(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, gallerycache.FieldPageUrls, value)
		})
	}
	if _u.mutation.PageUrlsCleared() {
		_spec.ClearField(gallerycache.FieldPageUrls, field.TypeJSON)
	}
	if value, ok := _u.mutation.Thumbnails(); ok {
		_spec.SetField(gallerycache.FieldThumbnails, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedThumbnails(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, gallerycache.FieldThumbnails, value)
		})
	}
	if _u.mutation.ThumbnailsCleared() {
		_spec.ClearField(gallerycache.FieldThumbnails, field.TypeJSON)
	}
	if value, ok := _u.mutation.MetaFetchedAt(); ok {
		_spec.SetField(gallerycache.FieldMetaFetchedAt, field.TypeTime, value)
	}
	if _u.mutation.MetaFetchedAtCleared() {
		_spec.ClearField(gallerycache.FieldMetaFetchedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DetailsFetchedAt(); ok {
		_spec.SetField(gallerycache.FieldDetailsFetchedAt, field.TypeTime, value)
	}
	if _u.mutation.DetailsFetchedAtCleared() {
		_spec.ClearField(gallerycache.FieldDetailsFetchedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PagesFetchedAt(); ok {
		_spec.SetField(gallerycache.FieldPagesFetchedAt, field.TypeTime, value)
	}
	if _u.mutation.PagesFetchedAtCleared() {
		_spec.ClearField(gallerycache.FieldPagesFetchedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(gallerycache.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gallerycache.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GalleryCacheUpdateOne is the builder for updating a single GalleryCache entity.
type GalleryCacheUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GalleryCacheMutation
}

// SetGalleryID sets the "gallery_id" field.
func (_u *GalleryCacheUpdateOne) SetGalleryID(v int64) *GalleryCacheUpdateOne {
	_u.mutation.ResetGalleryID()
	_u.mutation.SetGalleryID(v)
	return _u
}

// SetNillableGalleryID sets the "gallery_id" field if the given value is not nil.
func (_u *GalleryCacheUpdateOne) SetNillableGalleryID(v *int64) *GalleryCacheUpdateOne {
	if v != nil {
		_u.SetGalleryID(*v)
	}
	return _u
}

// AddGalleryID adds value to the "gallery_id" field.
func (_u *GalleryCacheUpdateOne) AddGalleryID(v int64) *GalleryCacheUpdateOne {
	_u.mutation.AddGalleryID(v)
	return _u
}

// SetToken sets the "token" field.
func (_u *GalleryCacheUpdateOne) SetToken(v string) *GalleryCacheUpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *GalleryCacheUpdateOne) SetNillableToken(v *string) *GalleryCacheUpdateOne {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *GalleryCacheUpdateOne) SetTitle(v string) *GalleryCacheUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *GalleryCacheUpdateOne) SetNillableTitle(v *string) *GalleryCacheUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetTitleJpn sets the "title_jpn" field.
func (_u *GalleryCacheUpdateOne) SetTitleJpn(v string) *GalleryCacheUpdateOne {
	_u.mutation.SetTitleJpn(v)
	return _u
}

// SetNillableTitleJpn sets the "title_jpn" field if the given value is not nil.
func (_u *GalleryCacheUpdateOne) SetNillableTitleJpn(v *string) *GalleryCacheUpdateOne {
	if v != nil {
		_u.SetTitleJpn(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *GalleryCacheUpdateOne) SetCategory(v string) *GalleryCacheUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *GalleryCacheUpdateOne) SetNillableCategory(v *string) *GalleryCacheUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetThumbnail sets the "thumbnail" field.
func (_u *GalleryCacheUpdateOne) SetThumbnail(v string) *GalleryCacheUpdateOne {
	_u.mutation.SetThumbnail(v)
	return _u
}

// SetNillableThumbnail sets the "thumbnail" field if the given value is not nil.
func (_u *GalleryCacheUpdateOne) SetNillableThumbnail(v *string) *GalleryCacheUpdateOne {
	if v != nil {
		_u.SetThumbnail(*v)
	}
	return _u
}

// SetPageCount sets the "page_count" field.
func (_u *GalleryCacheUpdateOne) SetPageCount(v int) *GalleryCacheUpdateOne {
	_u.mutation.ResetPageCount()
	_u.mutation.SetPageCount(v)
	return _u
}

// SetNillablePageCount sets the "page_count" field if the given value is not nil.
func (_u *GalleryCacheUpdateOne) SetNillablePageCount(v *int) *GalleryCacheUpdateOne {
	if v != nil {
		_u.SetPageCount(*v)
	}
	return _u
}

// AddPageCount adds value to the "page_count" field.
func (_u *GalleryCacheUpdateOne) AddPageCount(v int) *GalleryCacheUpdateOne {
	_u.mutation.AddPageCount(v)
	return _u
}

// SetRating sets the "rating" field.
func (_u *GalleryCacheUpdateOne) SetRating(v float64) *GalleryCacheUpdateOne {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *GalleryCacheUpdateOne) SetNillableRating(v *float64) *GalleryCacheUpdateOne {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *GalleryCacheUpdateOne) AddRating(v float64) *GalleryCacheUpdateOne {
	_u.mutation.AddRating(v)
	return _u
}

// SetRatingCount sets the "rating_count" field.
func (_u *GalleryCacheUpdateOne) SetRatingCount(v int) *GalleryCacheUpdateOne {
	_u.mutation.ResetRatingCount()
	_u.mutation.SetRatingCount(v)
	return _u
}

// SetNillableRatingCount sets the "rating_count" field if the given value is not nil.
func (_u *GalleryCacheUpdateOne) SetNillableRatingCount(v *int) *GalleryCacheUpdateOne {
	if v != nil {
		_u.SetRatingCount(*v)
	}
	return _u
}

// AddRatingCount adds value to the "rating_count" field.
func (_u *GalleryCacheUpdateOne) AddRatingCount(v int) *GalleryCacheUpdateOne {
	_u.mutation.AddRatingCount(v)
	return _u
}

// SetUploader sets the "uploader" field.
func (_u *GalleryCacheUpdateOne) SetUploader(v string) *GalleryCacheUpdateOne {
	_u.mutation.SetUploader(v)
	return _u
}

// SetNillableUploader sets the "uploader" field if the given value is not nil.
func (_u *GalleryCacheUpdateOne) SetNillableUploader(v *string) *GalleryCacheUpdateOne {
	if v != nil {
		_u.SetUploader(*v)
	}
	return _u
}

// SetPosted sets the "posted" field.
func (_u *GalleryCacheUpdateOne) SetPosted(v string) *GalleryCacheUpdateOne {
	_u.mutation.SetPosted(v)
	return _u
}

// SetNillablePosted sets the "posted" field if the given value is not nil.
func (_u *GalleryCacheUpdateOne) SetNillablePosted(v *string) *GalleryCacheUpdateOne {
	if v != nil {
		_u.SetPosted(*v)
	}
	return _u
}

// SetPostedAt sets the "posted_at" field.
func (_u *GalleryCacheUpdateOne) SetPostedAt(v time.Time) *GalleryCacheUpdateOne {
	_u.mutation.SetPostedAt(v)
	return _u
}

// SetNillablePostedAt sets the "posted_at" field if the given value is not nil.
func (_u *GalleryCacheUpdateOne) SetNillablePostedAt(v *time.Time) *GalleryCacheUpdateOne {
	if v != nil {
		_u.SetPostedAt(*v)
	}
	return _u
}

// ClearPostedAt clears the value of the "posted_at" field.
func (_u *GalleryCacheUpdateOne) ClearPostedAt() *GalleryCacheUpdateOne {
	_u.mutation.ClearPostedAt()
	return _u
}

// SetLanguage sets the "language" field.
func (_u *GalleryCacheUpdateOne) SetLanguage(v string) *GalleryCacheUpdateOne {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *GalleryCacheUpdateOne) SetNillableLanguage(v *string) *GalleryCacheUpdateOne {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetTranslated sets the "translated" field.
func (_u *GalleryCacheUpdateOne) SetTranslated(v bool) *GalleryCacheUpdateOne {
	_u.mutation.SetTranslated(v)
	return _u
}

// SetNillableTranslated sets the "translated" field if the given value is not nil.
func (_u *GalleryCacheUpdateOne) SetNillableTranslated(v *bool) *GalleryCacheUpdateOne {
	if v != nil {
		_u.SetTranslated(*v)
	}
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *GalleryCacheUpdateOne) SetFileSize(v string) *GalleryCacheUpdateOne {
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *GalleryCacheUpdateOne) SetNillableFileSize(v *string) *GalleryCacheUpdateOne {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// SetFavorited sets the "favorited" field.
func (_u *GalleryCacheUpdateOne) SetFavorited(v int) *GalleryCacheUpdateOne {
	_u.mutation.ResetFavorited()
	_u.mutation.SetFavorited(v)
	return _u
}

// SetNillableFavorited sets the "favorited" field if the given value is not nil.
func (_u *GalleryCacheUpdateOne) SetNillableFavorited(v *int) *GalleryCacheUpdateOne {
	if v != nil {
		_u.SetFavorited(*v)
	}
	return _u
}

// AddFavorited adds value to the "favorited" field.
func (_u *GalleryCacheUpdateOne) AddFavorited(v int) *GalleryCacheUpdateOne {
	_u.mutation.AddFavorited(v)
	return _u
}

// SetExpunged sets the "expunged" field.
func (_u *GalleryCacheUpdateOne) SetExpunged(v bool) *GalleryCacheUpdateOne {
	_u.mutation.SetExpunged(v)
	return _u
}

// SetNillableExpunged sets the "expunged" field if the given value is not nil.
func (_u *GalleryCacheUpdateOne) SetNillableExpunged(v *bool) *GalleryCacheUpdateOne {
	if v != nil {
		_u.SetExpunged(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *GalleryCacheUpdateOne) SetTags(v []model.Tag) *GalleryCacheUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *GalleryCacheUpdateOne) AppendTags(v []model.Tag) *GalleryCacheUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *GalleryCacheUpdateOne) ClearTags() *GalleryCacheUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// SetPageUrls sets the "page_urls" field.
func (_u *GalleryCacheUpdateOne) SetPageUrls(v []string) *GalleryCacheUpdateOne {
	_u.mutation.SetPageUrls(v)
	return _u
}

// AppendPageUrls appends value to the "page_urls" field.
func (_u *GalleryCacheUpdateOne) AppendPageUrls(v []string) *GalleryCacheUpdateOne {
	_u.mutation.AppendPageUrls(v)
	return _u
}

// ClearPageUrls clears the value of the "page_urls" field.
func (_u *GalleryCacheUpdateOne) ClearPageUrls() *GalleryCacheUpdateOne {
	_u.mutation.ClearPageUrls()
	return _u
}

// SetThumbnails sets the "thumbnails" field.
func (_u *GalleryCacheUpdateOne) SetThumbnails(v []model.GalleryPageThumb) *GalleryCacheUpdateOne {
	_u.mutation.SetThumbnails(v)
	return _u
}

// AppendThumbnails appends value to the "thumbnails" field.
func (_u *GalleryCacheUpdateOne) AppendThumbnails(v []model.GalleryPageThumb) *GalleryCacheUpdateOne {
	_u.mutation.AppendThumbnails(v)
	return _u
}

// ClearThumbnails clears the value of the "thumbnails" field.
func (_u *GalleryCacheUpdateOne) ClearThumbnails() *GalleryCacheUpdateOne {
	_u.mutation.ClearThumbnails()
	return _u
}

// SetMetaFetchedAt sets the "meta_fetched_at" field.
func (_u *GalleryCacheUpdateOne) SetMetaFetchedAt(v time.Time) *GalleryCacheUpdateOne {
	_u.mutation.SetMetaFetchedAt(v)
	return _u
}

// SetNillableMetaFetchedAt sets the "meta_fetched_at" field if the given value is not nil.
func (_u *GalleryCacheUpdateOne) SetNillableMetaFetchedAt(v *time.Time) *GalleryCacheUpdateOne {
	if v != nil {
		_u.SetMetaFetchedAt(*v)
	}
	return _u
}

// ClearMetaFetchedAt clears the value of the "meta_fetched_at" field.
func (_u *GalleryCacheUpdateOne) ClearMetaFetchedAt() *GalleryCacheUpdateOne {
	_u.mutation.ClearMetaFetchedAt()
	return _u
}

// SetDetailsFetchedAt sets the "details_fetched_at" field.
func (_u *GalleryCacheUpdateOne) SetDetailsFetchedAt(v time.Time) *GalleryCacheUpdateOne {
	_u.mutation.SetDetailsFetchedAt(v)
	return _u
}

// SetNillableDetailsFetchedAt sets the "details_fetched_at" field if the given value is not nil.
func (_u *GalleryCacheUpdateOne) SetNillableDetailsFetchedAt(v *time.Time) *GalleryCacheUpdateOne {
	if v != nil {
		_u.SetDetailsFetchedAt(*v)
	}
	return _u
}

// ClearDetailsFetchedAt clears the value of the "details_fetched_at" field.
func (_u *GalleryCacheUpdateOne) ClearDetailsFetchedAt() *GalleryCacheUpdateOne {
	_u.mutation.ClearDetailsFetchedAt()
	return _u
}

// SetPagesFetchedAt sets the "pages_fetched_at" field.
func (_u *GalleryCacheUpdateOne) SetPagesFetchedAt(v time.Time) *GalleryCacheUpdateOne {
	_u.mutation.SetPagesFetchedAt(v)
	return _u
}

// SetNillablePagesFetchedAt sets the "pages_fetched_at" field if the given value is not nil.
func (_u *GalleryCacheUpdateOne) SetNillablePagesFetchedAt(v *time.Time) *GalleryCacheUpdateOne {
	if v != nil {
		_u.SetPagesFetchedAt(*v)
	}
	return _u
}

// ClearPagesFetchedAt clears the value of the "pages_fetched_at" field.
func (_u *GalleryCacheUpdateOne) ClearPagesFetchedAt() *GalleryCacheUpdateOne {
	_u.mutation.ClearPagesFetchedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GalleryCacheUpdateOne) SetUpdatedAt(v time.Time) *GalleryCacheUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the GalleryCacheMutation object of the builder.
func (_u *GalleryCacheUpdateOne) Mutation() *GalleryCacheMutation {
	return _u.mutation
}

// Where appends a list predicates to the GalleryCacheUpdate builder.
func (_u *GalleryCacheUpdateOne) Where(ps ...predicate.GalleryCache) *GalleryCacheUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GalleryCacheUpdateOne) Select(field string, fields ...string) *GalleryCacheUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GalleryCache entity.
func (_u *GalleryCacheUpdateOne) Save(ctx context.Context) (*GalleryCache, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GalleryCacheUpdateOne) SaveX(ctx context.Context) *GalleryCache {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GalleryCacheUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GalleryCacheUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GalleryCacheUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := gallerycache.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *GalleryCacheUpdateOne) sqlSave(ctx context.Context) (_node *GalleryCache, err error) {
	_spec := sqlgraph.NewUpdateSpec(gallerycache.Table, gallerycache.Columns, sqlgraph.NewFieldSpec(gallerycache.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GalleryCache.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, gallerycache.FieldID)
		for _, f := range fields {
			if !gallerycache.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != gallerycache.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GalleryID(); ok {
		_spec.SetField(gallerycache.FieldGalleryID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGalleryID(); ok {
		_spec.AddField(gallerycache.FieldGalleryID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(gallerycache.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(gallerycache.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.TitleJpn(); ok {
		_spec.SetField(gallerycache.FieldTitleJpn, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(gallerycache.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Thumbnail(); ok {
		_spec.SetField(gallerycache.FieldThumbnail, field.TypeString, value)
	}
	if value, ok := _u.mutation.PageCount(); ok {
		_spec.SetField(gallerycache.FieldPageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPageCount(); ok {
		_spec.AddField(gallerycache.FieldPageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(gallerycache.FieldRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(gallerycache.FieldRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RatingCount(); ok {
		_spec.SetField(gallerycache.FieldRatingCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRatingCount(); ok {
		_spec.AddField(gallerycache.FieldRatingCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Uploader(); ok {
		_spec.SetField(gallerycache.FieldUploader, field.TypeString, value)
	}
	if value, ok := _u.mutation.Posted(); ok {
		_spec.SetField(gallerycache.FieldPosted, field.TypeString, value)
	}
	if value, ok := _u.mutation.PostedAt(); ok {
		_spec.SetField(gallerycache.FieldPostedAt, field.TypeTime, value)
	}
	if _u.mutation.PostedAtCleared() {
		_spec.ClearField(gallerycache.FieldPostedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(gallerycache.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Translated(); ok {
		_spec.SetField(gallerycache.FieldTranslated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(gallerycache.FieldFileSize, field.TypeString, value)
	}
	if value, ok := _u.mutation.Favorited(); ok {
		_spec.SetField(gallerycache.FieldFavorited, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFavorited(); ok {
		_spec.AddField(gallerycache.FieldFavorited, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Expunged(); ok {
		_spec.SetField(gallerycache.FieldExpunged, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(gallerycache.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, gallerycache.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(gallerycache.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.PageUrls(); ok {
		_spec.SetField(gallerycache.FieldPageUrls, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPageUrls(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, gallerycache.FieldPageUrls, value)
		})
	}
	if _u.mutation.PageUrlsCleared() {
		_spec.ClearField(gallerycache.FieldPageUrls, field.TypeJSON)
	}
	if value, ok := _u.mutation.Thumbnails(); ok {
		_spec.SetField(gallerycache.FieldThumbnails, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedThumbnails(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, gallerycache.FieldThumbnails, value)
		})
	}
	if _u.mutation.ThumbnailsCleared() {
		_spec.ClearField(gallerycache.FieldThumbnails, field.TypeJSON)
	}
	if value, ok := _u.mutation.MetaFetchedAt(); ok {
		_spec.SetField(gallerycache.FieldMetaFetchedAt, field.TypeTime, value)
	}
	if _u.mutation.MetaFetchedAtCleared() {
		_spec.ClearField(gallerycache.FieldMetaFetchedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DetailsFetchedAt(); ok {
		_spec.SetField(gallerycache.FieldDetailsFetchedAt, field.TypeTime, value)
	}
	if _u.mutation.DetailsFetchedAtCleared() {
		_spec.ClearField(gallerycache.FieldDetailsFetchedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PagesFetchedAt(); ok {
		_spec.SetField(gallerycache.FieldPagesFetchedAt, field.TypeTime, value)
	}
	if _u.mutation.PagesFetchedAtCleared() {
		_spec.ClearField(gallerycache.FieldPagesFetchedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(gallerycache.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &GalleryCache{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gallerycache.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
