// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"manga-reader/internal/ent/gallerycache"
	"manga-reader/internal/model"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// GalleryCache is the model entity for the GalleryCache schema.
type GalleryCache struct {
	config `json:"-"`
	// GalleryID holds the value of the "gallery_id" field.
	GalleryID int64 `json:"gallery_id,omitempty"`
	// Token holds the value of the "token" field.
	Token string `json:"token,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// TitleJpn holds the value of the "title_jpn" field.
	TitleJpn string `json:"title_jpn,omitempty"`
	// Category holds the value of the "category" field.
	Category string `json:"category,omitempty"`
	// Thumbnail holds the value of the "thumbnail" field.
	Thumbnail string `json:"thumbnail,omitempty"`
	// PageCount holds the value of the "page_count" field.
	PageCount int `json:"page_count,omitempty"`
	// Rating holds the value of the "rating" field.
	Rating float64 `json:"rating,omitempty"`
	// RatingCount holds the value of the "rating_count" field.
	RatingCount int `json:"rating_count,omitempty"`
	// Uploader holds the value of the "uploader" field.
	Uploader string `json:"uploader,omitempty"`
	// Posted holds the value of the "posted" field.
	Posted string `json:"posted,omitempty"`
	// PostedAt holds the value of the "posted_at" field.
	PostedAt *time.Time `json:"posted_at,omitempty"`
	// Language holds the value of the "language" field.
	Language string `json:"language,omitempty"`
	// Translated holds the value of the "translated" field.
	Translated bool `json:"translated,omitempty"`
	// FileSize holds the value of the "file_size" field.
	FileSize string `json:"file_size,omitempty"`
	// Favorited holds the value of the "favorited" field.
	Favorited int `json:"favorited,omitempty"`
	// Expunged holds the value of the "expunged" field.
	Expunged bool `json:"expunged,omitempty"`
	// Tags holds the value of the "tags" field.
	Tags []model.Tag `json:"tags,omitempty"`
	// Pages holds the value of the "pages" field.
	Pages []string `json:"pages,omitempty"`
	// Thumbnails holds the value of the "thumbnails" field.
	Thumbnails []model.GalleryPageThumb `json:"thumbnails,omitempty"`
	// MetaFetchedAt holds the value of the "meta_fetched_at" field.
	MetaFetchedAt *time.Time `json:"meta_fetched_at,omitempty"`
	// DetailsFetchedAt holds the value of the "details_fetched_at" field.
	DetailsFetchedAt *time.Time `json:"details_fetched_at,omitempty"`
	// PagesFetchedAt holds the value of the "pages_fetched_at" field.
	PagesFetchedAt *time.Time `json:"pages_fetched_at,omitempty"`
	// ThumbnailFetchedAt holds the value of the "thumbnail_fetched_at" field.
	ThumbnailFetchedAt *time.Time `json:"thumbnail_fetched_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GalleryCache) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case gallerycache.FieldTags, gallerycache.FieldPages, gallerycache.FieldThumbnails:
			values[i] = new([]byte)
		case gallerycache.FieldTranslated, gallerycache.FieldExpunged:
			values[i] = new(sql.NullBool)
		case gallerycache.FieldRating:
			values[i] = new(sql.NullFloat64)
		case gallerycache.FieldGalleryID, gallerycache.FieldPageCount, gallerycache.FieldRatingCount, gallerycache.FieldFavorited:
			values[i] = new(sql.NullInt64)
		case gallerycache.FieldToken, gallerycache.FieldTitle, gallerycache.FieldTitleJpn, gallerycache.FieldCategory, gallerycache.FieldThumbnail, gallerycache.FieldUploader, gallerycache.FieldPosted, gallerycache.FieldLanguage, gallerycache.FieldFileSize:
			values[i] = new(sql.NullString)
		case gallerycache.FieldCreatedAt, gallerycache.FieldPostedAt, gallerycache.FieldMetaFetchedAt, gallerycache.FieldDetailsFetchedAt, gallerycache.FieldPagesFetchedAt, gallerycache.FieldThumbnailFetchedAt, gallerycache.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GalleryCache fields.
func (_m *GalleryCache) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case gallerycache.FieldGalleryID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field gallery_id", values[i])
			} else if value.Valid {
				_m.GalleryID = value.Int64
			}
		case gallerycache.FieldToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token", values[i])
			} else if value.Valid {
				_m.Token = value.String
			}
		case gallerycache.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case gallerycache.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case gallerycache.FieldTitleJpn:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title_jpn", values[i])
			} else if value.Valid {
				_m.TitleJpn = value.String
			}
		case gallerycache.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = value.String
			}
		case gallerycache.FieldThumbnail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field thumbnail", values[i])
			} else if value.Valid {
				_m.Thumbnail = value.String
			}
		case gallerycache.FieldPageCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field page_count", values[i])
			} else if value.Valid {
				_m.PageCount = int(value.Int64)
			}
		case gallerycache.FieldRating:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rating", values[i])
			} else if value.Valid {
				_m.Rating = value.Float64
			}
		case gallerycache.FieldRatingCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rating_count", values[i])
			} else if value.Valid {
				_m.RatingCount = int(value.Int64)
			}
		case gallerycache.FieldUploader:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field uploader", values[i])
			} else if value.Valid {
				_m.Uploader = value.String
			}
		case gallerycache.FieldPosted:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field posted", values[i])
			} else if value.Valid {
				_m.Posted = value.String
			}
		case gallerycache.FieldPostedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field posted_at", values[i])
			} else if value.Valid {
				_m.PostedAt = new(time.Time)
				*_m.PostedAt = value.Time
			}
		case gallerycache.FieldLanguage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field language", values[i])
			} else if value.Valid {
				_m.Language = value.String
			}
		case gallerycache.FieldTranslated:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field translated", values[i])
			} else if value.Valid {
				_m.Translated = value.Bool
			}
		case gallerycache.FieldFileSize:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_size", values[i])
			} else if value.Valid {
				_m.FileSize = value.String
			}
		case gallerycache.FieldFavorited:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field favorited", values[i])
			} else if value.Valid {
				_m.Favorited = int(value.Int64)
			}
		case gallerycache.FieldExpunged:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field expunged", values[i])
			} else if value.Valid {
				_m.Expunged = value.Bool
			}
		case gallerycache.FieldTags:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field tags", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Tags); err != nil {
					return fmt.Errorf("unmarshal field tags: %w", err)
				}
			}
		case gallerycache.FieldPages:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field pages", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Pages); err != nil {
					return fmt.Errorf("unmarshal field pages: %w", err)
				}
			}
		case gallerycache.FieldThumbnails:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field thumbnails", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Thumbnails); err != nil {
					return fmt.Errorf("unmarshal field thumbnails: %w", err)
				}
			}
		case gallerycache.FieldMetaFetchedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field meta_fetched_at", values[i])
			} else if value.Valid {
				_m.MetaFetchedAt = new(time.Time)
				*_m.MetaFetchedAt = value.Time
			}
		case gallerycache.FieldDetailsFetchedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field details_fetched_at", values[i])
			} else if value.Valid {
				_m.DetailsFetchedAt = new(time.Time)
				*_m.DetailsFetchedAt = value.Time
			}
		case gallerycache.FieldPagesFetchedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field pages_fetched_at", values[i])
			} else if value.Valid {
				_m.PagesFetchedAt = new(time.Time)
				*_m.PagesFetchedAt = value.Time
			}
		case gallerycache.FieldThumbnailFetchedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field thumbnail_fetched_at", values[i])
			} else if value.Valid {
				_m.ThumbnailFetchedAt = new(time.Time)
				*_m.ThumbnailFetchedAt = value.Time
			}
		case gallerycache.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GalleryCache.
// This includes values selected through modifiers, order, etc.
func (_m *GalleryCache) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this GalleryCache.
// Note that you need to call GalleryCache.Unwrap() before calling this method if this GalleryCache
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GalleryCache) Update() *GalleryCacheUpdateOne {
	return NewGalleryCacheClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GalleryCache entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GalleryCache) Unwrap() *GalleryCache {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GalleryCache is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GalleryCache) String() string {
	var builder strings.Builder
	builder.WriteString("GalleryCache(")
	builder.WriteString("gallery_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GalleryID))
	builder.WriteString(", ")
	builder.WriteString("token=")
	builder.WriteString(_m.Token)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("title_jpn=")
	builder.WriteString(_m.TitleJpn)
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(_m.Category)
	builder.WriteString(", ")
	builder.WriteString("thumbnail=")
	builder.WriteString(_m.Thumbnail)
	builder.WriteString(", ")
	builder.WriteString("page_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.PageCount))
	builder.WriteString(", ")
	builder.WriteString("rating=")
	builder.WriteString(fmt.Sprintf("%v", _m.Rating))
	builder.WriteString(", ")
	builder.WriteString("rating_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RatingCount))
	builder.WriteString(", ")
	builder.WriteString("uploader=")
	builder.WriteString(_m.Uploader)
	builder.WriteString(", ")
	builder.WriteString("posted=")
	builder.WriteString(_m.Posted)
	builder.WriteString(", ")
	if v := _m.PostedAt; v != nil {
		builder.WriteString("posted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("language=")
	builder.WriteString(_m.Language)
	builder.WriteString(", ")
	builder.WriteString("translated=")
	builder.WriteString(fmt.Sprintf("%v", _m.Translated))
	builder.WriteString(", ")
	builder.WriteString("file_size=")
	builder.WriteString(_m.FileSize)
	builder.WriteString(", ")
	builder.WriteString("favorited=")
	builder.WriteString(fmt.Sprintf("%v", _m.Favorited))
	builder.WriteString(", ")
	builder.WriteString("expunged=")
	builder.WriteString(fmt.Sprintf("%v", _m.Expunged))
	builder.WriteString(", ")
	builder.WriteString("tags=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tags))
	builder.WriteString(", ")
	builder.WriteString("pages=")
	builder.WriteString(fmt.Sprintf("%v", _m.Pages))
	builder.WriteString(", ")
	builder.WriteString("thumbnails=")
	builder.WriteString(fmt.Sprintf("%v", _m.Thumbnails))
	builder.WriteString(", ")
	if v := _m.MetaFetchedAt; v != nil {
		builder.WriteString("meta_fetched_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DetailsFetchedAt; v != nil {
		builder.WriteString("details_fetched_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.PagesFetchedAt; v != nil {
		builder.WriteString("pages_fetched_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ThumbnailFetchedAt; v != nil {
		builder.WriteString("thumbnail_fetched_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// GalleryCaches is a parsable slice of GalleryCache.
type GalleryCaches []*GalleryCache
