// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"manga-reader/internal/ent/bookshelf"
	"manga-reader/internal/ent/predicate"
	"manga-reader/internal/ent/prefilljob"
	"manga-reader/internal/ent/readingprogress"
	"manga-reader/internal/model"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeBookshelf       = "Bookshelf"
	TypePrefillJob      = "PrefillJob"
	TypeReadingProgress = "ReadingProgress"
)

// BookshelfMutation represents an operation that mutates the Bookshelf nodes in the graph.
type BookshelfMutation struct {
	config
	op            Op
	typ           string
	id            *int
	gallery_id    *int64
	addgallery_id *int64
	token         *string
	title         *string
	title_jpn     *string
	category      *string
	thumbnail     *string
	page_count    *int
	addpage_count *int
	added_at      *time.Time
	updated_at    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Bookshelf, error)
	predicates    []predicate.Bookshelf
}

var _ ent.Mutation = (*BookshelfMutation)(nil)

// bookshelfOption allows management of the mutation configuration using functional options.
type bookshelfOption func(*BookshelfMutation)

// newBookshelfMutation creates new mutation for the Bookshelf entity.
func newBookshelfMutation(c config, op Op, opts ...bookshelfOption) *BookshelfMutation {
	m := &BookshelfMutation{
		config:        c,
		op:            op,
		typ:           TypeBookshelf,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withBookshelfID sets the ID field of the mutation.
func withBookshelfID(id int) bookshelfOption {
	return func(m *BookshelfMutation) {
		var (
			err   error
			once  sync.Once
			value *Bookshelf
		)
		m.oldValue = func(ctx context.Context) (*Bookshelf, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Bookshelf.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withBookshelf sets the old Bookshelf of the mutation.
func withBookshelf(node *Bookshelf) bookshelfOption {
	return func(m *BookshelfMutation) {
		m.oldValue = func(context.Context) (*Bookshelf, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m BookshelfMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m BookshelfMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *BookshelfMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *BookshelfMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Bookshelf.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetGalleryID sets the "gallery_id" field.
func (m *BookshelfMutation) SetGalleryID(i int64) {
	m.gallery_id = &i
	m.addgallery_id = nil
}

// GalleryID returns the value of the "gallery_id" field in the mutation.
func (m *BookshelfMutation) GalleryID() (r int64, exists bool) {
	v := m.gallery_id
	if v == nil {
		return
	}
	return *v, true
}

// OldGalleryID returns the old "gallery_id" field's value of the Bookshelf entity.
// If the Bookshelf object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BookshelfMutation) OldGalleryID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldGalleryID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldGalleryID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGalleryID: %w", err)
	}
	return oldValue.GalleryID, nil
}

// AddGalleryID adds i to the "gallery_id" field.
func (m *BookshelfMutation) AddGalleryID(i int64) {
	if m.addgallery_id != nil {
		*m.addgallery_id += i
	} else {
		m.addgallery_id = &i
	}
}

// AddedGalleryID returns the value that was added to the "gallery_id" field in this mutation.
func (m *BookshelfMutation) AddedGalleryID() (r int64, exists bool) {
	v := m.addgallery_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetGalleryID resets all changes to the "gallery_id" field.
func (m *BookshelfMutation) ResetGalleryID() {
	m.gallery_id = nil
	m.addgallery_id = nil
}

// SetToken sets the "token" field.
func (m *BookshelfMutation) SetToken(s string) {
	m.token = &s
}

// Token returns the value of the "token" field in the mutation.
func (m *BookshelfMutation) Token() (r string, exists bool) {
	v := m.token
	if v == nil {
		return
	}
	return *v, true
}

// OldToken returns the old "token" field's value of the Bookshelf entity.
// If the Bookshelf object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BookshelfMutation) OldToken(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldToken is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldToken requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldToken: %w", err)
	}
	return oldValue.Token, nil
}

// ResetToken resets all changes to the "token" field.
func (m *BookshelfMutation) ResetToken() {
	m.token = nil
}

// SetTitle sets the "title" field.
func (m *BookshelfMutation) SetTitle(s string) {
	m.title = &s
}

// Title returns the value of the "title" field in the mutation.
func (m *BookshelfMutation) Title() (r string, exists bool) {
	v := m.title
	if v == nil {
		return
	}
	return *v, true
}

// OldTitle returns the old "title" field's value of the Bookshelf entity.
// If the Bookshelf object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BookshelfMutation) OldTitle(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTitle is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTitle requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTitle: %w", err)
	}
	return oldValue.Title, nil
}

// ResetTitle resets all changes to the "title" field.
func (m *BookshelfMutation) ResetTitle() {
	m.title = nil
}

// SetTitleJpn sets the "title_jpn" field.
func (m *BookshelfMutation) SetTitleJpn(s string) {
	m.title_jpn = &s
}

// TitleJpn returns the value of the "title_jpn" field in the mutation.
func (m *BookshelfMutation) TitleJpn() (r string, exists bool) {
	v := m.title_jpn
	if v == nil {
		return
	}
	return *v, true
}

// OldTitleJpn returns the old "title_jpn" field's value of the Bookshelf entity.
// If the Bookshelf object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BookshelfMutation) OldTitleJpn(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTitleJpn is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTitleJpn requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTitleJpn: %w", err)
	}
	return oldValue.TitleJpn, nil
}

// ResetTitleJpn resets all changes to the "title_jpn" field.
func (m *BookshelfMutation) ResetTitleJpn() {
	m.title_jpn = nil
}

// SetCategory sets the "category" field.
func (m *BookshelfMutation) SetCategory(s string) {
	m.category = &s
}

// Category returns the value of the "category" field in the mutation.
func (m *BookshelfMutation) Category() (r string, exists bool) {
	v := m.category
	if v == nil {
		return
	}
	return *v, true
}

// OldCategory returns the old "category" field's value of the Bookshelf entity.
// If the Bookshelf object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BookshelfMutation) OldCategory(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCategory is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCategory requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCategory: %w", err)
	}
	return oldValue.Category, nil
}

// ResetCategory resets all changes to the "category" field.
func (m *BookshelfMutation) ResetCategory() {
	m.category = nil
}

// SetThumbnail sets the "thumbnail" field.
func (m *BookshelfMutation) SetThumbnail(s string) {
	m.thumbnail = &s
}

// Thumbnail returns the value of the "thumbnail" field in the mutation.
func (m *BookshelfMutation) Thumbnail() (r string, exists bool) {
	v := m.thumbnail
	if v == nil {
		return
	}
	return *v, true
}

// OldThumbnail returns the old "thumbnail" field's value of the Bookshelf entity.
// If the Bookshelf object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BookshelfMutation) OldThumbnail(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldThumbnail is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldThumbnail requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldThumbnail: %w", err)
	}
	return oldValue.Thumbnail, nil
}

// ResetThumbnail resets all changes to the "thumbnail" field.
func (m *BookshelfMutation) ResetThumbnail() {
	m.thumbnail = nil
}

// SetPageCount sets the "page_count" field.
func (m *BookshelfMutation) SetPageCount(i int) {
	m.page_count = &i
	m.addpage_count = nil
}

// PageCount returns the value of the "page_count" field in the mutation.
func (m *BookshelfMutation) PageCount() (r int, exists bool) {
	v := m.page_count
	if v == nil {
		return
	}
	return *v, true
}

// OldPageCount returns the old "page_count" field's value of the Bookshelf entity.
// If the Bookshelf object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BookshelfMutation) OldPageCount(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPageCount is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPageCount requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPageCount: %w", err)
	}
	return oldValue.PageCount, nil
}

// AddPageCount adds i to the "page_count" field.
func (m *BookshelfMutation) AddPageCount(i int) {
	if m.addpage_count != nil {
		*m.addpage_count += i
	} else {
		m.addpage_count = &i
	}
}

// AddedPageCount returns the value that was added to the "page_count" field in this mutation.
func (m *BookshelfMutation) AddedPageCount() (r int, exists bool) {
	v := m.addpage_count
	if v == nil {
		return
	}
	return *v, true
}

// ResetPageCount resets all changes to the "page_count" field.
func (m *BookshelfMutation) ResetPageCount() {
	m.page_count = nil
	m.addpage_count = nil
}

// SetAddedAt sets the "added_at" field.
func (m *BookshelfMutation) SetAddedAt(t time.Time) {
	m.added_at = &t
}

// AddedAt returns the value of the "added_at" field in the mutation.
func (m *BookshelfMutation) AddedAt() (r time.Time, exists bool) {
	v := m.added_at
	if v == nil {
		return
	}
	return *v, true
}

// OldAddedAt returns the old "added_at" field's value of the Bookshelf entity.
// If the Bookshelf object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BookshelfMutation) OldAddedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAddedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAddedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAddedAt: %w", err)
	}
	return oldValue.AddedAt, nil
}

// ResetAddedAt resets all changes to the "added_at" field.
func (m *BookshelfMutation) ResetAddedAt() {
	m.added_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *BookshelfMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *BookshelfMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Bookshelf entity.
// If the Bookshelf object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BookshelfMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *BookshelfMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// Where appends a list predicates to the BookshelfMutation builder.
func (m *BookshelfMutation) Where(ps ...predicate.Bookshelf) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the BookshelfMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *BookshelfMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Bookshelf, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *BookshelfMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *BookshelfMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Bookshelf).
func (m *BookshelfMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *BookshelfMutation) Fields() []string {
	fields := make([]string, 0, 9)
	if m.gallery_id != nil {
		fields = append(fields, bookshelf.FieldGalleryID)
	}
	if m.token != nil {
		fields = append(fields, bookshelf.FieldToken)
	}
	if m.title != nil {
		fields = append(fields, bookshelf.FieldTitle)
	}
	if m.title_jpn != nil {
		fields = append(fields, bookshelf.FieldTitleJpn)
	}
	if m.category != nil {
		fields = append(fields, bookshelf.FieldCategory)
	}
	if m.thumbnail != nil {
		fields = append(fields, bookshelf.FieldThumbnail)
	}
	if m.page_count != nil {
		fields = append(fields, bookshelf.FieldPageCount)
	}
	if m.added_at != nil {
		fields = append(fields, bookshelf.FieldAddedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, bookshelf.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *BookshelfMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case bookshelf.FieldGalleryID:
		return m.GalleryID()
	case bookshelf.FieldToken:
		return m.Token()
	case bookshelf.FieldTitle:
		return m.Title()
	case bookshelf.FieldTitleJpn:
		return m.TitleJpn()
	case bookshelf.FieldCategory:
		return m.Category()
	case bookshelf.FieldThumbnail:
		return m.Thumbnail()
	case bookshelf.FieldPageCount:
		return m.PageCount()
	case bookshelf.FieldAddedAt:
		return m.AddedAt()
	case bookshelf.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *BookshelfMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case bookshelf.FieldGalleryID:
		return m.OldGalleryID(ctx)
	case bookshelf.FieldToken:
		return m.OldToken(ctx)
	case bookshelf.FieldTitle:
		return m.OldTitle(ctx)
	case bookshelf.FieldTitleJpn:
		return m.OldTitleJpn(ctx)
	case bookshelf.FieldCategory:
		return m.OldCategory(ctx)
	case bookshelf.FieldThumbnail:
		return m.OldThumbnail(ctx)
	case bookshelf.FieldPageCount:
		return m.OldPageCount(ctx)
	case bookshelf.FieldAddedAt:
		return m.OldAddedAt(ctx)
	case bookshelf.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Bookshelf field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *BookshelfMutation) SetField(name string, value ent.Value) error {
	switch name {
	case bookshelf.FieldGalleryID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGalleryID(v)
		return nil
	case bookshelf.FieldToken:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetToken(v)
		return nil
	case bookshelf.FieldTitle:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTitle(v)
		return nil
	case bookshelf.FieldTitleJpn:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTitleJpn(v)
		return nil
	case bookshelf.FieldCategory:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCategory(v)
		return nil
	case bookshelf.FieldThumbnail:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetThumbnail(v)
		return nil
	case bookshelf.FieldPageCount:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPageCount(v)
		return nil
	case bookshelf.FieldAddedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAddedAt(v)
		return nil
	case bookshelf.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Bookshelf field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *BookshelfMutation) AddedFields() []string {
	var fields []string
	if m.addgallery_id != nil {
		fields = append(fields, bookshelf.FieldGalleryID)
	}
	if m.addpage_count != nil {
		fields = append(fields, bookshelf.FieldPageCount)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *BookshelfMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case bookshelf.FieldGalleryID:
		return m.AddedGalleryID()
	case bookshelf.FieldPageCount:
		return m.AddedPageCount()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *BookshelfMutation) AddField(name string, value ent.Value) error {
	switch name {
	case bookshelf.FieldGalleryID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddGalleryID(v)
		return nil
	case bookshelf.FieldPageCount:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPageCount(v)
		return nil
	}
	return fmt.Errorf("unknown Bookshelf numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *BookshelfMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *BookshelfMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *BookshelfMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Bookshelf nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *BookshelfMutation) ResetField(name string) error {
	switch name {
	case bookshelf.FieldGalleryID:
		m.ResetGalleryID()
		return nil
	case bookshelf.FieldToken:
		m.ResetToken()
		return nil
	case bookshelf.FieldTitle:
		m.ResetTitle()
		return nil
	case bookshelf.FieldTitleJpn:
		m.ResetTitleJpn()
		return nil
	case bookshelf.FieldCategory:
		m.ResetCategory()
		return nil
	case bookshelf.FieldThumbnail:
		m.ResetThumbnail()
		return nil
	case bookshelf.FieldPageCount:
		m.ResetPageCount()
		return nil
	case bookshelf.FieldAddedAt:
		m.ResetAddedAt()
		return nil
	case bookshelf.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown Bookshelf field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *BookshelfMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *BookshelfMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *BookshelfMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *BookshelfMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *BookshelfMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *BookshelfMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *BookshelfMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Bookshelf unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *BookshelfMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Bookshelf edge %s", name)
}

// PrefillJobMutation represents an operation that mutates the PrefillJob nodes in the graph.
type PrefillJobMutation struct {
	config
	op              Op
	typ             string
	id              *int
	gallery_id      *int64
	addgallery_id   *int64
	gallery_token   *string
	title           *string
	urls            *[]string
	appendurls      []string
	status          *string
	total           *int
	addtotal        *int
	failed_count    *int
	addfailed_count *int
	errors          *[]model.PrefillItemError
	appenderrors    []model.PrefillItemError
	created_at      *time.Time
	updated_at      *time.Time
	finished_at     *time.Time
	clearedFields   map[string]struct{}
	done            bool
	oldValue        func(context.Context) (*PrefillJob, error)
	predicates      []predicate.PrefillJob
}

var _ ent.Mutation = (*PrefillJobMutation)(nil)

// prefilljobOption allows management of the mutation configuration using functional options.
type prefilljobOption func(*PrefillJobMutation)

// newPrefillJobMutation creates new mutation for the PrefillJob entity.
func newPrefillJobMutation(c config, op Op, opts ...prefilljobOption) *PrefillJobMutation {
	m := &PrefillJobMutation{
		config:        c,
		op:            op,
		typ:           TypePrefillJob,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withPrefillJobID sets the ID field of the mutation.
func withPrefillJobID(id int) prefilljobOption {
	return func(m *PrefillJobMutation) {
		var (
			err   error
			once  sync.Once
			value *PrefillJob
		)
		m.oldValue = func(ctx context.Context) (*PrefillJob, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().PrefillJob.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withPrefillJob sets the old PrefillJob of the mutation.
func withPrefillJob(node *PrefillJob) prefilljobOption {
	return func(m *PrefillJobMutation) {
		m.oldValue = func(context.Context) (*PrefillJob, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m PrefillJobMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m PrefillJobMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *PrefillJobMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *PrefillJobMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().PrefillJob.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetGalleryID sets the "gallery_id" field.
func (m *PrefillJobMutation) SetGalleryID(i int64) {
	m.gallery_id = &i
	m.addgallery_id = nil
}

// GalleryID returns the value of the "gallery_id" field in the mutation.
func (m *PrefillJobMutation) GalleryID() (r int64, exists bool) {
	v := m.gallery_id
	if v == nil {
		return
	}
	return *v, true
}

// OldGalleryID returns the old "gallery_id" field's value of the PrefillJob entity.
// If the PrefillJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PrefillJobMutation) OldGalleryID(ctx context.Context) (v *int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldGalleryID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldGalleryID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGalleryID: %w", err)
	}
	return oldValue.GalleryID, nil
}

// AddGalleryID adds i to the "gallery_id" field.
func (m *PrefillJobMutation) AddGalleryID(i int64) {
	if m.addgallery_id != nil {
		*m.addgallery_id += i
	} else {
		m.addgallery_id = &i
	}
}

// AddedGalleryID returns the value that was added to the "gallery_id" field in this mutation.
func (m *PrefillJobMutation) AddedGalleryID() (r int64, exists bool) {
	v := m.addgallery_id
	if v == nil {
		return
	}
	return *v, true
}

// ClearGalleryID clears the value of the "gallery_id" field.
func (m *PrefillJobMutation) ClearGalleryID() {
	m.gallery_id = nil
	m.addgallery_id = nil
	m.clearedFields[prefilljob.FieldGalleryID] = struct{}{}
}

// GalleryIDCleared returns if the "gallery_id" field was cleared in this mutation.
func (m *PrefillJobMutation) GalleryIDCleared() bool {
	_, ok := m.clearedFields[prefilljob.FieldGalleryID]
	return ok
}

// ResetGalleryID resets all changes to the "gallery_id" field.
func (m *PrefillJobMutation) ResetGalleryID() {
	m.gallery_id = nil
	m.addgallery_id = nil
	delete(m.clearedFields, prefilljob.FieldGalleryID)
}

// SetGalleryToken sets the "gallery_token" field.
func (m *PrefillJobMutation) SetGalleryToken(s string) {
	m.gallery_token = &s
}

// GalleryToken returns the value of the "gallery_token" field in the mutation.
func (m *PrefillJobMutation) GalleryToken() (r string, exists bool) {
	v := m.gallery_token
	if v == nil {
		return
	}
	return *v, true
}

// OldGalleryToken returns the old "gallery_token" field's value of the PrefillJob entity.
// If the PrefillJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PrefillJobMutation) OldGalleryToken(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldGalleryToken is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldGalleryToken requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGalleryToken: %w", err)
	}
	return oldValue.GalleryToken, nil
}

// ResetGalleryToken resets all changes to the "gallery_token" field.
func (m *PrefillJobMutation) ResetGalleryToken() {
	m.gallery_token = nil
}

// SetTitle sets the "title" field.
func (m *PrefillJobMutation) SetTitle(s string) {
	m.title = &s
}

// Title returns the value of the "title" field in the mutation.
func (m *PrefillJobMutation) Title() (r string, exists bool) {
	v := m.title
	if v == nil {
		return
	}
	return *v, true
}

// OldTitle returns the old "title" field's value of the PrefillJob entity.
// If the PrefillJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PrefillJobMutation) OldTitle(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTitle is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTitle requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTitle: %w", err)
	}
	return oldValue.Title, nil
}

// ResetTitle resets all changes to the "title" field.
func (m *PrefillJobMutation) ResetTitle() {
	m.title = nil
}

// SetUrls sets the "urls" field.
func (m *PrefillJobMutation) SetUrls(s []string) {
	m.urls = &s
	m.appendurls = nil
}

// Urls returns the value of the "urls" field in the mutation.
func (m *PrefillJobMutation) Urls() (r []string, exists bool) {
	v := m.urls
	if v == nil {
		return
	}
	return *v, true
}

// OldUrls returns the old "urls" field's value of the PrefillJob entity.
// If the PrefillJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PrefillJobMutation) OldUrls(ctx context.Context) (v []string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUrls is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUrls requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUrls: %w", err)
	}
	return oldValue.Urls, nil
}

// AppendUrls adds s to the "urls" field.
func (m *PrefillJobMutation) AppendUrls(s []string) {
	m.appendurls = append(m.appendurls, s...)
}

// AppendedUrls returns the list of values that were appended to the "urls" field in this mutation.
func (m *PrefillJobMutation) AppendedUrls() ([]string, bool) {
	if len(m.appendurls) == 0 {
		return nil, false
	}
	return m.appendurls, true
}

// ResetUrls resets all changes to the "urls" field.
func (m *PrefillJobMutation) ResetUrls() {
	m.urls = nil
	m.appendurls = nil
}

// SetStatus sets the "status" field.
func (m *PrefillJobMutation) SetStatus(s string) {
	m.status = &s
}

// Status returns the value of the "status" field in the mutation.
func (m *PrefillJobMutation) Status() (r string, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the PrefillJob entity.
// If the PrefillJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PrefillJobMutation) OldStatus(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *PrefillJobMutation) ResetStatus() {
	m.status = nil
}

// SetTotal sets the "total" field.
func (m *PrefillJobMutation) SetTotal(i int) {
	m.total = &i
	m.addtotal = nil
}

// Total returns the value of the "total" field in the mutation.
func (m *PrefillJobMutation) Total() (r int, exists bool) {
	v := m.total
	if v == nil {
		return
	}
	return *v, true
}

// OldTotal returns the old "total" field's value of the PrefillJob entity.
// If the PrefillJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PrefillJobMutation) OldTotal(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTotal is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTotal requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTotal: %w", err)
	}
	return oldValue.Total, nil
}

// AddTotal adds i to the "total" field.
func (m *PrefillJobMutation) AddTotal(i int) {
	if m.addtotal != nil {
		*m.addtotal += i
	} else {
		m.addtotal = &i
	}
}

// AddedTotal returns the value that was added to the "total" field in this mutation.
func (m *PrefillJobMutation) AddedTotal() (r int, exists bool) {
	v := m.addtotal
	if v == nil {
		return
	}
	return *v, true
}

// ResetTotal resets all changes to the "total" field.
func (m *PrefillJobMutation) ResetTotal() {
	m.total = nil
	m.addtotal = nil
}

// SetFailedCount sets the "failed_count" field.
func (m *PrefillJobMutation) SetFailedCount(i int) {
	m.failed_count = &i
	m.addfailed_count = nil
}

// FailedCount returns the value of the "failed_count" field in the mutation.
func (m *PrefillJobMutation) FailedCount() (r int, exists bool) {
	v := m.failed_count
	if v == nil {
		return
	}
	return *v, true
}

// OldFailedCount returns the old "failed_count" field's value of the PrefillJob entity.
// If the PrefillJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PrefillJobMutation) OldFailedCount(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFailedCount is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFailedCount requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFailedCount: %w", err)
	}
	return oldValue.FailedCount, nil
}

// AddFailedCount adds i to the "failed_count" field.
func (m *PrefillJobMutation) AddFailedCount(i int) {
	if m.addfailed_count != nil {
		*m.addfailed_count += i
	} else {
		m.addfailed_count = &i
	}
}

// AddedFailedCount returns the value that was added to the "failed_count" field in this mutation.
func (m *PrefillJobMutation) AddedFailedCount() (r int, exists bool) {
	v := m.addfailed_count
	if v == nil {
		return
	}
	return *v, true
}

// ResetFailedCount resets all changes to the "failed_count" field.
func (m *PrefillJobMutation) ResetFailedCount() {
	m.failed_count = nil
	m.addfailed_count = nil
}

// SetErrors sets the "errors" field.
func (m *PrefillJobMutation) SetErrors(mie []model.PrefillItemError) {
	m.errors = &mie
	m.appenderrors = nil
}

// Errors returns the value of the "errors" field in the mutation.
func (m *PrefillJobMutation) Errors() (r []model.PrefillItemError, exists bool) {
	v := m.errors
	if v == nil {
		return
	}
	return *v, true
}

// OldErrors returns the old "errors" field's value of the PrefillJob entity.
// If the PrefillJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PrefillJobMutation) OldErrors(ctx context.Context) (v []model.PrefillItemError, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldErrors is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldErrors requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldErrors: %w", err)
	}
	return oldValue.Errors, nil
}

// AppendErrors adds mie to the "errors" field.
func (m *PrefillJobMutation) AppendErrors(mie []model.PrefillItemError) {
	m.appenderrors = append(m.appenderrors, mie...)
}

// AppendedErrors returns the list of values that were appended to the "errors" field in this mutation.
func (m *PrefillJobMutation) AppendedErrors() ([]model.PrefillItemError, bool) {
	if len(m.appenderrors) == 0 {
		return nil, false
	}
	return m.appenderrors, true
}

// ClearErrors clears the value of the "errors" field.
func (m *PrefillJobMutation) ClearErrors() {
	m.errors = nil
	m.appenderrors = nil
	m.clearedFields[prefilljob.FieldErrors] = struct{}{}
}

// ErrorsCleared returns if the "errors" field was cleared in this mutation.
func (m *PrefillJobMutation) ErrorsCleared() bool {
	_, ok := m.clearedFields[prefilljob.FieldErrors]
	return ok
}

// ResetErrors resets all changes to the "errors" field.
func (m *PrefillJobMutation) ResetErrors() {
	m.errors = nil
	m.appenderrors = nil
	delete(m.clearedFields, prefilljob.FieldErrors)
}

// SetCreatedAt sets the "created_at" field.
func (m *PrefillJobMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *PrefillJobMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the PrefillJob entity.
// If the PrefillJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PrefillJobMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *PrefillJobMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *PrefillJobMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *PrefillJobMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the PrefillJob entity.
// If the PrefillJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PrefillJobMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *PrefillJobMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetFinishedAt sets the "finished_at" field.
func (m *PrefillJobMutation) SetFinishedAt(t time.Time) {
	m.finished_at = &t
}

// FinishedAt returns the value of the "finished_at" field in the mutation.
func (m *PrefillJobMutation) FinishedAt() (r time.Time, exists bool) {
	v := m.finished_at
	if v == nil {
		return
	}
	return *v, true
}

// OldFinishedAt returns the old "finished_at" field's value of the PrefillJob entity.
// If the PrefillJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PrefillJobMutation) OldFinishedAt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFinishedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFinishedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFinishedAt: %w", err)
	}
	return oldValue.FinishedAt, nil
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (m *PrefillJobMutation) ClearFinishedAt() {
	m.finished_at = nil
	m.clearedFields[prefilljob.FieldFinishedAt] = struct{}{}
}

// FinishedAtCleared returns if the "finished_at" field was cleared in this mutation.
func (m *PrefillJobMutation) FinishedAtCleared() bool {
	_, ok := m.clearedFields[prefilljob.FieldFinishedAt]
	return ok
}

// ResetFinishedAt resets all changes to the "finished_at" field.
func (m *PrefillJobMutation) ResetFinishedAt() {
	m.finished_at = nil
	delete(m.clearedFields, prefilljob.FieldFinishedAt)
}

// Where appends a list predicates to the PrefillJobMutation builder.
func (m *PrefillJobMutation) Where(ps ...predicate.PrefillJob) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the PrefillJobMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *PrefillJobMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.PrefillJob, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *PrefillJobMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *PrefillJobMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (PrefillJob).
func (m *PrefillJobMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *PrefillJobMutation) Fields() []string {
	fields := make([]string, 0, 11)
	if m.gallery_id != nil {
		fields = append(fields, prefilljob.FieldGalleryID)
	}
	if m.gallery_token != nil {
		fields = append(fields, prefilljob.FieldGalleryToken)
	}
	if m.title != nil {
		fields = append(fields, prefilljob.FieldTitle)
	}
	if m.urls != nil {
		fields = append(fields, prefilljob.FieldUrls)
	}
	if m.status != nil {
		fields = append(fields, prefilljob.FieldStatus)
	}
	if m.total != nil {
		fields = append(fields, prefilljob.FieldTotal)
	}
	if m.failed_count != nil {
		fields = append(fields, prefilljob.FieldFailedCount)
	}
	if m.errors != nil {
		fields = append(fields, prefilljob.FieldErrors)
	}
	if m.created_at != nil {
		fields = append(fields, prefilljob.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, prefilljob.FieldUpdatedAt)
	}
	if m.finished_at != nil {
		fields = append(fields, prefilljob.FieldFinishedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *PrefillJobMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case prefilljob.FieldGalleryID:
		return m.GalleryID()
	case prefilljob.FieldGalleryToken:
		return m.GalleryToken()
	case prefilljob.FieldTitle:
		return m.Title()
	case prefilljob.FieldUrls:
		return m.Urls()
	case prefilljob.FieldStatus:
		return m.Status()
	case prefilljob.FieldTotal:
		return m.Total()
	case prefilljob.FieldFailedCount:
		return m.FailedCount()
	case prefilljob.FieldErrors:
		return m.Errors()
	case prefilljob.FieldCreatedAt:
		return m.CreatedAt()
	case prefilljob.FieldUpdatedAt:
		return m.UpdatedAt()
	case prefilljob.FieldFinishedAt:
		return m.FinishedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *PrefillJobMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case prefilljob.FieldGalleryID:
		return m.OldGalleryID(ctx)
	case prefilljob.FieldGalleryToken:
		return m.OldGalleryToken(ctx)
	case prefilljob.FieldTitle:
		return m.OldTitle(ctx)
	case prefilljob.FieldUrls:
		return m.OldUrls(ctx)
	case prefilljob.FieldStatus:
		return m.OldStatus(ctx)
	case prefilljob.FieldTotal:
		return m.OldTotal(ctx)
	case prefilljob.FieldFailedCount:
		return m.OldFailedCount(ctx)
	case prefilljob.FieldErrors:
		return m.OldErrors(ctx)
	case prefilljob.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case prefilljob.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case prefilljob.FieldFinishedAt:
		return m.OldFinishedAt(ctx)
	}
	return nil, fmt.Errorf("unknown PrefillJob field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PrefillJobMutation) SetField(name string, value ent.Value) error {
	switch name {
	case prefilljob.FieldGalleryID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGalleryID(v)
		return nil
	case prefilljob.FieldGalleryToken:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGalleryToken(v)
		return nil
	case prefilljob.FieldTitle:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTitle(v)
		return nil
	case prefilljob.FieldUrls:
		v, ok := value.([]string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUrls(v)
		return nil
	case prefilljob.FieldStatus:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case prefilljob.FieldTotal:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTotal(v)
		return nil
	case prefilljob.FieldFailedCount:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFailedCount(v)
		return nil
	case prefilljob.FieldErrors:
		v, ok := value.([]model.PrefillItemError)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetErrors(v)
		return nil
	case prefilljob.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case prefilljob.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case prefilljob.FieldFinishedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFinishedAt(v)
		return nil
	}
	return fmt.Errorf("unknown PrefillJob field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *PrefillJobMutation) AddedFields() []string {
	var fields []string
	if m.addgallery_id != nil {
		fields = append(fields, prefilljob.FieldGalleryID)
	}
	if m.addtotal != nil {
		fields = append(fields, prefilljob.FieldTotal)
	}
	if m.addfailed_count != nil {
		fields = append(fields, prefilljob.FieldFailedCount)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *PrefillJobMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case prefilljob.FieldGalleryID:
		return m.AddedGalleryID()
	case prefilljob.FieldTotal:
		return m.AddedTotal()
	case prefilljob.FieldFailedCount:
		return m.AddedFailedCount()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PrefillJobMutation) AddField(name string, value ent.Value) error {
	switch name {
	case prefilljob.FieldGalleryID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddGalleryID(v)
		return nil
	case prefilljob.FieldTotal:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddTotal(v)
		return nil
	case prefilljob.FieldFailedCount:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddFailedCount(v)
		return nil
	}
	return fmt.Errorf("unknown PrefillJob numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *PrefillJobMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(prefilljob.FieldGalleryID) {
		fields = append(fields, prefilljob.FieldGalleryID)
	}
	if m.FieldCleared(prefilljob.FieldErrors) {
		fields = append(fields, prefilljob.FieldErrors)
	}
	if m.FieldCleared(prefilljob.FieldFinishedAt) {
		fields = append(fields, prefilljob.FieldFinishedAt)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *PrefillJobMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *PrefillJobMutation) ClearField(name string) error {
	switch name {
	case prefilljob.FieldGalleryID:
		m.ClearGalleryID()
		return nil
	case prefilljob.FieldErrors:
		m.ClearErrors()
		return nil
	case prefilljob.FieldFinishedAt:
		m.ClearFinishedAt()
		return nil
	}
	return fmt.Errorf("unknown PrefillJob nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *PrefillJobMutation) ResetField(name string) error {
	switch name {
	case prefilljob.FieldGalleryID:
		m.ResetGalleryID()
		return nil
	case prefilljob.FieldGalleryToken:
		m.ResetGalleryToken()
		return nil
	case prefilljob.FieldTitle:
		m.ResetTitle()
		return nil
	case prefilljob.FieldUrls:
		m.ResetUrls()
		return nil
	case prefilljob.FieldStatus:
		m.ResetStatus()
		return nil
	case prefilljob.FieldTotal:
		m.ResetTotal()
		return nil
	case prefilljob.FieldFailedCount:
		m.ResetFailedCount()
		return nil
	case prefilljob.FieldErrors:
		m.ResetErrors()
		return nil
	case prefilljob.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case prefilljob.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case prefilljob.FieldFinishedAt:
		m.ResetFinishedAt()
		return nil
	}
	return fmt.Errorf("unknown PrefillJob field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *PrefillJobMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *PrefillJobMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *PrefillJobMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *PrefillJobMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *PrefillJobMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *PrefillJobMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *PrefillJobMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown PrefillJob unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *PrefillJobMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown PrefillJob edge %s", name)
}

// ReadingProgressMutation represents an operation that mutates the ReadingProgress nodes in the graph.
type ReadingProgressMutation struct {
	config
	op              Op
	typ             string
	id              *int
	gallery_id      *int64
	addgallery_id   *int64
	token           *string
	current_page    *int
	addcurrent_page *int
	progress        *float64
	addprogress     *float64
	completed       *bool
	title           *string
	title_jpn       *string
	category        *string
	thumbnail       *string
	page_count      *int
	addpage_count   *int
	started_at      *time.Time
	updated_at      *time.Time
	clearedFields   map[string]struct{}
	done            bool
	oldValue        func(context.Context) (*ReadingProgress, error)
	predicates      []predicate.ReadingProgress
}

var _ ent.Mutation = (*ReadingProgressMutation)(nil)

// readingprogressOption allows management of the mutation configuration using functional options.
type readingprogressOption func(*ReadingProgressMutation)

// newReadingProgressMutation creates new mutation for the ReadingProgress entity.
func newReadingProgressMutation(c config, op Op, opts ...readingprogressOption) *ReadingProgressMutation {
	m := &ReadingProgressMutation{
		config:        c,
		op:            op,
		typ:           TypeReadingProgress,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withReadingProgressID sets the ID field of the mutation.
func withReadingProgressID(id int) readingprogressOption {
	return func(m *ReadingProgressMutation) {
		var (
			err   error
			once  sync.Once
			value *ReadingProgress
		)
		m.oldValue = func(ctx context.Context) (*ReadingProgress, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().ReadingProgress.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withReadingProgress sets the old ReadingProgress of the mutation.
func withReadingProgress(node *ReadingProgress) readingprogressOption {
	return func(m *ReadingProgressMutation) {
		m.oldValue = func(context.Context) (*ReadingProgress, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ReadingProgressMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ReadingProgressMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ReadingProgressMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ReadingProgressMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().ReadingProgress.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetGalleryID sets the "gallery_id" field.
func (m *ReadingProgressMutation) SetGalleryID(i int64) {
	m.gallery_id = &i
	m.addgallery_id = nil
}

// GalleryID returns the value of the "gallery_id" field in the mutation.
func (m *ReadingProgressMutation) GalleryID() (r int64, exists bool) {
	v := m.gallery_id
	if v == nil {
		return
	}
	return *v, true
}

// OldGalleryID returns the old "gallery_id" field's value of the ReadingProgress entity.
// If the ReadingProgress object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ReadingProgressMutation) OldGalleryID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldGalleryID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldGalleryID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGalleryID: %w", err)
	}
	return oldValue.GalleryID, nil
}

// AddGalleryID adds i to the "gallery_id" field.
func (m *ReadingProgressMutation) AddGalleryID(i int64) {
	if m.addgallery_id != nil {
		*m.addgallery_id += i
	} else {
		m.addgallery_id = &i
	}
}

// AddedGalleryID returns the value that was added to the "gallery_id" field in this mutation.
func (m *ReadingProgressMutation) AddedGalleryID() (r int64, exists bool) {
	v := m.addgallery_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetGalleryID resets all changes to the "gallery_id" field.
func (m *ReadingProgressMutation) ResetGalleryID() {
	m.gallery_id = nil
	m.addgallery_id = nil
}

// SetToken sets the "token" field.
func (m *ReadingProgressMutation) SetToken(s string) {
	m.token = &s
}

// Token returns the value of the "token" field in the mutation.
func (m *ReadingProgressMutation) Token() (r string, exists bool) {
	v := m.token
	if v == nil {
		return
	}
	return *v, true
}

// OldToken returns the old "token" field's value of the ReadingProgress entity.
// If the ReadingProgress object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ReadingProgressMutation) OldToken(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldToken is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldToken requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldToken: %w", err)
	}
	return oldValue.Token, nil
}

// ResetToken resets all changes to the "token" field.
func (m *ReadingProgressMutation) ResetToken() {
	m.token = nil
}

// SetCurrentPage sets the "current_page" field.
func (m *ReadingProgressMutation) SetCurrentPage(i int) {
	m.current_page = &i
	m.addcurrent_page = nil
}

// CurrentPage returns the value of the "current_page" field in the mutation.
func (m *ReadingProgressMutation) CurrentPage() (r int, exists bool) {
	v := m.current_page
	if v == nil {
		return
	}
	return *v, true
}

// OldCurrentPage returns the old "current_page" field's value of the ReadingProgress entity.
// If the ReadingProgress object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ReadingProgressMutation) OldCurrentPage(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCurrentPage is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCurrentPage requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCurrentPage: %w", err)
	}
	return oldValue.CurrentPage, nil
}

// AddCurrentPage adds i to the "current_page" field.
func (m *ReadingProgressMutation) AddCurrentPage(i int) {
	if m.addcurrent_page != nil {
		*m.addcurrent_page += i
	} else {
		m.addcurrent_page = &i
	}
}

// AddedCurrentPage returns the value that was added to the "current_page" field in this mutation.
func (m *ReadingProgressMutation) AddedCurrentPage() (r int, exists bool) {
	v := m.addcurrent_page
	if v == nil {
		return
	}
	return *v, true
}

// ResetCurrentPage resets all changes to the "current_page" field.
func (m *ReadingProgressMutation) ResetCurrentPage() {
	m.current_page = nil
	m.addcurrent_page = nil
}

// SetProgress sets the "progress" field.
func (m *ReadingProgressMutation) SetProgress(f float64) {
	m.progress = &f
	m.addprogress = nil
}

// Progress returns the value of the "progress" field in the mutation.
func (m *ReadingProgressMutation) Progress() (r float64, exists bool) {
	v := m.progress
	if v == nil {
		return
	}
	return *v, true
}

// OldProgress returns the old "progress" field's value of the ReadingProgress entity.
// If the ReadingProgress object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ReadingProgressMutation) OldProgress(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldProgress is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldProgress requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldProgress: %w", err)
	}
	return oldValue.Progress, nil
}

// AddProgress adds f to the "progress" field.
func (m *ReadingProgressMutation) AddProgress(f float64) {
	if m.addprogress != nil {
		*m.addprogress += f
	} else {
		m.addprogress = &f
	}
}

// AddedProgress returns the value that was added to the "progress" field in this mutation.
func (m *ReadingProgressMutation) AddedProgress() (r float64, exists bool) {
	v := m.addprogress
	if v == nil {
		return
	}
	return *v, true
}

// ResetProgress resets all changes to the "progress" field.
func (m *ReadingProgressMutation) ResetProgress() {
	m.progress = nil
	m.addprogress = nil
}

// SetCompleted sets the "completed" field.
func (m *ReadingProgressMutation) SetCompleted(b bool) {
	m.completed = &b
}

// Completed returns the value of the "completed" field in the mutation.
func (m *ReadingProgressMutation) Completed() (r bool, exists bool) {
	v := m.completed
	if v == nil {
		return
	}
	return *v, true
}

// OldCompleted returns the old "completed" field's value of the ReadingProgress entity.
// If the ReadingProgress object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ReadingProgressMutation) OldCompleted(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCompleted is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCompleted requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCompleted: %w", err)
	}
	return oldValue.Completed, nil
}

// ResetCompleted resets all changes to the "completed" field.
func (m *ReadingProgressMutation) ResetCompleted() {
	m.completed = nil
}

// SetTitle sets the "title" field.
func (m *ReadingProgressMutation) SetTitle(s string) {
	m.title = &s
}

// Title returns the value of the "title" field in the mutation.
func (m *ReadingProgressMutation) Title() (r string, exists bool) {
	v := m.title
	if v == nil {
		return
	}
	return *v, true
}

// OldTitle returns the old "title" field's value of the ReadingProgress entity.
// If the ReadingProgress object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ReadingProgressMutation) OldTitle(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTitle is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTitle requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTitle: %w", err)
	}
	return oldValue.Title, nil
}

// ResetTitle resets all changes to the "title" field.
func (m *ReadingProgressMutation) ResetTitle() {
	m.title = nil
}

// SetTitleJpn sets the "title_jpn" field.
func (m *ReadingProgressMutation) SetTitleJpn(s string) {
	m.title_jpn = &s
}

// TitleJpn returns the value of the "title_jpn" field in the mutation.
func (m *ReadingProgressMutation) TitleJpn() (r string, exists bool) {
	v := m.title_jpn
	if v == nil {
		return
	}
	return *v, true
}

// OldTitleJpn returns the old "title_jpn" field's value of the ReadingProgress entity.
// If the ReadingProgress object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ReadingProgressMutation) OldTitleJpn(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTitleJpn is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTitleJpn requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTitleJpn: %w", err)
	}
	return oldValue.TitleJpn, nil
}

// ResetTitleJpn resets all changes to the "title_jpn" field.
func (m *ReadingProgressMutation) ResetTitleJpn() {
	m.title_jpn = nil
}

// SetCategory sets the "category" field.
func (m *ReadingProgressMutation) SetCategory(s string) {
	m.category = &s
}

// Category returns the value of the "category" field in the mutation.
func (m *ReadingProgressMutation) Category() (r string, exists bool) {
	v := m.category
	if v == nil {
		return
	}
	return *v, true
}

// OldCategory returns the old "category" field's value of the ReadingProgress entity.
// If the ReadingProgress object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ReadingProgressMutation) OldCategory(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCategory is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCategory requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCategory: %w", err)
	}
	return oldValue.Category, nil
}

// ResetCategory resets all changes to the "category" field.
func (m *ReadingProgressMutation) ResetCategory() {
	m.category = nil
}

// SetThumbnail sets the "thumbnail" field.
func (m *ReadingProgressMutation) SetThumbnail(s string) {
	m.thumbnail = &s
}

// Thumbnail returns the value of the "thumbnail" field in the mutation.
func (m *ReadingProgressMutation) Thumbnail() (r string, exists bool) {
	v := m.thumbnail
	if v == nil {
		return
	}
	return *v, true
}

// OldThumbnail returns the old "thumbnail" field's value of the ReadingProgress entity.
// If the ReadingProgress object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ReadingProgressMutation) OldThumbnail(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldThumbnail is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldThumbnail requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldThumbnail: %w", err)
	}
	return oldValue.Thumbnail, nil
}

// ResetThumbnail resets all changes to the "thumbnail" field.
func (m *ReadingProgressMutation) ResetThumbnail() {
	m.thumbnail = nil
}

// SetPageCount sets the "page_count" field.
func (m *ReadingProgressMutation) SetPageCount(i int) {
	m.page_count = &i
	m.addpage_count = nil
}

// PageCount returns the value of the "page_count" field in the mutation.
func (m *ReadingProgressMutation) PageCount() (r int, exists bool) {
	v := m.page_count
	if v == nil {
		return
	}
	return *v, true
}

// OldPageCount returns the old "page_count" field's value of the ReadingProgress entity.
// If the ReadingProgress object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ReadingProgressMutation) OldPageCount(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPageCount is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPageCount requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPageCount: %w", err)
	}
	return oldValue.PageCount, nil
}

// AddPageCount adds i to the "page_count" field.
func (m *ReadingProgressMutation) AddPageCount(i int) {
	if m.addpage_count != nil {
		*m.addpage_count += i
	} else {
		m.addpage_count = &i
	}
}

// AddedPageCount returns the value that was added to the "page_count" field in this mutation.
func (m *ReadingProgressMutation) AddedPageCount() (r int, exists bool) {
	v := m.addpage_count
	if v == nil {
		return
	}
	return *v, true
}

// ResetPageCount resets all changes to the "page_count" field.
func (m *ReadingProgressMutation) ResetPageCount() {
	m.page_count = nil
	m.addpage_count = nil
}

// SetStartedAt sets the "started_at" field.
func (m *ReadingProgressMutation) SetStartedAt(t time.Time) {
	m.started_at = &t
}

// StartedAt returns the value of the "started_at" field in the mutation.
func (m *ReadingProgressMutation) StartedAt() (r time.Time, exists bool) {
	v := m.started_at
	if v == nil {
		return
	}
	return *v, true
}

// OldStartedAt returns the old "started_at" field's value of the ReadingProgress entity.
// If the ReadingProgress object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ReadingProgressMutation) OldStartedAt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStartedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStartedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStartedAt: %w", err)
	}
	return oldValue.StartedAt, nil
}

// ClearStartedAt clears the value of the "started_at" field.
func (m *ReadingProgressMutation) ClearStartedAt() {
	m.started_at = nil
	m.clearedFields[readingprogress.FieldStartedAt] = struct{}{}
}

// StartedAtCleared returns if the "started_at" field was cleared in this mutation.
func (m *ReadingProgressMutation) StartedAtCleared() bool {
	_, ok := m.clearedFields[readingprogress.FieldStartedAt]
	return ok
}

// ResetStartedAt resets all changes to the "started_at" field.
func (m *ReadingProgressMutation) ResetStartedAt() {
	m.started_at = nil
	delete(m.clearedFields, readingprogress.FieldStartedAt)
}

// SetUpdatedAt sets the "updated_at" field.
func (m *ReadingProgressMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *ReadingProgressMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the ReadingProgress entity.
// If the ReadingProgress object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ReadingProgressMutation) OldUpdatedAt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (m *ReadingProgressMutation) ClearUpdatedAt() {
	m.updated_at = nil
	m.clearedFields[readingprogress.FieldUpdatedAt] = struct{}{}
}

// UpdatedAtCleared returns if the "updated_at" field was cleared in this mutation.
func (m *ReadingProgressMutation) UpdatedAtCleared() bool {
	_, ok := m.clearedFields[readingprogress.FieldUpdatedAt]
	return ok
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *ReadingProgressMutation) ResetUpdatedAt() {
	m.updated_at = nil
	delete(m.clearedFields, readingprogress.FieldUpdatedAt)
}

// Where appends a list predicates to the ReadingProgressMutation builder.
func (m *ReadingProgressMutation) Where(ps ...predicate.ReadingProgress) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ReadingProgressMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ReadingProgressMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.ReadingProgress, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ReadingProgressMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ReadingProgressMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (ReadingProgress).
func (m *ReadingProgressMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ReadingProgressMutation) Fields() []string {
	fields := make([]string, 0, 12)
	if m.gallery_id != nil {
		fields = append(fields, readingprogress.FieldGalleryID)
	}
	if m.token != nil {
		fields = append(fields, readingprogress.FieldToken)
	}
	if m.current_page != nil {
		fields = append(fields, readingprogress.FieldCurrentPage)
	}
	if m.progress != nil {
		fields = append(fields, readingprogress.FieldProgress)
	}
	if m.completed != nil {
		fields = append(fields, readingprogress.FieldCompleted)
	}
	if m.title != nil {
		fields = append(fields, readingprogress.FieldTitle)
	}
	if m.title_jpn != nil {
		fields = append(fields, readingprogress.FieldTitleJpn)
	}
	if m.category != nil {
		fields = append(fields, readingprogress.FieldCategory)
	}
	if m.thumbnail != nil {
		fields = append(fields, readingprogress.FieldThumbnail)
	}
	if m.page_count != nil {
		fields = append(fields, readingprogress.FieldPageCount)
	}
	if m.started_at != nil {
		fields = append(fields, readingprogress.FieldStartedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, readingprogress.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ReadingProgressMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case readingprogress.FieldGalleryID:
		return m.GalleryID()
	case readingprogress.FieldToken:
		return m.Token()
	case readingprogress.FieldCurrentPage:
		return m.CurrentPage()
	case readingprogress.FieldProgress:
		return m.Progress()
	case readingprogress.FieldCompleted:
		return m.Completed()
	case readingprogress.FieldTitle:
		return m.Title()
	case readingprogress.FieldTitleJpn:
		return m.TitleJpn()
	case readingprogress.FieldCategory:
		return m.Category()
	case readingprogress.FieldThumbnail:
		return m.Thumbnail()
	case readingprogress.FieldPageCount:
		return m.PageCount()
	case readingprogress.FieldStartedAt:
		return m.StartedAt()
	case readingprogress.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ReadingProgressMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case readingprogress.FieldGalleryID:
		return m.OldGalleryID(ctx)
	case readingprogress.FieldToken:
		return m.OldToken(ctx)
	case readingprogress.FieldCurrentPage:
		return m.OldCurrentPage(ctx)
	case readingprogress.FieldProgress:
		return m.OldProgress(ctx)
	case readingprogress.FieldCompleted:
		return m.OldCompleted(ctx)
	case readingprogress.FieldTitle:
		return m.OldTitle(ctx)
	case readingprogress.FieldTitleJpn:
		return m.OldTitleJpn(ctx)
	case readingprogress.FieldCategory:
		return m.OldCategory(ctx)
	case readingprogress.FieldThumbnail:
		return m.OldThumbnail(ctx)
	case readingprogress.FieldPageCount:
		return m.OldPageCount(ctx)
	case readingprogress.FieldStartedAt:
		return m.OldStartedAt(ctx)
	case readingprogress.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown ReadingProgress field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ReadingProgressMutation) SetField(name string, value ent.Value) error {
	switch name {
	case readingprogress.FieldGalleryID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGalleryID(v)
		return nil
	case readingprogress.FieldToken:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetToken(v)
		return nil
	case readingprogress.FieldCurrentPage:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCurrentPage(v)
		return nil
	case readingprogress.FieldProgress:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetProgress(v)
		return nil
	case readingprogress.FieldCompleted:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCompleted(v)
		return nil
	case readingprogress.FieldTitle:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTitle(v)
		return nil
	case readingprogress.FieldTitleJpn:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTitleJpn(v)
		return nil
	case readingprogress.FieldCategory:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCategory(v)
		return nil
	case readingprogress.FieldThumbnail:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetThumbnail(v)
		return nil
	case readingprogress.FieldPageCount:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPageCount(v)
		return nil
	case readingprogress.FieldStartedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStartedAt(v)
		return nil
	case readingprogress.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown ReadingProgress field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ReadingProgressMutation) AddedFields() []string {
	var fields []string
	if m.addgallery_id != nil {
		fields = append(fields, readingprogress.FieldGalleryID)
	}
	if m.addcurrent_page != nil {
		fields = append(fields, readingprogress.FieldCurrentPage)
	}
	if m.addprogress != nil {
		fields = append(fields, readingprogress.FieldProgress)
	}
	if m.addpage_count != nil {
		fields = append(fields, readingprogress.FieldPageCount)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ReadingProgressMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case readingprogress.FieldGalleryID:
		return m.AddedGalleryID()
	case readingprogress.FieldCurrentPage:
		return m.AddedCurrentPage()
	case readingprogress.FieldProgress:
		return m.AddedProgress()
	case readingprogress.FieldPageCount:
		return m.AddedPageCount()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ReadingProgressMutation) AddField(name string, value ent.Value) error {
	switch name {
	case readingprogress.FieldGalleryID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddGalleryID(v)
		return nil
	case readingprogress.FieldCurrentPage:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCurrentPage(v)
		return nil
	case readingprogress.FieldProgress:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddProgress(v)
		return nil
	case readingprogress.FieldPageCount:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPageCount(v)
		return nil
	}
	return fmt.Errorf("unknown ReadingProgress numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ReadingProgressMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(readingprogress.FieldStartedAt) {
		fields = append(fields, readingprogress.FieldStartedAt)
	}
	if m.FieldCleared(readingprogress.FieldUpdatedAt) {
		fields = append(fields, readingprogress.FieldUpdatedAt)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ReadingProgressMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ReadingProgressMutation) ClearField(name string) error {
	switch name {
	case readingprogress.FieldStartedAt:
		m.ClearStartedAt()
		return nil
	case readingprogress.FieldUpdatedAt:
		m.ClearUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown ReadingProgress nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ReadingProgressMutation) ResetField(name string) error {
	switch name {
	case readingprogress.FieldGalleryID:
		m.ResetGalleryID()
		return nil
	case readingprogress.FieldToken:
		m.ResetToken()
		return nil
	case readingprogress.FieldCurrentPage:
		m.ResetCurrentPage()
		return nil
	case readingprogress.FieldProgress:
		m.ResetProgress()
		return nil
	case readingprogress.FieldCompleted:
		m.ResetCompleted()
		return nil
	case readingprogress.FieldTitle:
		m.ResetTitle()
		return nil
	case readingprogress.FieldTitleJpn:
		m.ResetTitleJpn()
		return nil
	case readingprogress.FieldCategory:
		m.ResetCategory()
		return nil
	case readingprogress.FieldThumbnail:
		m.ResetThumbnail()
		return nil
	case readingprogress.FieldPageCount:
		m.ResetPageCount()
		return nil
	case readingprogress.FieldStartedAt:
		m.ResetStartedAt()
		return nil
	case readingprogress.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown ReadingProgress field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ReadingProgressMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ReadingProgressMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ReadingProgressMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ReadingProgressMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ReadingProgressMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ReadingProgressMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ReadingProgressMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown ReadingProgress unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ReadingProgressMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown ReadingProgress edge %s", name)
}
