// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"manga-reader/internal/ent/predicate"
	"manga-reader/internal/ent/prefilljob"
	"manga-reader/internal/model"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// PrefillJobUpdate is the builder for updating PrefillJob entities.
type PrefillJobUpdate struct {
	config
	hooks    []Hook
	mutation *PrefillJobMutation
}

// Where appends a list predicates to the PrefillJobUpdate builder.
func (_u *PrefillJobUpdate) Where(ps ...predicate.PrefillJob) *PrefillJobUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGalleryID sets the "gallery_id" field.
func (_u *PrefillJobUpdate) SetGalleryID(v int64) *PrefillJobUpdate {
	_u.mutation.ResetGalleryID()
	_u.mutation.SetGalleryID(v)
	return _u
}

// SetNillableGalleryID sets the "gallery_id" field if the given value is not nil.
func (_u *PrefillJobUpdate) SetNillableGalleryID(v *int64) *PrefillJobUpdate {
	if v != nil {
		_u.SetGalleryID(*v)
	}
	return _u
}

// AddGalleryID adds value to the "gallery_id" field.
func (_u *PrefillJobUpdate) AddGalleryID(v int64) *PrefillJobUpdate {
	_u.mutation.AddGalleryID(v)
	return _u
}

// ClearGalleryID clears the value of the "gallery_id" field.
func (_u *PrefillJobUpdate) ClearGalleryID() *PrefillJobUpdate {
	_u.mutation.ClearGalleryID()
	return _u
}

// SetToken sets the "token" field.
func (_u *PrefillJobUpdate) SetToken(v string) *PrefillJobUpdate {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *PrefillJobUpdate) SetNillableToken(v *string) *PrefillJobUpdate {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *PrefillJobUpdate) SetTitle(v string) *PrefillJobUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PrefillJobUpdate) SetNillableTitle(v *string) *PrefillJobUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetUrls sets the "urls" field.
func (_u *PrefillJobUpdate) SetUrls(v []string) *PrefillJobUpdate {
	_u.mutation.SetUrls(v)
	return _u
}

// AppendUrls appends value to the "urls" field.
func (_u *PrefillJobUpdate) AppendUrls(v []string) *PrefillJobUpdate {
	_u.mutation.AppendUrls(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *PrefillJobUpdate) SetStatus(v string) *PrefillJobUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PrefillJobUpdate) SetNillableStatus(v *string) *PrefillJobUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTotal sets the "total" field.
func (_u *PrefillJobUpdate) SetTotal(v int) *PrefillJobUpdate {
	_u.mutation.ResetTotal()
	_u.mutation.SetTotal(v)
	return _u
}

// SetNillableTotal sets the "total" field if the given value is not nil.
func (_u *PrefillJobUpdate) SetNillableTotal(v *int) *PrefillJobUpdate {
	if v != nil {
		_u.SetTotal(*v)
	}
	return _u
}

// AddTotal adds value to the "total" field.
func (_u *PrefillJobUpdate) AddTotal(v int) *PrefillJobUpdate {
	_u.mutation.AddTotal(v)
	return _u
}

// SetFailedCount sets the "failed_count" field.
func (_u *PrefillJobUpdate) SetFailedCount(v int) *PrefillJobUpdate {
	_u.mutation.ResetFailedCount()
	_u.mutation.SetFailedCount(v)
	return _u
}

// SetNillableFailedCount sets the "failed_count" field if the given value is not nil.
func (_u *PrefillJobUpdate) SetNillableFailedCount(v *int) *PrefillJobUpdate {
	if v != nil {
		_u.SetFailedCount(*v)
	}
	return _u
}

// AddFailedCount adds value to the "failed_count" field.
func (_u *PrefillJobUpdate) AddFailedCount(v int) *PrefillJobUpdate {
	_u.mutation.AddFailedCount(v)
	return _u
}

// SetErrors sets the "errors" field.
func (_u *PrefillJobUpdate) SetErrors(v []model.PrefillItemError) *PrefillJobUpdate {
	_u.mutation.SetErrors(v)
	return _u
}

// AppendErrors appends value to the "errors" field.
func (_u *PrefillJobUpdate) AppendErrors(v []model.PrefillItemError) *PrefillJobUpdate {
	_u.mutation.AppendErrors(v)
	return _u
}

// ClearErrors clears the value of the "errors" field.
func (_u *PrefillJobUpdate) ClearErrors() *PrefillJobUpdate {
	_u.mutation.ClearErrors()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PrefillJobUpdate) SetUpdatedAt(v time.Time) *PrefillJobUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *PrefillJobUpdate) SetFinishedAt(v time.Time) *PrefillJobUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *PrefillJobUpdate) SetNillableFinishedAt(v *time.Time) *PrefillJobUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *PrefillJobUpdate) ClearFinishedAt() *PrefillJobUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// Mutation returns the PrefillJobMutation object of the builder.
func (_u *PrefillJobUpdate) Mutation() *PrefillJobMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PrefillJobUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PrefillJobUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PrefillJobUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PrefillJobUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PrefillJobUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := prefilljob.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *PrefillJobUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(prefilljob.Table, prefilljob.Columns, sqlgraph.NewFieldSpec(prefilljob.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GalleryID(); ok {
		_spec.SetField(prefilljob.FieldGalleryID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGalleryID(); ok {
		_spec.AddField(prefilljob.FieldGalleryID, field.TypeInt64, value)
	}
	if _u.mutation.GalleryIDCleared() {
		_spec.ClearField(prefilljob.FieldGalleryID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(prefilljob.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(prefilljob.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Urls(); ok {
		_spec.SetField(prefilljob.FieldUrls, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedUrls(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, prefilljob.FieldUrls, value)
		})
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(prefilljob.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Total(); ok {
		_spec.SetField(prefilljob.FieldTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotal(); ok {
		_spec.AddField(prefilljob.FieldTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FailedCount(); ok {
		_spec.SetField(prefilljob.FieldFailedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFailedCount(); ok {
		_spec.AddField(prefilljob.FieldFailedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Errors(); ok {
		_spec.SetField(prefilljob.FieldErrors, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedErrors(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, prefilljob.FieldErrors, value)
		})
	}
	if _u.mutation.ErrorsCleared() {
		_spec.ClearField(prefilljob.FieldErrors, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(prefilljob.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(prefilljob.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(prefilljob.FieldFinishedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{prefilljob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PrefillJobUpdateOne is the builder for updating a single PrefillJob entity.
type PrefillJobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PrefillJobMutation
}

// SetGalleryID sets the "gallery_id" field.
func (_u *PrefillJobUpdateOne) SetGalleryID(v int64) *PrefillJobUpdateOne {
	_u.mutation.ResetGalleryID()
	_u.mutation.SetGalleryID(v)
	return _u
}

// SetNillableGalleryID sets the "gallery_id" field if the given value is not nil.
func (_u *PrefillJobUpdateOne) SetNillableGalleryID(v *int64) *PrefillJobUpdateOne {
	if v != nil {
		_u.SetGalleryID(*v)
	}
	return _u
}

// AddGalleryID adds value to the "gallery_id" field.
func (_u *PrefillJobUpdateOne) AddGalleryID(v int64) *PrefillJobUpdateOne {
	_u.mutation.AddGalleryID(v)
	return _u
}

// ClearGalleryID clears the value of the "gallery_id" field.
func (_u *PrefillJobUpdateOne) ClearGalleryID() *PrefillJobUpdateOne {
	_u.mutation.ClearGalleryID()
	return _u
}

// SetToken sets the "token" field.
func (_u *PrefillJobUpdateOne) SetToken(v string) *PrefillJobUpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *PrefillJobUpdateOne) SetNillableToken(v *string) *PrefillJobUpdateOne {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *PrefillJobUpdateOne) SetTitle(v string) *PrefillJobUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PrefillJobUpdateOne) SetNillableTitle(v *string) *PrefillJobUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetUrls sets the "urls" field.
func (_u *PrefillJobUpdateOne) SetUrls(v []string) *PrefillJobUpdateOne {
	_u.mutation.SetUrls(v)
	return _u
}

// AppendUrls appends value to the "urls" field.
func (_u *PrefillJobUpdateOne) AppendUrls(v []string) *PrefillJobUpdateOne {
	_u.mutation.AppendUrls(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *PrefillJobUpdateOne) SetStatus(v string) *PrefillJobUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PrefillJobUpdateOne) SetNillableStatus(v *string) *PrefillJobUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTotal sets the "total" field.
func (_u *PrefillJobUpdateOne) SetTotal(v int) *PrefillJobUpdateOne {
	_u.mutation.ResetTotal()
	_u.mutation.SetTotal(v)
	return _u
}

// SetNillableTotal sets the "total" field if the given value is not nil.
func (_u *PrefillJobUpdateOne) SetNillableTotal(v *int) *PrefillJobUpdateOne {
	if v != nil {
		_u.SetTotal(*v)
	}
	return _u
}

// AddTotal adds value to the "total" field.
func (_u *PrefillJobUpdateOne) AddTotal(v int) *PrefillJobUpdateOne {
	_u.mutation.AddTotal(v)
	return _u
}

// SetFailedCount sets the "failed_count" field.
func (_u *PrefillJobUpdateOne) SetFailedCount(v int) *PrefillJobUpdateOne {
	_u.mutation.ResetFailedCount()
	_u.mutation.SetFailedCount(v)
	return _u
}

// SetNillableFailedCount sets the "failed_count" field if the given value is not nil.
func (_u *PrefillJobUpdateOne) SetNillableFailedCount(v *int) *PrefillJobUpdateOne {
	if v != nil {
		_u.SetFailedCount(*v)
	}
	return _u
}

// AddFailedCount adds value to the "failed_count" field.
func (_u *PrefillJobUpdateOne) AddFailedCount(v int) *PrefillJobUpdateOne {
	_u.mutation.AddFailedCount(v)
	return _u
}

// SetErrors sets the "errors" field.
func (_u *PrefillJobUpdateOne) SetErrors(v []model.PrefillItemError) *PrefillJobUpdateOne {
	_u.mutation.SetErrors(v)
	return _u
}

// AppendErrors appends value to the "errors" field.
func (_u *PrefillJobUpdateOne) AppendErrors(v []model.PrefillItemError) *PrefillJobUpdateOne {
	_u.mutation.AppendErrors(v)
	return _u
}

// ClearErrors clears the value of the "errors" field.
func (_u *PrefillJobUpdateOne) ClearErrors() *PrefillJobUpdateOne {
	_u.mutation.ClearErrors()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PrefillJobUpdateOne) SetUpdatedAt(v time.Time) *PrefillJobUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *PrefillJobUpdateOne) SetFinishedAt(v time.Time) *PrefillJobUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *PrefillJobUpdateOne) SetNillableFinishedAt(v *time.Time) *PrefillJobUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *PrefillJobUpdateOne) ClearFinishedAt() *PrefillJobUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// Mutation returns the PrefillJobMutation object of the builder.
func (_u *PrefillJobUpdateOne) Mutation() *PrefillJobMutation {
	return _u.mutation
}

// Where appends a list predicates to the PrefillJobUpdate builder.
func (_u *PrefillJobUpdateOne) Where(ps ...predicate.PrefillJob) *PrefillJobUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PrefillJobUpdateOne) Select(field string, fields ...string) *PrefillJobUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PrefillJob entity.
func (_u *PrefillJobUpdateOne) Save(ctx context.Context) (*PrefillJob, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PrefillJobUpdateOne) SaveX(ctx context.Context) *PrefillJob {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PrefillJobUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PrefillJobUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PrefillJobUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := prefilljob.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *PrefillJobUpdateOne) sqlSave(ctx context.Context) (_node *PrefillJob, err error) {
	_spec := sqlgraph.NewUpdateSpec(prefilljob.Table, prefilljob.Columns, sqlgraph.NewFieldSpec(prefilljob.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PrefillJob.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, prefilljob.FieldID)
		for _, f := range fields {
			if !prefilljob.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != prefilljob.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GalleryID(); ok {
		_spec.SetField(prefilljob.FieldGalleryID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGalleryID(); ok {
		_spec.AddField(prefilljob.FieldGalleryID, field.TypeInt64, value)
	}
	if _u.mutation.GalleryIDCleared() {
		_spec.ClearField(prefilljob.FieldGalleryID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(prefilljob.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(prefilljob.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Urls(); ok {
		_spec.SetField(prefilljob.FieldUrls, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedUrls(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, prefilljob.FieldUrls, value)
		})
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(prefilljob.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Total(); ok {
		_spec.SetField(prefilljob.FieldTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotal(); ok {
		_spec.AddField(prefilljob.FieldTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FailedCount(); ok {
		_spec.SetField(prefilljob.FieldFailedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFailedCount(); ok {
		_spec.AddField(prefilljob.FieldFailedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Errors(); ok {
		_spec.SetField(prefilljob.FieldErrors, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedErrors(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, prefilljob.FieldErrors, value)
		})
	}
	if _u.mutation.ErrorsCleared() {
		_spec.ClearField(prefilljob.FieldErrors, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(prefilljob.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(prefilljob.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(prefilljob.FieldFinishedAt, field.TypeTime)
	}
	_node = &PrefillJob{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{prefilljob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
