// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"manga-reader/internal/ent/prefilljob"
	"manga-reader/internal/model"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// PrefillJob is the model entity for the PrefillJob schema.
type PrefillJob struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// GalleryID holds the value of the "gallery_id" field.
	GalleryID *int64 `json:"gallery_id,omitempty"`
	// GalleryToken holds the value of the "gallery_token" field.
	GalleryToken string `json:"gallery_token,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Urls holds the value of the "urls" field.
	Urls []string `json:"urls,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// FailedCount holds the value of the "failed_count" field.
	FailedCount int `json:"failed_count,omitempty"`
	// Errors holds the value of the "errors" field.
	Errors []model.PrefillItemError `json:"errors,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// FinishedAt holds the value of the "finished_at" field.
	FinishedAt   *time.Time `json:"finished_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PrefillJob) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case prefilljob.FieldUrls, prefilljob.FieldErrors:
			values[i] = new([]byte)
		case prefilljob.FieldID, prefilljob.FieldGalleryID, prefilljob.FieldFailedCount:
			values[i] = new(sql.NullInt64)
		case prefilljob.FieldGalleryToken, prefilljob.FieldTitle, prefilljob.FieldStatus:
			values[i] = new(sql.NullString)
		case prefilljob.FieldCreatedAt, prefilljob.FieldUpdatedAt, prefilljob.FieldFinishedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PrefillJob fields.
func (_m *PrefillJob) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case prefilljob.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case prefilljob.FieldGalleryID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field gallery_id", values[i])
			} else if value.Valid {
				_m.GalleryID = new(int64)
				*_m.GalleryID = value.Int64
			}
		case prefilljob.FieldGalleryToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field gallery_token", values[i])
			} else if value.Valid {
				_m.GalleryToken = value.String
			}
		case prefilljob.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case prefilljob.FieldUrls:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field urls", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Urls); err != nil {
					return fmt.Errorf("unmarshal field urls: %w", err)
				}
			}
		case prefilljob.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case prefilljob.FieldFailedCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field failed_count", values[i])
			} else if value.Valid {
				_m.FailedCount = int(value.Int64)
			}
		case prefilljob.FieldErrors:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field errors", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Errors); err != nil {
					return fmt.Errorf("unmarshal field errors: %w", err)
				}
			}
		case prefilljob.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case prefilljob.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case prefilljob.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PrefillJob.
// This includes values selected through modifiers, order, etc.
func (_m *PrefillJob) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PrefillJob.
// Note that you need to call PrefillJob.Unwrap() before calling this method if this PrefillJob
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PrefillJob) Update() *PrefillJobUpdateOne {
	return NewPrefillJobClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PrefillJob entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PrefillJob) Unwrap() *PrefillJob {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PrefillJob is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PrefillJob) String() string {
	var builder strings.Builder
	builder.WriteString("PrefillJob(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.GalleryID; v != nil {
		builder.WriteString("gallery_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("gallery_token=")
	builder.WriteString(_m.GalleryToken)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("urls=")
	builder.WriteString(fmt.Sprintf("%v", _m.Urls))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("failed_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.FailedCount))
	builder.WriteString(", ")
	builder.WriteString("errors=")
	builder.WriteString(fmt.Sprintf("%v", _m.Errors))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// PrefillJobs is a parsable slice of PrefillJob.
type PrefillJobs []*PrefillJob
