// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"manga-reader/internal/ent/predicate"
	"manga-reader/internal/ent/prefilljob"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PrefillJobDelete is the builder for deleting a PrefillJob entity.
type PrefillJobDelete struct {
	config
	hooks    []Hook
	mutation *PrefillJobMutation
}

// Where appends a list predicates to the PrefillJobDelete builder.
func (_d *PrefillJobDelete) Where(ps ...predicate.PrefillJob) *PrefillJobDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PrefillJobDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PrefillJobDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PrefillJobDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(prefilljob.Table, sqlgraph.NewFieldSpec(prefilljob.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PrefillJobDeleteOne is the builder for deleting a single PrefillJob entity.
type PrefillJobDeleteOne struct {
	_d *PrefillJobDelete
}

// Where appends a list predicates to the PrefillJobDelete builder.
func (_d *PrefillJobDeleteOne) Where(ps ...predicate.PrefillJob) *PrefillJobDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PrefillJobDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{prefilljob.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PrefillJobDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
