// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"manga-reader/internal/ent/prefilljob"
	"manga-reader/internal/model"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PrefillJobCreate is the builder for creating a PrefillJob entity.
type PrefillJobCreate struct {
	config
	mutation *PrefillJobMutation
	hooks    []Hook
}

// SetGalleryID sets the "gallery_id" field.
func (_c *PrefillJobCreate) SetGalleryID(v int64) *PrefillJobCreate {
	_c.mutation.SetGalleryID(v)
	return _c
}

// SetNillableGalleryID sets the "gallery_id" field if the given value is not nil.
func (_c *PrefillJobCreate) SetNillableGalleryID(v *int64) *PrefillJobCreate {
	if v != nil {
		_c.SetGalleryID(*v)
	}
	return _c
}

// SetGalleryToken sets the "gallery_token" field.
func (_c *PrefillJobCreate) SetGalleryToken(v string) *PrefillJobCreate {
	_c.mutation.SetGalleryToken(v)
	return _c
}

// SetNillableGalleryToken sets the "gallery_token" field if the given value is not nil.
func (_c *PrefillJobCreate) SetNillableGalleryToken(v *string) *PrefillJobCreate {
	if v != nil {
		_c.SetGalleryToken(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *PrefillJobCreate) SetTitle(v string) *PrefillJobCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *PrefillJobCreate) SetNillableTitle(v *string) *PrefillJobCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetUrls sets the "urls" field.
func (_c *PrefillJobCreate) SetUrls(v []string) *PrefillJobCreate {
	_c.mutation.SetUrls(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *PrefillJobCreate) SetStatus(v string) *PrefillJobCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PrefillJobCreate) SetNillableStatus(v *string) *PrefillJobCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetFailedCount sets the "failed_count" field.
func (_c *PrefillJobCreate) SetFailedCount(v int) *PrefillJobCreate {
	_c.mutation.SetFailedCount(v)
	return _c
}

// SetNillableFailedCount sets the "failed_count" field if the given value is not nil.
func (_c *PrefillJobCreate) SetNillableFailedCount(v *int) *PrefillJobCreate {
	if v != nil {
		_c.SetFailedCount(*v)
	}
	return _c
}

// SetErrors sets the "errors" field.
func (_c *PrefillJobCreate) SetErrors(v []model.PrefillItemError) *PrefillJobCreate {
	_c.mutation.SetErrors(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PrefillJobCreate) SetCreatedAt(v time.Time) *PrefillJobCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PrefillJobCreate) SetNillableCreatedAt(v *time.Time) *PrefillJobCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PrefillJobCreate) SetUpdatedAt(v time.Time) *PrefillJobCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PrefillJobCreate) SetNillableUpdatedAt(v *time.Time) *PrefillJobCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *PrefillJobCreate) SetFinishedAt(v time.Time) *PrefillJobCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *PrefillJobCreate) SetNillableFinishedAt(v *time.Time) *PrefillJobCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// Mutation returns the PrefillJobMutation object of the builder.
func (_c *PrefillJobCreate) Mutation() *PrefillJobMutation {
	return _c.mutation
}

// Save creates the PrefillJob in the database.
func (_c *PrefillJobCreate) Save(ctx context.Context) (*PrefillJob, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PrefillJobCreate) SaveX(ctx context.Context) *PrefillJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PrefillJobCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PrefillJobCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PrefillJobCreate) defaults() {
	if _, ok := _c.mutation.GalleryToken(); !ok {
		v := prefilljob.DefaultGalleryToken
		_c.mutation.SetGalleryToken(v)
	}
	if _, ok := _c.mutation.Title(); !ok {
		v := prefilljob.DefaultTitle
		_c.mutation.SetTitle(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := prefilljob.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.FailedCount(); !ok {
		v := prefilljob.DefaultFailedCount
		_c.mutation.SetFailedCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := prefilljob.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := prefilljob.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PrefillJobCreate) check() error {
	if _, ok := _c.mutation.GalleryToken(); !ok {
		return &ValidationError{Name: "gallery_token", err: errors.New(`ent: missing required field "PrefillJob.gallery_token"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "PrefillJob.title"`)}
	}
	if _, ok := _c.mutation.Urls(); !ok {
		return &ValidationError{Name: "urls", err: errors.New(`ent: missing required field "PrefillJob.urls"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "PrefillJob.status"`)}
	}
	if _, ok := _c.mutation.FailedCount(); !ok {
		return &ValidationError{Name: "failed_count", err: errors.New(`ent: missing required field "PrefillJob.failed_count"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PrefillJob.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PrefillJob.updated_at"`)}
	}
	return nil
}

func (_c *PrefillJobCreate) sqlSave(ctx context.Context) (*PrefillJob, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PrefillJobCreate) createSpec() (*PrefillJob, *sqlgraph.CreateSpec) {
	var (
		_node = &PrefillJob{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(prefilljob.Table, sqlgraph.NewFieldSpec(prefilljob.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.GalleryID(); ok {
		_spec.SetField(prefilljob.FieldGalleryID, field.TypeInt64, value)
		_node.GalleryID = &value
	}
	if value, ok := _c.mutation.GalleryToken(); ok {
		_spec.SetField(prefilljob.FieldGalleryToken, field.TypeString, value)
		_node.GalleryToken = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(prefilljob.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Urls(); ok {
		_spec.SetField(prefilljob.FieldUrls, field.TypeJSON, value)
		_node.Urls = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(prefilljob.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.FailedCount(); ok {
		_spec.SetField(prefilljob.FieldFailedCount, field.TypeInt, value)
		_node.FailedCount = value
	}
	if value, ok := _c.mutation.Errors(); ok {
		_spec.SetField(prefilljob.FieldErrors, field.TypeJSON, value)
		_node.Errors = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(prefilljob.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(prefilljob.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(prefilljob.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	return _node, _spec
}

// PrefillJobCreateBulk is the builder for creating many PrefillJob entities in bulk.
type PrefillJobCreateBulk struct {
	config
	err      error
	builders []*PrefillJobCreate
}

// Save creates the PrefillJob entities in the database.
func (_c *PrefillJobCreateBulk) Save(ctx context.Context) ([]*PrefillJob, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PrefillJob, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PrefillJobMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PrefillJobCreateBulk) SaveX(ctx context.Context) []*PrefillJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PrefillJobCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PrefillJobCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
