// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"manga-reader/internal/ent/predicate"
	"manga-reader/internal/ent/readingprogress"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ReadingProgressUpdate is the builder for updating ReadingProgress entities.
type ReadingProgressUpdate struct {
	config
	hooks    []Hook
	mutation *ReadingProgressMutation
}

// Where appends a list predicates to the ReadingProgressUpdate builder.
func (_u *ReadingProgressUpdate) Where(ps ...predicate.ReadingProgress) *ReadingProgressUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGalleryID sets the "gallery_id" field.
func (_u *ReadingProgressUpdate) SetGalleryID(v int64) *ReadingProgressUpdate {
	_u.mutation.ResetGalleryID()
	_u.mutation.SetGalleryID(v)
	return _u
}

// SetNillableGalleryID sets the "gallery_id" field if the given value is not nil.
func (_u *ReadingProgressUpdate) SetNillableGalleryID(v *int64) *ReadingProgressUpdate {
	if v != nil {
		_u.SetGalleryID(*v)
	}
	return _u
}

// AddGalleryID adds value to the "gallery_id" field.
func (_u *ReadingProgressUpdate) AddGalleryID(v int64) *ReadingProgressUpdate {
	_u.mutation.AddGalleryID(v)
	return _u
}

// SetToken sets the "token" field.
func (_u *ReadingProgressUpdate) SetToken(v string) *ReadingProgressUpdate {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *ReadingProgressUpdate) SetNillableToken(v *string) *ReadingProgressUpdate {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetCurrentPage sets the "current_page" field.
func (_u *ReadingProgressUpdate) SetCurrentPage(v int) *ReadingProgressUpdate {
	_u.mutation.ResetCurrentPage()
	_u.mutation.SetCurrentPage(v)
	return _u
}

// SetNillableCurrentPage sets the "current_page" field if the given value is not nil.
func (_u *ReadingProgressUpdate) SetNillableCurrentPage(v *int) *ReadingProgressUpdate {
	if v != nil {
		_u.SetCurrentPage(*v)
	}
	return _u
}

// AddCurrentPage adds value to the "current_page" field.
func (_u *ReadingProgressUpdate) AddCurrentPage(v int) *ReadingProgressUpdate {
	_u.mutation.AddCurrentPage(v)
	return _u
}

// SetProgress sets the "progress" field.
func (_u *ReadingProgressUpdate) SetProgress(v float64) *ReadingProgressUpdate {
	_u.mutation.ResetProgress()
	_u.mutation.SetProgress(v)
	return _u
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (_u *ReadingProgressUpdate) SetNillableProgress(v *float64) *ReadingProgressUpdate {
	if v != nil {
		_u.SetProgress(*v)
	}
	return _u
}

// AddProgress adds value to the "progress" field.
func (_u *ReadingProgressUpdate) AddProgress(v float64) *ReadingProgressUpdate {
	_u.mutation.AddProgress(v)
	return _u
}

// SetCompleted sets the "completed" field.
func (_u *ReadingProgressUpdate) SetCompleted(v bool) *ReadingProgressUpdate {
	_u.mutation.SetCompleted(v)
	return _u
}

// SetNillableCompleted sets the "completed" field if the given value is not nil.
func (_u *ReadingProgressUpdate) SetNillableCompleted(v *bool) *ReadingProgressUpdate {
	if v != nil {
		_u.SetCompleted(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *ReadingProgressUpdate) SetTitle(v string) *ReadingProgressUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ReadingProgressUpdate) SetNillableTitle(v *string) *ReadingProgressUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetTitleJpn sets the "title_jpn" field.
func (_u *ReadingProgressUpdate) SetTitleJpn(v string) *ReadingProgressUpdate {
	_u.mutation.SetTitleJpn(v)
	return _u
}

// SetNillableTitleJpn sets the "title_jpn" field if the given value is not nil.
func (_u *ReadingProgressUpdate) SetNillableTitleJpn(v *string) *ReadingProgressUpdate {
	if v != nil {
		_u.SetTitleJpn(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *ReadingProgressUpdate) SetCategory(v string) *ReadingProgressUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *ReadingProgressUpdate) SetNillableCategory(v *string) *ReadingProgressUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetThumbnail sets the "thumbnail" field.
func (_u *ReadingProgressUpdate) SetThumbnail(v string) *ReadingProgressUpdate {
	_u.mutation.SetThumbnail(v)
	return _u
}

// SetNillableThumbnail sets the "thumbnail" field if the given value is not nil.
func (_u *ReadingProgressUpdate) SetNillableThumbnail(v *string) *ReadingProgressUpdate {
	if v != nil {
		_u.SetThumbnail(*v)
	}
	return _u
}

// SetPageCount sets the "page_count" field.
func (_u *ReadingProgressUpdate) SetPageCount(v int) *ReadingProgressUpdate {
	_u.mutation.ResetPageCount()
	_u.mutation.SetPageCount(v)
	return _u
}

// SetNillablePageCount sets the "page_count" field if the given value is not nil.
func (_u *ReadingProgressUpdate) SetNillablePageCount(v *int) *ReadingProgressUpdate {
	if v != nil {
		_u.SetPageCount(*v)
	}
	return _u
}

// AddPageCount adds value to the "page_count" field.
func (_u *ReadingProgressUpdate) AddPageCount(v int) *ReadingProgressUpdate {
	_u.mutation.AddPageCount(v)
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *ReadingProgressUpdate) SetStartedAt(v time.Time) *ReadingProgressUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *ReadingProgressUpdate) SetNillableStartedAt(v *time.Time) *ReadingProgressUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *ReadingProgressUpdate) ClearStartedAt() *ReadingProgressUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ReadingProgressUpdate) SetUpdatedAt(v time.Time) *ReadingProgressUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ReadingProgressUpdate) ClearUpdatedAt() *ReadingProgressUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// Mutation returns the ReadingProgressMutation object of the builder.
func (_u *ReadingProgressUpdate) Mutation() *ReadingProgressMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReadingProgressUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReadingProgressUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReadingProgressUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReadingProgressUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ReadingProgressUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := readingprogress.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReadingProgressUpdate) check() error {
	if v, ok := _u.mutation.CurrentPage(); ok {
		if err := readingprogress.CurrentPageValidator(v); err != nil {
			return &ValidationError{Name: "current_page", err: fmt.Errorf(`ent: validator failed for field "ReadingProgress.current_page": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Progress(); ok {
		if err := readingprogress.ProgressValidator(v); err != nil {
			return &ValidationError{Name: "progress", err: fmt.Errorf(`ent: validator failed for field "ReadingProgress.progress": %w`, err)}
		}
	}
	return nil
}

func (_u *ReadingProgressUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(readingprogress.Table, readingprogress.Columns, sqlgraph.NewFieldSpec(readingprogress.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GalleryID(); ok {
		_spec.SetField(readingprogress.FieldGalleryID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGalleryID(); ok {
		_spec.AddField(readingprogress.FieldGalleryID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(readingprogress.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.CurrentPage(); ok {
		_spec.SetField(readingprogress.FieldCurrentPage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCurrentPage(); ok {
		_spec.AddField(readingprogress.FieldCurrentPage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Progress(); ok {
		_spec.SetField(readingprogress.FieldProgress, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedProgress(); ok {
		_spec.AddField(readingprogress.FieldProgress, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Completed(); ok {
		_spec.SetField(readingprogress.FieldCompleted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(readingprogress.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.TitleJpn(); ok {
		_spec.SetField(readingprogress.FieldTitleJpn, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(readingprogress.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Thumbnail(); ok {
		_spec.SetField(readingprogress.FieldThumbnail, field.TypeString, value)
	}
	if value, ok := _u.mutation.PageCount(); ok {
		_spec.SetField(readingprogress.FieldPageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPageCount(); ok {
		_spec.AddField(readingprogress.FieldPageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(readingprogress.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(readingprogress.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(readingprogress.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(readingprogress.FieldUpdatedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{readingprogress.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReadingProgressUpdateOne is the builder for updating a single ReadingProgress entity.
type ReadingProgressUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReadingProgressMutation
}

// SetGalleryID sets the "gallery_id" field.
func (_u *ReadingProgressUpdateOne) SetGalleryID(v int64) *ReadingProgressUpdateOne {
	_u.mutation.ResetGalleryID()
	_u.mutation.SetGalleryID(v)
	return _u
}

// SetNillableGalleryID sets the "gallery_id" field if the given value is not nil.
func (_u *ReadingProgressUpdateOne) SetNillableGalleryID(v *int64) *ReadingProgressUpdateOne {
	if v != nil {
		_u.SetGalleryID(*v)
	}
	return _u
}

// AddGalleryID adds value to the "gallery_id" field.
func (_u *ReadingProgressUpdateOne) AddGalleryID(v int64) *ReadingProgressUpdateOne {
	_u.mutation.AddGalleryID(v)
	return _u
}

// SetToken sets the "token" field.
func (_u *ReadingProgressUpdateOne) SetToken(v string) *ReadingProgressUpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *ReadingProgressUpdateOne) SetNillableToken(v *string) *ReadingProgressUpdateOne {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetCurrentPage sets the "current_page" field.
func (_u *ReadingProgressUpdateOne) SetCurrentPage(v int) *ReadingProgressUpdateOne {
	_u.mutation.ResetCurrentPage()
	_u.mutation.SetCurrentPage(v)
	return _u
}

// SetNillableCurrentPage sets the "current_page" field if the given value is not nil.
func (_u *ReadingProgressUpdateOne) SetNillableCurrentPage(v *int) *ReadingProgressUpdateOne {
	if v != nil {
		_u.SetCurrentPage(*v)
	}
	return _u
}

// AddCurrentPage adds value to the "current_page" field.
func (_u *ReadingProgressUpdateOne) AddCurrentPage(v int) *ReadingProgressUpdateOne {
	_u.mutation.AddCurrentPage(v)
	return _u
}

// SetProgress sets the "progress" field.
func (_u *ReadingProgressUpdateOne) SetProgress(v float64) *ReadingProgressUpdateOne {
	_u.mutation.ResetProgress()
	_u.mutation.SetProgress(v)
	return _u
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (_u *ReadingProgressUpdateOne) SetNillableProgress(v *float64) *ReadingProgressUpdateOne {
	if v != nil {
		_u.SetProgress(*v)
	}
	return _u
}

// AddProgress adds value to the "progress" field.
func (_u *ReadingProgressUpdateOne) AddProgress(v float64) *ReadingProgressUpdateOne {
	_u.mutation.AddProgress(v)
	return _u
}

// SetCompleted sets the "completed" field.
func (_u *ReadingProgressUpdateOne) SetCompleted(v bool) *ReadingProgressUpdateOne {
	_u.mutation.SetCompleted(v)
	return _u
}

// SetNillableCompleted sets the "completed" field if the given value is not nil.
func (_u *ReadingProgressUpdateOne) SetNillableCompleted(v *bool) *ReadingProgressUpdateOne {
	if v != nil {
		_u.SetCompleted(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *ReadingProgressUpdateOne) SetTitle(v string) *ReadingProgressUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ReadingProgressUpdateOne) SetNillableTitle(v *string) *ReadingProgressUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetTitleJpn sets the "title_jpn" field.
func (_u *ReadingProgressUpdateOne) SetTitleJpn(v string) *ReadingProgressUpdateOne {
	_u.mutation.SetTitleJpn(v)
	return _u
}

// SetNillableTitleJpn sets the "title_jpn" field if the given value is not nil.
func (_u *ReadingProgressUpdateOne) SetNillableTitleJpn(v *string) *ReadingProgressUpdateOne {
	if v != nil {
		_u.SetTitleJpn(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *ReadingProgressUpdateOne) SetCategory(v string) *ReadingProgressUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *ReadingProgressUpdateOne) SetNillableCategory(v *string) *ReadingProgressUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetThumbnail sets the "thumbnail" field.
func (_u *ReadingProgressUpdateOne) SetThumbnail(v string) *ReadingProgressUpdateOne {
	_u.mutation.SetThumbnail(v)
	return _u
}

// SetNillableThumbnail sets the "thumbnail" field if the given value is not nil.
func (_u *ReadingProgressUpdateOne) SetNillableThumbnail(v *string) *ReadingProgressUpdateOne {
	if v != nil {
		_u.SetThumbnail(*v)
	}
	return _u
}

// SetPageCount sets the "page_count" field.
func (_u *ReadingProgressUpdateOne) SetPageCount(v int) *ReadingProgressUpdateOne {
	_u.mutation.ResetPageCount()
	_u.mutation.SetPageCount(v)
	return _u
}

// SetNillablePageCount sets the "page_count" field if the given value is not nil.
func (_u *ReadingProgressUpdateOne) SetNillablePageCount(v *int) *ReadingProgressUpdateOne {
	if v != nil {
		_u.SetPageCount(*v)
	}
	return _u
}

// AddPageCount adds value to the "page_count" field.
func (_u *ReadingProgressUpdateOne) AddPageCount(v int) *ReadingProgressUpdateOne {
	_u.mutation.AddPageCount(v)
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *ReadingProgressUpdateOne) SetStartedAt(v time.Time) *ReadingProgressUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *ReadingProgressUpdateOne) SetNillableStartedAt(v *time.Time) *ReadingProgressUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *ReadingProgressUpdateOne) ClearStartedAt() *ReadingProgressUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ReadingProgressUpdateOne) SetUpdatedAt(v time.Time) *ReadingProgressUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ReadingProgressUpdateOne) ClearUpdatedAt() *ReadingProgressUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// Mutation returns the ReadingProgressMutation object of the builder.
func (_u *ReadingProgressUpdateOne) Mutation() *ReadingProgressMutation {
	return _u.mutation
}

// Where appends a list predicates to the ReadingProgressUpdate builder.
func (_u *ReadingProgressUpdateOne) Where(ps ...predicate.ReadingProgress) *ReadingProgressUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReadingProgressUpdateOne) Select(field string, fields ...string) *ReadingProgressUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ReadingProgress entity.
func (_u *ReadingProgressUpdateOne) Save(ctx context.Context) (*ReadingProgress, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReadingProgressUpdateOne) SaveX(ctx context.Context) *ReadingProgress {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReadingProgressUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReadingProgressUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ReadingProgressUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := readingprogress.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReadingProgressUpdateOne) check() error {
	if v, ok := _u.mutation.CurrentPage(); ok {
		if err := readingprogress.CurrentPageValidator(v); err != nil {
			return &ValidationError{Name: "current_page", err: fmt.Errorf(`ent: validator failed for field "ReadingProgress.current_page": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Progress(); ok {
		if err := readingprogress.ProgressValidator(v); err != nil {
			return &ValidationError{Name: "progress", err: fmt.Errorf(`ent: validator failed for field "ReadingProgress.progress": %w`, err)}
		}
	}
	return nil
}

func (_u *ReadingProgressUpdateOne) sqlSave(ctx context.Context) (_node *ReadingProgress, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(readingprogress.Table, readingprogress.Columns, sqlgraph.NewFieldSpec(readingprogress.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ReadingProgress.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, readingprogress.FieldID)
		for _, f := range fields {
			if !readingprogress.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != readingprogress.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GalleryID(); ok {
		_spec.SetField(readingprogress.FieldGalleryID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGalleryID(); ok {
		_spec.AddField(readingprogress.FieldGalleryID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(readingprogress.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.CurrentPage(); ok {
		_spec.SetField(readingprogress.FieldCurrentPage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCurrentPage(); ok {
		_spec.AddField(readingprogress.FieldCurrentPage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Progress(); ok {
		_spec.SetField(readingprogress.FieldProgress, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedProgress(); ok {
		_spec.AddField(readingprogress.FieldProgress, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Completed(); ok {
		_spec.SetField(readingprogress.FieldCompleted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(readingprogress.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.TitleJpn(); ok {
		_spec.SetField(readingprogress.FieldTitleJpn, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(readingprogress.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Thumbnail(); ok {
		_spec.SetField(readingprogress.FieldThumbnail, field.TypeString, value)
	}
	if value, ok := _u.mutation.PageCount(); ok {
		_spec.SetField(readingprogress.FieldPageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPageCount(); ok {
		_spec.AddField(readingprogress.FieldPageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(readingprogress.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(readingprogress.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(readingprogress.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(readingprogress.FieldUpdatedAt, field.TypeTime)
	}
	_node = &ReadingProgress{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{readingprogress.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
