// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"manga-reader/internal/ent/readingprogress"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ReadingProgressCreate is the builder for creating a ReadingProgress entity.
type ReadingProgressCreate struct {
	config
	mutation *ReadingProgressMutation
	hooks    []Hook
}

// SetGalleryID sets the "gallery_id" field.
func (_c *ReadingProgressCreate) SetGalleryID(v int64) *ReadingProgressCreate {
	_c.mutation.SetGalleryID(v)
	return _c
}

// SetToken sets the "token" field.
func (_c *ReadingProgressCreate) SetToken(v string) *ReadingProgressCreate {
	_c.mutation.SetToken(v)
	return _c
}

// SetCurrentPage sets the "current_page" field.
func (_c *ReadingProgressCreate) SetCurrentPage(v int) *ReadingProgressCreate {
	_c.mutation.SetCurrentPage(v)
	return _c
}

// SetNillableCurrentPage sets the "current_page" field if the given value is not nil.
func (_c *ReadingProgressCreate) SetNillableCurrentPage(v *int) *ReadingProgressCreate {
	if v != nil {
		_c.SetCurrentPage(*v)
	}
	return _c
}

// SetProgress sets the "progress" field.
func (_c *ReadingProgressCreate) SetProgress(v float64) *ReadingProgressCreate {
	_c.mutation.SetProgress(v)
	return _c
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (_c *ReadingProgressCreate) SetNillableProgress(v *float64) *ReadingProgressCreate {
	if v != nil {
		_c.SetProgress(*v)
	}
	return _c
}

// SetCompleted sets the "completed" field.
func (_c *ReadingProgressCreate) SetCompleted(v bool) *ReadingProgressCreate {
	_c.mutation.SetCompleted(v)
	return _c
}

// SetNillableCompleted sets the "completed" field if the given value is not nil.
func (_c *ReadingProgressCreate) SetNillableCompleted(v *bool) *ReadingProgressCreate {
	if v != nil {
		_c.SetCompleted(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ReadingProgressCreate) SetCreatedAt(v time.Time) *ReadingProgressCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ReadingProgressCreate) SetNillableCreatedAt(v *time.Time) *ReadingProgressCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ReadingProgressCreate) SetUpdatedAt(v time.Time) *ReadingProgressCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ReadingProgressCreate) SetNillableUpdatedAt(v *time.Time) *ReadingProgressCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the ReadingProgressMutation object of the builder.
func (_c *ReadingProgressCreate) Mutation() *ReadingProgressMutation {
	return _c.mutation
}

// Save creates the ReadingProgress in the database.
func (_c *ReadingProgressCreate) Save(ctx context.Context) (*ReadingProgress, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReadingProgressCreate) SaveX(ctx context.Context) *ReadingProgress {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReadingProgressCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReadingProgressCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ReadingProgressCreate) defaults() {
	if _, ok := _c.mutation.CurrentPage(); !ok {
		v := readingprogress.DefaultCurrentPage
		_c.mutation.SetCurrentPage(v)
	}
	if _, ok := _c.mutation.Progress(); !ok {
		v := readingprogress.DefaultProgress
		_c.mutation.SetProgress(v)
	}
	if _, ok := _c.mutation.Completed(); !ok {
		v := readingprogress.DefaultCompleted
		_c.mutation.SetCompleted(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := readingprogress.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := readingprogress.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReadingProgressCreate) check() error {
	if _, ok := _c.mutation.GalleryID(); !ok {
		return &ValidationError{Name: "gallery_id", err: errors.New(`ent: missing required field "ReadingProgress.gallery_id"`)}
	}
	if _, ok := _c.mutation.Token(); !ok {
		return &ValidationError{Name: "token", err: errors.New(`ent: missing required field "ReadingProgress.token"`)}
	}
	if _, ok := _c.mutation.CurrentPage(); !ok {
		return &ValidationError{Name: "current_page", err: errors.New(`ent: missing required field "ReadingProgress.current_page"`)}
	}
	if v, ok := _c.mutation.CurrentPage(); ok {
		if err := readingprogress.CurrentPageValidator(v); err != nil {
			return &ValidationError{Name: "current_page", err: fmt.Errorf(`ent: validator failed for field "ReadingProgress.current_page": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Progress(); !ok {
		return &ValidationError{Name: "progress", err: errors.New(`ent: missing required field "ReadingProgress.progress"`)}
	}
	if v, ok := _c.mutation.Progress(); ok {
		if err := readingprogress.ProgressValidator(v); err != nil {
			return &ValidationError{Name: "progress", err: fmt.Errorf(`ent: validator failed for field "ReadingProgress.progress": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Completed(); !ok {
		return &ValidationError{Name: "completed", err: errors.New(`ent: missing required field "ReadingProgress.completed"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ReadingProgress.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ReadingProgress.updated_at"`)}
	}
	return nil
}

func (_c *ReadingProgressCreate) sqlSave(ctx context.Context) (*ReadingProgress, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReadingProgressCreate) createSpec() (*ReadingProgress, *sqlgraph.CreateSpec) {
	var (
		_node = &ReadingProgress{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(readingprogress.Table, sqlgraph.NewFieldSpec(readingprogress.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.GalleryID(); ok {
		_spec.SetField(readingprogress.FieldGalleryID, field.TypeInt64, value)
		_node.GalleryID = value
	}
	if value, ok := _c.mutation.Token(); ok {
		_spec.SetField(readingprogress.FieldToken, field.TypeString, value)
		_node.Token = value
	}
	if value, ok := _c.mutation.CurrentPage(); ok {
		_spec.SetField(readingprogress.FieldCurrentPage, field.TypeInt, value)
		_node.CurrentPage = value
	}
	if value, ok := _c.mutation.Progress(); ok {
		_spec.SetField(readingprogress.FieldProgress, field.TypeFloat64, value)
		_node.Progress = value
	}
	if value, ok := _c.mutation.Completed(); ok {
		_spec.SetField(readingprogress.FieldCompleted, field.TypeBool, value)
		_node.Completed = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(readingprogress.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(readingprogress.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ReadingProgressCreateBulk is the builder for creating many ReadingProgress entities in bulk.
type ReadingProgressCreateBulk struct {
	config
	err      error
	builders []*ReadingProgressCreate
}

// Save creates the ReadingProgress entities in the database.
func (_c *ReadingProgressCreateBulk) Save(ctx context.Context) ([]*ReadingProgress, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ReadingProgress, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReadingProgressMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReadingProgressCreateBulk) SaveX(ctx context.Context) []*ReadingProgress {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReadingProgressCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReadingProgressCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
