// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"manga-reader/internal/ent/readingprogress"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ReadingProgress is the model entity for the ReadingProgress schema.
type ReadingProgress struct {
	config `json:"-"`
	// GalleryID holds the value of the "gallery_id" field.
	GalleryID int64 `json:"gallery_id,omitempty"`
	// Token holds the value of the "token" field.
	Token string `json:"token,omitempty"`
	// CurrentPage holds the value of the "current_page" field.
	CurrentPage int `json:"current_page,omitempty"`
	// Progress holds the value of the "progress" field.
	Progress float64 `json:"progress,omitempty"`
	// Completed holds the value of the "completed" field.
	Completed bool `json:"completed,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ReadingProgress) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case readingprogress.FieldCompleted:
			values[i] = new(sql.NullBool)
		case readingprogress.FieldProgress:
			values[i] = new(sql.NullFloat64)
		case readingprogress.FieldGalleryID, readingprogress.FieldCurrentPage:
			values[i] = new(sql.NullInt64)
		case readingprogress.FieldToken:
			values[i] = new(sql.NullString)
		case readingprogress.FieldCreatedAt, readingprogress.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ReadingProgress fields.
func (_m *ReadingProgress) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case readingprogress.FieldGalleryID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field gallery_id", values[i])
			} else if value.Valid {
				_m.GalleryID = value.Int64
			}
		case readingprogress.FieldToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token", values[i])
			} else if value.Valid {
				_m.Token = value.String
			}
		case readingprogress.FieldCurrentPage:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field current_page", values[i])
			} else if value.Valid {
				_m.CurrentPage = int(value.Int64)
			}
		case readingprogress.FieldProgress:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field progress", values[i])
			} else if value.Valid {
				_m.Progress = value.Float64
			}
		case readingprogress.FieldCompleted:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field completed", values[i])
			} else if value.Valid {
				_m.Completed = value.Bool
			}
		case readingprogress.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case readingprogress.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ReadingProgress.
// This includes values selected through modifiers, order, etc.
func (_m *ReadingProgress) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ReadingProgress.
// Note that you need to call ReadingProgress.Unwrap() before calling this method if this ReadingProgress
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ReadingProgress) Update() *ReadingProgressUpdateOne {
	return NewReadingProgressClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ReadingProgress entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ReadingProgress) Unwrap() *ReadingProgress {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ReadingProgress is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ReadingProgress) String() string {
	var builder strings.Builder
	builder.WriteString("ReadingProgress(")
	builder.WriteString("gallery_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GalleryID))
	builder.WriteString(", ")
	builder.WriteString("token=")
	builder.WriteString(_m.Token)
	builder.WriteString(", ")
	builder.WriteString("current_page=")
	builder.WriteString(fmt.Sprintf("%v", _m.CurrentPage))
	builder.WriteString(", ")
	builder.WriteString("progress=")
	builder.WriteString(fmt.Sprintf("%v", _m.Progress))
	builder.WriteString(", ")
	builder.WriteString("completed=")
	builder.WriteString(fmt.Sprintf("%v", _m.Completed))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ReadingProgresses is a parsable slice of ReadingProgress.
type ReadingProgresses []*ReadingProgress
