// Code generated by ent, DO NOT EDIT.

package ent

import (
	"manga-reader/internal/ent/bookshelf"
	"manga-reader/internal/ent/gallerycache"
	"manga-reader/internal/ent/prefilljob"
	"manga-reader/internal/ent/readingprogress"
	"manga-reader/internal/ent/schema"
	"manga-reader/internal/ent/setting"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	bookshelfFields := schema.Bookshelf{}.Fields()
	_ = bookshelfFields
	// bookshelfDescCreatedAt is the schema descriptor for created_at field.
	bookshelfDescCreatedAt := bookshelfFields[2].Descriptor()
	// bookshelf.DefaultCreatedAt holds the default value on creation for the created_at field.
	bookshelf.DefaultCreatedAt = bookshelfDescCreatedAt.Default.(func() time.Time)
	// bookshelfDescUpdatedAt is the schema descriptor for updated_at field.
	bookshelfDescUpdatedAt := bookshelfFields[3].Descriptor()
	// bookshelf.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	bookshelf.DefaultUpdatedAt = bookshelfDescUpdatedAt.Default.(func() time.Time)
	// bookshelf.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	bookshelf.UpdateDefaultUpdatedAt = bookshelfDescUpdatedAt.UpdateDefault.(func() time.Time)
	gallerycacheFields := schema.GalleryCache{}.Fields()
	_ = gallerycacheFields
	// gallerycacheDescCreatedAt is the schema descriptor for created_at field.
	gallerycacheDescCreatedAt := gallerycacheFields[2].Descriptor()
	// gallerycache.DefaultCreatedAt holds the default value on creation for the created_at field.
	gallerycache.DefaultCreatedAt = gallerycacheDescCreatedAt.Default.(func() time.Time)
	// gallerycacheDescTitle is the schema descriptor for title field.
	gallerycacheDescTitle := gallerycacheFields[3].Descriptor()
	// gallerycache.DefaultTitle holds the default value on creation for the title field.
	gallerycache.DefaultTitle = gallerycacheDescTitle.Default.(string)
	// gallerycacheDescTitleJpn is the schema descriptor for title_jpn field.
	gallerycacheDescTitleJpn := gallerycacheFields[4].Descriptor()
	// gallerycache.DefaultTitleJpn holds the default value on creation for the title_jpn field.
	gallerycache.DefaultTitleJpn = gallerycacheDescTitleJpn.Default.(string)
	// gallerycacheDescCategory is the schema descriptor for category field.
	gallerycacheDescCategory := gallerycacheFields[5].Descriptor()
	// gallerycache.DefaultCategory holds the default value on creation for the category field.
	gallerycache.DefaultCategory = gallerycacheDescCategory.Default.(string)
	// gallerycacheDescThumbnail is the schema descriptor for thumbnail field.
	gallerycacheDescThumbnail := gallerycacheFields[6].Descriptor()
	// gallerycache.DefaultThumbnail holds the default value on creation for the thumbnail field.
	gallerycache.DefaultThumbnail = gallerycacheDescThumbnail.Default.(string)
	// gallerycacheDescPageCount is the schema descriptor for page_count field.
	gallerycacheDescPageCount := gallerycacheFields[7].Descriptor()
	// gallerycache.DefaultPageCount holds the default value on creation for the page_count field.
	gallerycache.DefaultPageCount = gallerycacheDescPageCount.Default.(int)
	// gallerycacheDescRating is the schema descriptor for rating field.
	gallerycacheDescRating := gallerycacheFields[8].Descriptor()
	// gallerycache.DefaultRating holds the default value on creation for the rating field.
	gallerycache.DefaultRating = gallerycacheDescRating.Default.(float64)
	// gallerycacheDescRatingCount is the schema descriptor for rating_count field.
	gallerycacheDescRatingCount := gallerycacheFields[9].Descriptor()
	// gallerycache.DefaultRatingCount holds the default value on creation for the rating_count field.
	gallerycache.DefaultRatingCount = gallerycacheDescRatingCount.Default.(int)
	// gallerycacheDescUploader is the schema descriptor for uploader field.
	gallerycacheDescUploader := gallerycacheFields[10].Descriptor()
	// gallerycache.DefaultUploader holds the default value on creation for the uploader field.
	gallerycache.DefaultUploader = gallerycacheDescUploader.Default.(string)
	// gallerycacheDescPosted is the schema descriptor for posted field.
	gallerycacheDescPosted := gallerycacheFields[11].Descriptor()
	// gallerycache.DefaultPosted holds the default value on creation for the posted field.
	gallerycache.DefaultPosted = gallerycacheDescPosted.Default.(string)
	// gallerycacheDescLanguage is the schema descriptor for language field.
	gallerycacheDescLanguage := gallerycacheFields[13].Descriptor()
	// gallerycache.DefaultLanguage holds the default value on creation for the language field.
	gallerycache.DefaultLanguage = gallerycacheDescLanguage.Default.(string)
	// gallerycacheDescTranslated is the schema descriptor for translated field.
	gallerycacheDescTranslated := gallerycacheFields[14].Descriptor()
	// gallerycache.DefaultTranslated holds the default value on creation for the translated field.
	gallerycache.DefaultTranslated = gallerycacheDescTranslated.Default.(bool)
	// gallerycacheDescFileSize is the schema descriptor for file_size field.
	gallerycacheDescFileSize := gallerycacheFields[15].Descriptor()
	// gallerycache.DefaultFileSize holds the default value on creation for the file_size field.
	gallerycache.DefaultFileSize = gallerycacheDescFileSize.Default.(string)
	// gallerycacheDescFavorited is the schema descriptor for favorited field.
	gallerycacheDescFavorited := gallerycacheFields[16].Descriptor()
	// gallerycache.DefaultFavorited holds the default value on creation for the favorited field.
	gallerycache.DefaultFavorited = gallerycacheDescFavorited.Default.(int)
	// gallerycacheDescExpunged is the schema descriptor for expunged field.
	gallerycacheDescExpunged := gallerycacheFields[17].Descriptor()
	// gallerycache.DefaultExpunged holds the default value on creation for the expunged field.
	gallerycache.DefaultExpunged = gallerycacheDescExpunged.Default.(bool)
	// gallerycacheDescUpdatedAt is the schema descriptor for updated_at field.
	gallerycacheDescUpdatedAt := gallerycacheFields[25].Descriptor()
	// gallerycache.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	gallerycache.DefaultUpdatedAt = gallerycacheDescUpdatedAt.Default.(func() time.Time)
	// gallerycache.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	gallerycache.UpdateDefaultUpdatedAt = gallerycacheDescUpdatedAt.UpdateDefault.(func() time.Time)
	prefilljobFields := schema.PrefillJob{}.Fields()
	_ = prefilljobFields
	// prefilljobDescToken is the schema descriptor for token field.
	prefilljobDescToken := prefilljobFields[2].Descriptor()
	// prefilljob.DefaultToken holds the default value on creation for the token field.
	prefilljob.DefaultToken = prefilljobDescToken.Default.(string)
	// prefilljobDescTitle is the schema descriptor for title field.
	prefilljobDescTitle := prefilljobFields[3].Descriptor()
	// prefilljob.DefaultTitle holds the default value on creation for the title field.
	prefilljob.DefaultTitle = prefilljobDescTitle.Default.(string)
	// prefilljobDescStatus is the schema descriptor for status field.
	prefilljobDescStatus := prefilljobFields[5].Descriptor()
	// prefilljob.DefaultStatus holds the default value on creation for the status field.
	prefilljob.DefaultStatus = prefilljobDescStatus.Default.(string)
	// prefilljobDescTotal is the schema descriptor for total field.
	prefilljobDescTotal := prefilljobFields[6].Descriptor()
	// prefilljob.DefaultTotal holds the default value on creation for the total field.
	prefilljob.DefaultTotal = prefilljobDescTotal.Default.(int)
	// prefilljobDescFailedCount is the schema descriptor for failed_count field.
	prefilljobDescFailedCount := prefilljobFields[7].Descriptor()
	// prefilljob.DefaultFailedCount holds the default value on creation for the failed_count field.
	prefilljob.DefaultFailedCount = prefilljobDescFailedCount.Default.(int)
	// prefilljobDescCreatedAt is the schema descriptor for created_at field.
	prefilljobDescCreatedAt := prefilljobFields[9].Descriptor()
	// prefilljob.DefaultCreatedAt holds the default value on creation for the created_at field.
	prefilljob.DefaultCreatedAt = prefilljobDescCreatedAt.Default.(func() time.Time)
	// prefilljobDescUpdatedAt is the schema descriptor for updated_at field.
	prefilljobDescUpdatedAt := prefilljobFields[10].Descriptor()
	// prefilljob.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	prefilljob.DefaultUpdatedAt = prefilljobDescUpdatedAt.Default.(func() time.Time)
	// prefilljob.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	prefilljob.UpdateDefaultUpdatedAt = prefilljobDescUpdatedAt.UpdateDefault.(func() time.Time)
	// prefilljobDescID is the schema descriptor for id field.
	prefilljobDescID := prefilljobFields[0].Descriptor()
	// prefilljob.DefaultID holds the default value on creation for the id field.
	prefilljob.DefaultID = prefilljobDescID.Default.(func() uuid.UUID)
	readingprogressFields := schema.ReadingProgress{}.Fields()
	_ = readingprogressFields
	// readingprogressDescCurrentPage is the schema descriptor for current_page field.
	readingprogressDescCurrentPage := readingprogressFields[2].Descriptor()
	// readingprogress.DefaultCurrentPage holds the default value on creation for the current_page field.
	readingprogress.DefaultCurrentPage = readingprogressDescCurrentPage.Default.(int)
	// readingprogress.CurrentPageValidator is a validator for the "current_page" field. It is called by the builders before save.
	readingprogress.CurrentPageValidator = readingprogressDescCurrentPage.Validators[0].(func(int) error)
	// readingprogressDescProgress is the schema descriptor for progress field.
	readingprogressDescProgress := readingprogressFields[3].Descriptor()
	// readingprogress.DefaultProgress holds the default value on creation for the progress field.
	readingprogress.DefaultProgress = readingprogressDescProgress.Default.(float64)
	// readingprogress.ProgressValidator is a validator for the "progress" field. It is called by the builders before save.
	readingprogress.ProgressValidator = func() func(float64) error {
		validators := readingprogressDescProgress.Validators
		fns := [...]func(float64) error{
			validators[0].(func(float64) error),
			validators[1].(func(float64) error),
		}
		return func(progress float64) error {
			for _, fn := range fns {
				if err := fn(progress); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// readingprogressDescCompleted is the schema descriptor for completed field.
	readingprogressDescCompleted := readingprogressFields[4].Descriptor()
	// readingprogress.DefaultCompleted holds the default value on creation for the completed field.
	readingprogress.DefaultCompleted = readingprogressDescCompleted.Default.(bool)
	// readingprogressDescCreatedAt is the schema descriptor for created_at field.
	readingprogressDescCreatedAt := readingprogressFields[5].Descriptor()
	// readingprogress.DefaultCreatedAt holds the default value on creation for the created_at field.
	readingprogress.DefaultCreatedAt = readingprogressDescCreatedAt.Default.(func() time.Time)
	// readingprogressDescUpdatedAt is the schema descriptor for updated_at field.
	readingprogressDescUpdatedAt := readingprogressFields[6].Descriptor()
	// readingprogress.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	readingprogress.DefaultUpdatedAt = readingprogressDescUpdatedAt.Default.(func() time.Time)
	// readingprogress.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	readingprogress.UpdateDefaultUpdatedAt = readingprogressDescUpdatedAt.UpdateDefault.(func() time.Time)
	settingFields := schema.Setting{}.Fields()
	_ = settingFields
	// settingDescKey is the schema descriptor for key field.
	settingDescKey := settingFields[0].Descriptor()
	// setting.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	setting.KeyValidator = settingDescKey.Validators[0].(func(string) error)
	// settingDescUpdatedAt is the schema descriptor for updated_at field.
	settingDescUpdatedAt := settingFields[2].Descriptor()
	// setting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	setting.DefaultUpdatedAt = settingDescUpdatedAt.Default.(func() time.Time)
	// setting.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	setting.UpdateDefaultUpdatedAt = settingDescUpdatedAt.UpdateDefault.(func() time.Time)
}
