// Code generated by ent, DO NOT EDIT.

package ent

import (
	"manga-reader/internal/ent/bookshelf"
	"manga-reader/internal/ent/readingprogress"
	"manga-reader/internal/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	bookshelfFields := schema.Bookshelf{}.Fields()
	_ = bookshelfFields
	// bookshelfDescTitle is the schema descriptor for title field.
	bookshelfDescTitle := bookshelfFields[2].Descriptor()
	// bookshelf.DefaultTitle holds the default value on creation for the title field.
	bookshelf.DefaultTitle = bookshelfDescTitle.Default.(string)
	// bookshelfDescTitleJpn is the schema descriptor for title_jpn field.
	bookshelfDescTitleJpn := bookshelfFields[3].Descriptor()
	// bookshelf.DefaultTitleJpn holds the default value on creation for the title_jpn field.
	bookshelf.DefaultTitleJpn = bookshelfDescTitleJpn.Default.(string)
	// bookshelfDescCategory is the schema descriptor for category field.
	bookshelfDescCategory := bookshelfFields[4].Descriptor()
	// bookshelf.DefaultCategory holds the default value on creation for the category field.
	bookshelf.DefaultCategory = bookshelfDescCategory.Default.(string)
	// bookshelfDescThumbnail is the schema descriptor for thumbnail field.
	bookshelfDescThumbnail := bookshelfFields[5].Descriptor()
	// bookshelf.DefaultThumbnail holds the default value on creation for the thumbnail field.
	bookshelf.DefaultThumbnail = bookshelfDescThumbnail.Default.(string)
	// bookshelfDescPageCount is the schema descriptor for page_count field.
	bookshelfDescPageCount := bookshelfFields[6].Descriptor()
	// bookshelf.DefaultPageCount holds the default value on creation for the page_count field.
	bookshelf.DefaultPageCount = bookshelfDescPageCount.Default.(int)
	// bookshelfDescAddedAt is the schema descriptor for added_at field.
	bookshelfDescAddedAt := bookshelfFields[7].Descriptor()
	// bookshelf.DefaultAddedAt holds the default value on creation for the added_at field.
	bookshelf.DefaultAddedAt = bookshelfDescAddedAt.Default.(func() time.Time)
	// bookshelfDescUpdatedAt is the schema descriptor for updated_at field.
	bookshelfDescUpdatedAt := bookshelfFields[8].Descriptor()
	// bookshelf.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	bookshelf.DefaultUpdatedAt = bookshelfDescUpdatedAt.Default.(func() time.Time)
	// bookshelf.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	bookshelf.UpdateDefaultUpdatedAt = bookshelfDescUpdatedAt.UpdateDefault.(func() time.Time)
	readingprogressFields := schema.ReadingProgress{}.Fields()
	_ = readingprogressFields
	// readingprogressDescCurrentPage is the schema descriptor for current_page field.
	readingprogressDescCurrentPage := readingprogressFields[2].Descriptor()
	// readingprogress.DefaultCurrentPage holds the default value on creation for the current_page field.
	readingprogress.DefaultCurrentPage = readingprogressDescCurrentPage.Default.(int)
	// readingprogress.CurrentPageValidator is a validator for the "current_page" field. It is called by the builders before save.
	readingprogress.CurrentPageValidator = readingprogressDescCurrentPage.Validators[0].(func(int) error)
	// readingprogressDescProgress is the schema descriptor for progress field.
	readingprogressDescProgress := readingprogressFields[3].Descriptor()
	// readingprogress.DefaultProgress holds the default value on creation for the progress field.
	readingprogress.DefaultProgress = readingprogressDescProgress.Default.(float64)
	// readingprogress.ProgressValidator is a validator for the "progress" field. It is called by the builders before save.
	readingprogress.ProgressValidator = func() func(float64) error {
		validators := readingprogressDescProgress.Validators
		fns := [...]func(float64) error{
			validators[0].(func(float64) error),
			validators[1].(func(float64) error),
		}
		return func(progress float64) error {
			for _, fn := range fns {
				if err := fn(progress); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// readingprogressDescCompleted is the schema descriptor for completed field.
	readingprogressDescCompleted := readingprogressFields[4].Descriptor()
	// readingprogress.DefaultCompleted holds the default value on creation for the completed field.
	readingprogress.DefaultCompleted = readingprogressDescCompleted.Default.(bool)
	// readingprogressDescUpdatedAt is the schema descriptor for updated_at field.
	readingprogressDescUpdatedAt := readingprogressFields[6].Descriptor()
	// readingprogress.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	readingprogress.UpdateDefaultUpdatedAt = readingprogressDescUpdatedAt.UpdateDefault.(func() time.Time)
}
