// Code generated by ent, DO NOT EDIT.

package gallerycache

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the gallerycache type in the database.
	Label = "gallery_cache"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGalleryID holds the string denoting the gallery_id field in the database.
	FieldGalleryID = "gallery_id"
	// FieldToken holds the string denoting the token field in the database.
	FieldToken = "token"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldTitleJpn holds the string denoting the title_jpn field in the database.
	FieldTitleJpn = "title_jpn"
	// FieldCategory holds the string denoting the category field in the database.
	FieldCategory = "category"
	// FieldThumbnail holds the string denoting the thumbnail field in the database.
	FieldThumbnail = "thumbnail"
	// FieldPageCount holds the string denoting the page_count field in the database.
	FieldPageCount = "page_count"
	// FieldRating holds the string denoting the rating field in the database.
	FieldRating = "rating"
	// FieldRatingCount holds the string denoting the rating_count field in the database.
	FieldRatingCount = "rating_count"
	// FieldUploader holds the string denoting the uploader field in the database.
	FieldUploader = "uploader"
	// FieldPosted holds the string denoting the posted field in the database.
	FieldPosted = "posted"
	// FieldPostedAt holds the string denoting the posted_at field in the database.
	FieldPostedAt = "posted_at"
	// FieldLanguage holds the string denoting the language field in the database.
	FieldLanguage = "language"
	// FieldTranslated holds the string denoting the translated field in the database.
	FieldTranslated = "translated"
	// FieldFileSize holds the string denoting the file_size field in the database.
	FieldFileSize = "file_size"
	// FieldFavorited holds the string denoting the favorited field in the database.
	FieldFavorited = "favorited"
	// FieldExpunged holds the string denoting the expunged field in the database.
	FieldExpunged = "expunged"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldPageUrls holds the string denoting the page_urls field in the database.
	FieldPageUrls = "page_urls"
	// FieldThumbnails holds the string denoting the thumbnails field in the database.
	FieldThumbnails = "thumbnails"
	// FieldMetaFetchedAt holds the string denoting the meta_fetched_at field in the database.
	FieldMetaFetchedAt = "meta_fetched_at"
	// FieldDetailsFetchedAt holds the string denoting the details_fetched_at field in the database.
	FieldDetailsFetchedAt = "details_fetched_at"
	// FieldPagesFetchedAt holds the string denoting the pages_fetched_at field in the database.
	FieldPagesFetchedAt = "pages_fetched_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the gallerycache in the database.
	Table = "gallery_cache"
)

// Columns holds all SQL columns for gallerycache fields.
var Columns = []string{
	FieldID,
	FieldGalleryID,
	FieldToken,
	FieldCreatedAt,
	FieldTitle,
	FieldTitleJpn,
	FieldCategory,
	FieldThumbnail,
	FieldPageCount,
	FieldRating,
	FieldRatingCount,
	FieldUploader,
	FieldPosted,
	FieldPostedAt,
	FieldLanguage,
	FieldTranslated,
	FieldFileSize,
	FieldFavorited,
	FieldExpunged,
	FieldTags,
	FieldPageUrls,
	FieldThumbnails,
	FieldMetaFetchedAt,
	FieldDetailsFetchedAt,
	FieldPagesFetchedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultTitle holds the default value on creation for the "title" field.
	DefaultTitle string
	// DefaultTitleJpn holds the default value on creation for the "title_jpn" field.
	DefaultTitleJpn string
	// DefaultCategory holds the default value on creation for the "category" field.
	DefaultCategory string
	// DefaultThumbnail holds the default value on creation for the "thumbnail" field.
	DefaultThumbnail string
	// DefaultPageCount holds the default value on creation for the "page_count" field.
	DefaultPageCount int
	// DefaultRating holds the default value on creation for the "rating" field.
	DefaultRating float64
	// DefaultRatingCount holds the default value on creation for the "rating_count" field.
	DefaultRatingCount int
	// DefaultUploader holds the default value on creation for the "uploader" field.
	DefaultUploader string
	// DefaultPosted holds the default value on creation for the "posted" field.
	DefaultPosted string
	// DefaultLanguage holds the default value on creation for the "language" field.
	DefaultLanguage string
	// DefaultTranslated holds the default value on creation for the "translated" field.
	DefaultTranslated bool
	// DefaultFileSize holds the default value on creation for the "file_size" field.
	DefaultFileSize string
	// DefaultFavorited holds the default value on creation for the "favorited" field.
	DefaultFavorited int
	// DefaultExpunged holds the default value on creation for the "expunged" field.
	DefaultExpunged bool
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the GalleryCache queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByGalleryID orders the results by the gallery_id field.
func ByGalleryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGalleryID, opts...).ToFunc()
}

// ByToken orders the results by the token field.
func ByToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToken, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByTitleJpn orders the results by the title_jpn field.
func ByTitleJpn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitleJpn, opts...).ToFunc()
}

// ByCategory orders the results by the category field.
func ByCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategory, opts...).ToFunc()
}

// ByThumbnail orders the results by the thumbnail field.
func ByThumbnail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldThumbnail, opts...).ToFunc()
}

// ByPageCount orders the results by the page_count field.
func ByPageCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPageCount, opts...).ToFunc()
}

// ByRating orders the results by the rating field.
func ByRating(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRating, opts...).ToFunc()
}

// ByRatingCount orders the results by the rating_count field.
func ByRatingCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRatingCount, opts...).ToFunc()
}

// ByUploader orders the results by the uploader field.
func ByUploader(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUploader, opts...).ToFunc()
}

// ByPosted orders the results by the posted field.
func ByPosted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPosted, opts...).ToFunc()
}

// ByPostedAt orders the results by the posted_at field.
func ByPostedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPostedAt, opts...).ToFunc()
}

// ByLanguage orders the results by the language field.
func ByLanguage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLanguage, opts...).ToFunc()
}

// ByTranslated orders the results by the translated field.
func ByTranslated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTranslated, opts...).ToFunc()
}

// ByFileSize orders the results by the file_size field.
func ByFileSize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileSize, opts...).ToFunc()
}

// ByFavorited orders the results by the favorited field.
func ByFavorited(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFavorited, opts...).ToFunc()
}

// ByExpunged orders the results by the expunged field.
func ByExpunged(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpunged, opts...).ToFunc()
}

// ByMetaFetchedAt orders the results by the meta_fetched_at field.
func ByMetaFetchedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetaFetchedAt, opts...).ToFunc()
}

// ByDetailsFetchedAt orders the results by the details_fetched_at field.
func ByDetailsFetchedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDetailsFetchedAt, opts...).ToFunc()
}

// ByPagesFetchedAt orders the results by the pages_fetched_at field.
func ByPagesFetchedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPagesFetchedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
