// Code generated by ent, DO NOT EDIT.

package readingprogress

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the readingprogress type in the database.
	Label = "reading_progress"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGalleryID holds the string denoting the gallery_id field in the database.
	FieldGalleryID = "gallery_id"
	// FieldToken holds the string denoting the token field in the database.
	FieldToken = "token"
	// FieldCurrentPage holds the string denoting the current_page field in the database.
	FieldCurrentPage = "current_page"
	// FieldProgress holds the string denoting the progress field in the database.
	FieldProgress = "progress"
	// FieldCompleted holds the string denoting the completed field in the database.
	FieldCompleted = "completed"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the readingprogress in the database.
	Table = "reading_progress"
)

// Columns holds all SQL columns for readingprogress fields.
var Columns = []string{
	FieldID,
	FieldGalleryID,
	FieldToken,
	FieldCurrentPage,
	FieldProgress,
	FieldCompleted,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCurrentPage holds the default value on creation for the "current_page" field.
	DefaultCurrentPage int
	// CurrentPageValidator is a validator for the "current_page" field. It is called by the builders before save.
	CurrentPageValidator func(int) error
	// DefaultProgress holds the default value on creation for the "progress" field.
	DefaultProgress float64
	// ProgressValidator is a validator for the "progress" field. It is called by the builders before save.
	ProgressValidator func(float64) error
	// DefaultCompleted holds the default value on creation for the "completed" field.
	DefaultCompleted bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the ReadingProgress queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByGalleryID orders the results by the gallery_id field.
func ByGalleryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGalleryID, opts...).ToFunc()
}

// ByToken orders the results by the token field.
func ByToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToken, opts...).ToFunc()
}

// ByCurrentPage orders the results by the current_page field.
func ByCurrentPage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentPage, opts...).ToFunc()
}

// ByProgress orders the results by the progress field.
func ByProgress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProgress, opts...).ToFunc()
}

// ByCompleted orders the results by the completed field.
func ByCompleted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompleted, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
