// Code generated by ent, DO NOT EDIT.

package readingprogress

import (
	"manga-reader/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldLTE(FieldID, id))
}

// GalleryID applies equality check predicate on the "gallery_id" field. It's identical to GalleryIDEQ.
func GalleryID(v int64) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldEQ(FieldGalleryID, v))
}

// Token applies equality check predicate on the "token" field. It's identical to TokenEQ.
func Token(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldEQ(FieldToken, v))
}

// CurrentPage applies equality check predicate on the "current_page" field. It's identical to CurrentPageEQ.
func CurrentPage(v int) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldEQ(FieldCurrentPage, v))
}

// Progress applies equality check predicate on the "progress" field. It's identical to ProgressEQ.
func Progress(v float64) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldEQ(FieldProgress, v))
}

// Completed applies equality check predicate on the "completed" field. It's identical to CompletedEQ.
func Completed(v bool) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldEQ(FieldCompleted, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldEQ(FieldTitle, v))
}

// TitleJpn applies equality check predicate on the "title_jpn" field. It's identical to TitleJpnEQ.
func TitleJpn(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldEQ(FieldTitleJpn, v))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldEQ(FieldCategory, v))
}

// Thumbnail applies equality check predicate on the "thumbnail" field. It's identical to ThumbnailEQ.
func Thumbnail(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldEQ(FieldThumbnail, v))
}

// PageCount applies equality check predicate on the "page_count" field. It's identical to PageCountEQ.
func PageCount(v int) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldEQ(FieldPageCount, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldEQ(FieldStartedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldEQ(FieldUpdatedAt, v))
}

// GalleryIDEQ applies the EQ predicate on the "gallery_id" field.
func GalleryIDEQ(v int64) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldEQ(FieldGalleryID, v))
}

// GalleryIDNEQ applies the NEQ predicate on the "gallery_id" field.
func GalleryIDNEQ(v int64) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldNEQ(FieldGalleryID, v))
}

// GalleryIDIn applies the In predicate on the "gallery_id" field.
func GalleryIDIn(vs ...int64) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldIn(FieldGalleryID, vs...))
}

// GalleryIDNotIn applies the NotIn predicate on the "gallery_id" field.
func GalleryIDNotIn(vs ...int64) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldNotIn(FieldGalleryID, vs...))
}

// GalleryIDGT applies the GT predicate on the "gallery_id" field.
func GalleryIDGT(v int64) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldGT(FieldGalleryID, v))
}

// GalleryIDGTE applies the GTE predicate on the "gallery_id" field.
func GalleryIDGTE(v int64) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldGTE(FieldGalleryID, v))
}

// GalleryIDLT applies the LT predicate on the "gallery_id" field.
func GalleryIDLT(v int64) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldLT(FieldGalleryID, v))
}

// GalleryIDLTE applies the LTE predicate on the "gallery_id" field.
func GalleryIDLTE(v int64) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldLTE(FieldGalleryID, v))
}

// TokenEQ applies the EQ predicate on the "token" field.
func TokenEQ(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldEQ(FieldToken, v))
}

// TokenNEQ applies the NEQ predicate on the "token" field.
func TokenNEQ(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldNEQ(FieldToken, v))
}

// TokenIn applies the In predicate on the "token" field.
func TokenIn(vs ...string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldIn(FieldToken, vs...))
}

// TokenNotIn applies the NotIn predicate on the "token" field.
func TokenNotIn(vs ...string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldNotIn(FieldToken, vs...))
}

// TokenGT applies the GT predicate on the "token" field.
func TokenGT(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldGT(FieldToken, v))
}

// TokenGTE applies the GTE predicate on the "token" field.
func TokenGTE(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldGTE(FieldToken, v))
}

// TokenLT applies the LT predicate on the "token" field.
func TokenLT(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldLT(FieldToken, v))
}

// TokenLTE applies the LTE predicate on the "token" field.
func TokenLTE(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldLTE(FieldToken, v))
}

// TokenContains applies the Contains predicate on the "token" field.
func TokenContains(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldContains(FieldToken, v))
}

// TokenHasPrefix applies the HasPrefix predicate on the "token" field.
func TokenHasPrefix(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldHasPrefix(FieldToken, v))
}

// TokenHasSuffix applies the HasSuffix predicate on the "token" field.
func TokenHasSuffix(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldHasSuffix(FieldToken, v))
}

// TokenEqualFold applies the EqualFold predicate on the "token" field.
func TokenEqualFold(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldEqualFold(FieldToken, v))
}

// TokenContainsFold applies the ContainsFold predicate on the "token" field.
func TokenContainsFold(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldContainsFold(FieldToken, v))
}

// CurrentPageEQ applies the EQ predicate on the "current_page" field.
func CurrentPageEQ(v int) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldEQ(FieldCurrentPage, v))
}

// CurrentPageNEQ applies the NEQ predicate on the "current_page" field.
func CurrentPageNEQ(v int) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldNEQ(FieldCurrentPage, v))
}

// CurrentPageIn applies the In predicate on the "current_page" field.
func CurrentPageIn(vs ...int) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldIn(FieldCurrentPage, vs...))
}

// CurrentPageNotIn applies the NotIn predicate on the "current_page" field.
func CurrentPageNotIn(vs ...int) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldNotIn(FieldCurrentPage, vs...))
}

// CurrentPageGT applies the GT predicate on the "current_page" field.
func CurrentPageGT(v int) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldGT(FieldCurrentPage, v))
}

// CurrentPageGTE applies the GTE predicate on the "current_page" field.
func CurrentPageGTE(v int) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldGTE(FieldCurrentPage, v))
}

// CurrentPageLT applies the LT predicate on the "current_page" field.
func CurrentPageLT(v int) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldLT(FieldCurrentPage, v))
}

// CurrentPageLTE applies the LTE predicate on the "current_page" field.
func CurrentPageLTE(v int) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldLTE(FieldCurrentPage, v))
}

// ProgressEQ applies the EQ predicate on the "progress" field.
func ProgressEQ(v float64) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldEQ(FieldProgress, v))
}

// ProgressNEQ applies the NEQ predicate on the "progress" field.
func ProgressNEQ(v float64) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldNEQ(FieldProgress, v))
}

// ProgressIn applies the In predicate on the "progress" field.
func ProgressIn(vs ...float64) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldIn(FieldProgress, vs...))
}

// ProgressNotIn applies the NotIn predicate on the "progress" field.
func ProgressNotIn(vs ...float64) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldNotIn(FieldProgress, vs...))
}

// ProgressGT applies the GT predicate on the "progress" field.
func ProgressGT(v float64) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldGT(FieldProgress, v))
}

// ProgressGTE applies the GTE predicate on the "progress" field.
func ProgressGTE(v float64) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldGTE(FieldProgress, v))
}

// ProgressLT applies the LT predicate on the "progress" field.
func ProgressLT(v float64) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldLT(FieldProgress, v))
}

// ProgressLTE applies the LTE predicate on the "progress" field.
func ProgressLTE(v float64) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldLTE(FieldProgress, v))
}

// CompletedEQ applies the EQ predicate on the "completed" field.
func CompletedEQ(v bool) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldEQ(FieldCompleted, v))
}

// CompletedNEQ applies the NEQ predicate on the "completed" field.
func CompletedNEQ(v bool) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldNEQ(FieldCompleted, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldContainsFold(FieldTitle, v))
}

// TitleJpnEQ applies the EQ predicate on the "title_jpn" field.
func TitleJpnEQ(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldEQ(FieldTitleJpn, v))
}

// TitleJpnNEQ applies the NEQ predicate on the "title_jpn" field.
func TitleJpnNEQ(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldNEQ(FieldTitleJpn, v))
}

// TitleJpnIn applies the In predicate on the "title_jpn" field.
func TitleJpnIn(vs ...string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldIn(FieldTitleJpn, vs...))
}

// TitleJpnNotIn applies the NotIn predicate on the "title_jpn" field.
func TitleJpnNotIn(vs ...string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldNotIn(FieldTitleJpn, vs...))
}

// TitleJpnGT applies the GT predicate on the "title_jpn" field.
func TitleJpnGT(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldGT(FieldTitleJpn, v))
}

// TitleJpnGTE applies the GTE predicate on the "title_jpn" field.
func TitleJpnGTE(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldGTE(FieldTitleJpn, v))
}

// TitleJpnLT applies the LT predicate on the "title_jpn" field.
func TitleJpnLT(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldLT(FieldTitleJpn, v))
}

// TitleJpnLTE applies the LTE predicate on the "title_jpn" field.
func TitleJpnLTE(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldLTE(FieldTitleJpn, v))
}

// TitleJpnContains applies the Contains predicate on the "title_jpn" field.
func TitleJpnContains(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldContains(FieldTitleJpn, v))
}

// TitleJpnHasPrefix applies the HasPrefix predicate on the "title_jpn" field.
func TitleJpnHasPrefix(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldHasPrefix(FieldTitleJpn, v))
}

// TitleJpnHasSuffix applies the HasSuffix predicate on the "title_jpn" field.
func TitleJpnHasSuffix(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldHasSuffix(FieldTitleJpn, v))
}

// TitleJpnEqualFold applies the EqualFold predicate on the "title_jpn" field.
func TitleJpnEqualFold(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldEqualFold(FieldTitleJpn, v))
}

// TitleJpnContainsFold applies the ContainsFold predicate on the "title_jpn" field.
func TitleJpnContainsFold(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldContainsFold(FieldTitleJpn, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldContainsFold(FieldCategory, v))
}

// ThumbnailEQ applies the EQ predicate on the "thumbnail" field.
func ThumbnailEQ(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldEQ(FieldThumbnail, v))
}

// ThumbnailNEQ applies the NEQ predicate on the "thumbnail" field.
func ThumbnailNEQ(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldNEQ(FieldThumbnail, v))
}

// ThumbnailIn applies the In predicate on the "thumbnail" field.
func ThumbnailIn(vs ...string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldIn(FieldThumbnail, vs...))
}

// ThumbnailNotIn applies the NotIn predicate on the "thumbnail" field.
func ThumbnailNotIn(vs ...string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldNotIn(FieldThumbnail, vs...))
}

// ThumbnailGT applies the GT predicate on the "thumbnail" field.
func ThumbnailGT(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldGT(FieldThumbnail, v))
}

// ThumbnailGTE applies the GTE predicate on the "thumbnail" field.
func ThumbnailGTE(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldGTE(FieldThumbnail, v))
}

// ThumbnailLT applies the LT predicate on the "thumbnail" field.
func ThumbnailLT(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldLT(FieldThumbnail, v))
}

// ThumbnailLTE applies the LTE predicate on the "thumbnail" field.
func ThumbnailLTE(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldLTE(FieldThumbnail, v))
}

// ThumbnailContains applies the Contains predicate on the "thumbnail" field.
func ThumbnailContains(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldContains(FieldThumbnail, v))
}

// ThumbnailHasPrefix applies the HasPrefix predicate on the "thumbnail" field.
func ThumbnailHasPrefix(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldHasPrefix(FieldThumbnail, v))
}

// ThumbnailHasSuffix applies the HasSuffix predicate on the "thumbnail" field.
func ThumbnailHasSuffix(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldHasSuffix(FieldThumbnail, v))
}

// ThumbnailEqualFold applies the EqualFold predicate on the "thumbnail" field.
func ThumbnailEqualFold(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldEqualFold(FieldThumbnail, v))
}

// ThumbnailContainsFold applies the ContainsFold predicate on the "thumbnail" field.
func ThumbnailContainsFold(v string) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldContainsFold(FieldThumbnail, v))
}

// PageCountEQ applies the EQ predicate on the "page_count" field.
func PageCountEQ(v int) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldEQ(FieldPageCount, v))
}

// PageCountNEQ applies the NEQ predicate on the "page_count" field.
func PageCountNEQ(v int) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldNEQ(FieldPageCount, v))
}

// PageCountIn applies the In predicate on the "page_count" field.
func PageCountIn(vs ...int) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldIn(FieldPageCount, vs...))
}

// PageCountNotIn applies the NotIn predicate on the "page_count" field.
func PageCountNotIn(vs ...int) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldNotIn(FieldPageCount, vs...))
}

// PageCountGT applies the GT predicate on the "page_count" field.
func PageCountGT(v int) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldGT(FieldPageCount, v))
}

// PageCountGTE applies the GTE predicate on the "page_count" field.
func PageCountGTE(v int) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldGTE(FieldPageCount, v))
}

// PageCountLT applies the LT predicate on the "page_count" field.
func PageCountLT(v int) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldLT(FieldPageCount, v))
}

// PageCountLTE applies the LTE predicate on the "page_count" field.
func PageCountLTE(v int) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldLTE(FieldPageCount, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldNotNull(FieldStartedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.FieldNotNull(FieldUpdatedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ReadingProgress) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ReadingProgress) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ReadingProgress) predicate.ReadingProgress {
	return predicate.ReadingProgress(sql.NotPredicates(p))
}
