// Code generated by ent, DO NOT EDIT.

package bookshelf

import (
	"manga-reader/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldLTE(FieldID, id))
}

// GalleryID applies equality check predicate on the "gallery_id" field. It's identical to GalleryIDEQ.
func GalleryID(v int64) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldEQ(FieldGalleryID, v))
}

// Token applies equality check predicate on the "token" field. It's identical to TokenEQ.
func Token(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldEQ(FieldToken, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldEQ(FieldUpdatedAt, v))
}

// GalleryIDEQ applies the EQ predicate on the "gallery_id" field.
func GalleryIDEQ(v int64) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldEQ(FieldGalleryID, v))
}

// GalleryIDNEQ applies the NEQ predicate on the "gallery_id" field.
func GalleryIDNEQ(v int64) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldNEQ(FieldGalleryID, v))
}

// GalleryIDIn applies the In predicate on the "gallery_id" field.
func GalleryIDIn(vs ...int64) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldIn(FieldGalleryID, vs...))
}

// GalleryIDNotIn applies the NotIn predicate on the "gallery_id" field.
func GalleryIDNotIn(vs ...int64) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldNotIn(FieldGalleryID, vs...))
}

// GalleryIDGT applies the GT predicate on the "gallery_id" field.
func GalleryIDGT(v int64) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldGT(FieldGalleryID, v))
}

// GalleryIDGTE applies the GTE predicate on the "gallery_id" field.
func GalleryIDGTE(v int64) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldGTE(FieldGalleryID, v))
}

// GalleryIDLT applies the LT predicate on the "gallery_id" field.
func GalleryIDLT(v int64) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldLT(FieldGalleryID, v))
}

// GalleryIDLTE applies the LTE predicate on the "gallery_id" field.
func GalleryIDLTE(v int64) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldLTE(FieldGalleryID, v))
}

// TokenEQ applies the EQ predicate on the "token" field.
func TokenEQ(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldEQ(FieldToken, v))
}

// TokenNEQ applies the NEQ predicate on the "token" field.
func TokenNEQ(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldNEQ(FieldToken, v))
}

// TokenIn applies the In predicate on the "token" field.
func TokenIn(vs ...string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldIn(FieldToken, vs...))
}

// TokenNotIn applies the NotIn predicate on the "token" field.
func TokenNotIn(vs ...string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldNotIn(FieldToken, vs...))
}

// TokenGT applies the GT predicate on the "token" field.
func TokenGT(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldGT(FieldToken, v))
}

// TokenGTE applies the GTE predicate on the "token" field.
func TokenGTE(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldGTE(FieldToken, v))
}

// TokenLT applies the LT predicate on the "token" field.
func TokenLT(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldLT(FieldToken, v))
}

// TokenLTE applies the LTE predicate on the "token" field.
func TokenLTE(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldLTE(FieldToken, v))
}

// TokenContains applies the Contains predicate on the "token" field.
func TokenContains(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldContains(FieldToken, v))
}

// TokenHasPrefix applies the HasPrefix predicate on the "token" field.
func TokenHasPrefix(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldHasPrefix(FieldToken, v))
}

// TokenHasSuffix applies the HasSuffix predicate on the "token" field.
func TokenHasSuffix(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldHasSuffix(FieldToken, v))
}

// TokenEqualFold applies the EqualFold predicate on the "token" field.
func TokenEqualFold(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldEqualFold(FieldToken, v))
}

// TokenContainsFold applies the ContainsFold predicate on the "token" field.
func TokenContainsFold(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldContainsFold(FieldToken, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Bookshelf) predicate.Bookshelf {
	return predicate.Bookshelf(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Bookshelf) predicate.Bookshelf {
	return predicate.Bookshelf(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Bookshelf) predicate.Bookshelf {
	return predicate.Bookshelf(sql.NotPredicates(p))
}
