// Code generated by ent, DO NOT EDIT.

package bookshelf

import (
	"manga-reader/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldLTE(FieldID, id))
}

// GalleryID applies equality check predicate on the "gallery_id" field. It's identical to GalleryIDEQ.
func GalleryID(v int64) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldEQ(FieldGalleryID, v))
}

// Token applies equality check predicate on the "token" field. It's identical to TokenEQ.
func Token(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldEQ(FieldToken, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldEQ(FieldTitle, v))
}

// TitleJpn applies equality check predicate on the "title_jpn" field. It's identical to TitleJpnEQ.
func TitleJpn(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldEQ(FieldTitleJpn, v))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldEQ(FieldCategory, v))
}

// Thumbnail applies equality check predicate on the "thumbnail" field. It's identical to ThumbnailEQ.
func Thumbnail(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldEQ(FieldThumbnail, v))
}

// PageCount applies equality check predicate on the "page_count" field. It's identical to PageCountEQ.
func PageCount(v int) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldEQ(FieldPageCount, v))
}

// AddedAt applies equality check predicate on the "added_at" field. It's identical to AddedAtEQ.
func AddedAt(v time.Time) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldEQ(FieldAddedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldEQ(FieldUpdatedAt, v))
}

// GalleryIDEQ applies the EQ predicate on the "gallery_id" field.
func GalleryIDEQ(v int64) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldEQ(FieldGalleryID, v))
}

// GalleryIDNEQ applies the NEQ predicate on the "gallery_id" field.
func GalleryIDNEQ(v int64) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldNEQ(FieldGalleryID, v))
}

// GalleryIDIn applies the In predicate on the "gallery_id" field.
func GalleryIDIn(vs ...int64) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldIn(FieldGalleryID, vs...))
}

// GalleryIDNotIn applies the NotIn predicate on the "gallery_id" field.
func GalleryIDNotIn(vs ...int64) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldNotIn(FieldGalleryID, vs...))
}

// GalleryIDGT applies the GT predicate on the "gallery_id" field.
func GalleryIDGT(v int64) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldGT(FieldGalleryID, v))
}

// GalleryIDGTE applies the GTE predicate on the "gallery_id" field.
func GalleryIDGTE(v int64) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldGTE(FieldGalleryID, v))
}

// GalleryIDLT applies the LT predicate on the "gallery_id" field.
func GalleryIDLT(v int64) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldLT(FieldGalleryID, v))
}

// GalleryIDLTE applies the LTE predicate on the "gallery_id" field.
func GalleryIDLTE(v int64) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldLTE(FieldGalleryID, v))
}

// TokenEQ applies the EQ predicate on the "token" field.
func TokenEQ(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldEQ(FieldToken, v))
}

// TokenNEQ applies the NEQ predicate on the "token" field.
func TokenNEQ(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldNEQ(FieldToken, v))
}

// TokenIn applies the In predicate on the "token" field.
func TokenIn(vs ...string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldIn(FieldToken, vs...))
}

// TokenNotIn applies the NotIn predicate on the "token" field.
func TokenNotIn(vs ...string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldNotIn(FieldToken, vs...))
}

// TokenGT applies the GT predicate on the "token" field.
func TokenGT(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldGT(FieldToken, v))
}

// TokenGTE applies the GTE predicate on the "token" field.
func TokenGTE(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldGTE(FieldToken, v))
}

// TokenLT applies the LT predicate on the "token" field.
func TokenLT(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldLT(FieldToken, v))
}

// TokenLTE applies the LTE predicate on the "token" field.
func TokenLTE(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldLTE(FieldToken, v))
}

// TokenContains applies the Contains predicate on the "token" field.
func TokenContains(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldContains(FieldToken, v))
}

// TokenHasPrefix applies the HasPrefix predicate on the "token" field.
func TokenHasPrefix(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldHasPrefix(FieldToken, v))
}

// TokenHasSuffix applies the HasSuffix predicate on the "token" field.
func TokenHasSuffix(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldHasSuffix(FieldToken, v))
}

// TokenEqualFold applies the EqualFold predicate on the "token" field.
func TokenEqualFold(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldEqualFold(FieldToken, v))
}

// TokenContainsFold applies the ContainsFold predicate on the "token" field.
func TokenContainsFold(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldContainsFold(FieldToken, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldContainsFold(FieldTitle, v))
}

// TitleJpnEQ applies the EQ predicate on the "title_jpn" field.
func TitleJpnEQ(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldEQ(FieldTitleJpn, v))
}

// TitleJpnNEQ applies the NEQ predicate on the "title_jpn" field.
func TitleJpnNEQ(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldNEQ(FieldTitleJpn, v))
}

// TitleJpnIn applies the In predicate on the "title_jpn" field.
func TitleJpnIn(vs ...string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldIn(FieldTitleJpn, vs...))
}

// TitleJpnNotIn applies the NotIn predicate on the "title_jpn" field.
func TitleJpnNotIn(vs ...string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldNotIn(FieldTitleJpn, vs...))
}

// TitleJpnGT applies the GT predicate on the "title_jpn" field.
func TitleJpnGT(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldGT(FieldTitleJpn, v))
}

// TitleJpnGTE applies the GTE predicate on the "title_jpn" field.
func TitleJpnGTE(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldGTE(FieldTitleJpn, v))
}

// TitleJpnLT applies the LT predicate on the "title_jpn" field.
func TitleJpnLT(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldLT(FieldTitleJpn, v))
}

// TitleJpnLTE applies the LTE predicate on the "title_jpn" field.
func TitleJpnLTE(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldLTE(FieldTitleJpn, v))
}

// TitleJpnContains applies the Contains predicate on the "title_jpn" field.
func TitleJpnContains(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldContains(FieldTitleJpn, v))
}

// TitleJpnHasPrefix applies the HasPrefix predicate on the "title_jpn" field.
func TitleJpnHasPrefix(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldHasPrefix(FieldTitleJpn, v))
}

// TitleJpnHasSuffix applies the HasSuffix predicate on the "title_jpn" field.
func TitleJpnHasSuffix(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldHasSuffix(FieldTitleJpn, v))
}

// TitleJpnEqualFold applies the EqualFold predicate on the "title_jpn" field.
func TitleJpnEqualFold(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldEqualFold(FieldTitleJpn, v))
}

// TitleJpnContainsFold applies the ContainsFold predicate on the "title_jpn" field.
func TitleJpnContainsFold(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldContainsFold(FieldTitleJpn, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldContainsFold(FieldCategory, v))
}

// ThumbnailEQ applies the EQ predicate on the "thumbnail" field.
func ThumbnailEQ(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldEQ(FieldThumbnail, v))
}

// ThumbnailNEQ applies the NEQ predicate on the "thumbnail" field.
func ThumbnailNEQ(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldNEQ(FieldThumbnail, v))
}

// ThumbnailIn applies the In predicate on the "thumbnail" field.
func ThumbnailIn(vs ...string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldIn(FieldThumbnail, vs...))
}

// ThumbnailNotIn applies the NotIn predicate on the "thumbnail" field.
func ThumbnailNotIn(vs ...string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldNotIn(FieldThumbnail, vs...))
}

// ThumbnailGT applies the GT predicate on the "thumbnail" field.
func ThumbnailGT(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldGT(FieldThumbnail, v))
}

// ThumbnailGTE applies the GTE predicate on the "thumbnail" field.
func ThumbnailGTE(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldGTE(FieldThumbnail, v))
}

// ThumbnailLT applies the LT predicate on the "thumbnail" field.
func ThumbnailLT(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldLT(FieldThumbnail, v))
}

// ThumbnailLTE applies the LTE predicate on the "thumbnail" field.
func ThumbnailLTE(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldLTE(FieldThumbnail, v))
}

// ThumbnailContains applies the Contains predicate on the "thumbnail" field.
func ThumbnailContains(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldContains(FieldThumbnail, v))
}

// ThumbnailHasPrefix applies the HasPrefix predicate on the "thumbnail" field.
func ThumbnailHasPrefix(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldHasPrefix(FieldThumbnail, v))
}

// ThumbnailHasSuffix applies the HasSuffix predicate on the "thumbnail" field.
func ThumbnailHasSuffix(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldHasSuffix(FieldThumbnail, v))
}

// ThumbnailEqualFold applies the EqualFold predicate on the "thumbnail" field.
func ThumbnailEqualFold(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldEqualFold(FieldThumbnail, v))
}

// ThumbnailContainsFold applies the ContainsFold predicate on the "thumbnail" field.
func ThumbnailContainsFold(v string) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldContainsFold(FieldThumbnail, v))
}

// PageCountEQ applies the EQ predicate on the "page_count" field.
func PageCountEQ(v int) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldEQ(FieldPageCount, v))
}

// PageCountNEQ applies the NEQ predicate on the "page_count" field.
func PageCountNEQ(v int) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldNEQ(FieldPageCount, v))
}

// PageCountIn applies the In predicate on the "page_count" field.
func PageCountIn(vs ...int) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldIn(FieldPageCount, vs...))
}

// PageCountNotIn applies the NotIn predicate on the "page_count" field.
func PageCountNotIn(vs ...int) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldNotIn(FieldPageCount, vs...))
}

// PageCountGT applies the GT predicate on the "page_count" field.
func PageCountGT(v int) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldGT(FieldPageCount, v))
}

// PageCountGTE applies the GTE predicate on the "page_count" field.
func PageCountGTE(v int) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldGTE(FieldPageCount, v))
}

// PageCountLT applies the LT predicate on the "page_count" field.
func PageCountLT(v int) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldLT(FieldPageCount, v))
}

// PageCountLTE applies the LTE predicate on the "page_count" field.
func PageCountLTE(v int) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldLTE(FieldPageCount, v))
}

// AddedAtEQ applies the EQ predicate on the "added_at" field.
func AddedAtEQ(v time.Time) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldEQ(FieldAddedAt, v))
}

// AddedAtNEQ applies the NEQ predicate on the "added_at" field.
func AddedAtNEQ(v time.Time) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldNEQ(FieldAddedAt, v))
}

// AddedAtIn applies the In predicate on the "added_at" field.
func AddedAtIn(vs ...time.Time) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldIn(FieldAddedAt, vs...))
}

// AddedAtNotIn applies the NotIn predicate on the "added_at" field.
func AddedAtNotIn(vs ...time.Time) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldNotIn(FieldAddedAt, vs...))
}

// AddedAtGT applies the GT predicate on the "added_at" field.
func AddedAtGT(v time.Time) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldGT(FieldAddedAt, v))
}

// AddedAtGTE applies the GTE predicate on the "added_at" field.
func AddedAtGTE(v time.Time) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldGTE(FieldAddedAt, v))
}

// AddedAtLT applies the LT predicate on the "added_at" field.
func AddedAtLT(v time.Time) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldLT(FieldAddedAt, v))
}

// AddedAtLTE applies the LTE predicate on the "added_at" field.
func AddedAtLTE(v time.Time) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldLTE(FieldAddedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Bookshelf {
	return predicate.Bookshelf(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Bookshelf) predicate.Bookshelf {
	return predicate.Bookshelf(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Bookshelf) predicate.Bookshelf {
	return predicate.Bookshelf(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Bookshelf) predicate.Bookshelf {
	return predicate.Bookshelf(sql.NotPredicates(p))
}
